Repository canyongbs/advisingapp, pull requests merged in 2024-09, with the labels that each got.

#996 [ADVAPP-840]: Modify local configuration to allow containers to reach each other via subdomain
  docker-compose.dev.yml
Labels: Change Type | DevOps

#999 [ADVAPP-773]: Label change in contact information
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
Labels: Change Type | Content or Styling Update

#995 [ADVAPP-832] Resolve the security issue tracked under CVE-2024-45048
  app-modules/engagement/src/Actions/GenerateTipTapBodyJson.php
  composer.lock
Labels: Change Type | Bug Fix, Change Type | Dependencies

#1004 [Cleanup] [ADVAPP-853]: Remove need for feature flag, changes, and data migration
  app-modules/ai/database/migrations/2024_09_06_182440_data_convert_ai_settings_max_tokens.php
  app-modules/ai/src/Filament/Pages/ManageAiSettings.php
  app-modules/ai/src/Settings/AiSettings.php
  app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
  app/Enums/FeatureFlag.php
Labels: Change Type | Feature Cleanup

#1005 [ADVAPP-833]: Twilio configuration throwing errors due to change done for demo mode
  app-modules/notification/src/Notifications/Messages/TwilioMessage.php
Labels: Change Type | Bug Fix

#1007 [Hotfix]: 1.26.2
  app-modules/ai/src/Filament/Pages/ManageAiSettings.php
  app-modules/ai/src/Settings/AiSettings.php
  app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
  app-modules/notification/src/Notifications/Messages/TwilioMessage.php
Labels: Change Type | Bug Fix

#1008 [ADVAPP-820]: Introduce a "branding bar" for institutions to integrate their brand name and brand color into the product experience for end users.
  resources/views/vendor/filament-panels/components/layout/index.blade.php
  resources/views/vendor/filament-panels/components/sidebar/index.blade.php
  resources/views/vendor/filament-panels/components/topbar/index.blade.php
Labels: Change Type | New Feature

#1013 [ADVAPP-870]: Fix performance issues with Roles
  app-modules/authorization/composer.json
  app-modules/authorization/database/migrations/2023_07_11_182500_create_permission_tables.php
  app-modules/authorization/src/Models/Concerns/HasRolesWithPivot.php
  app-modules/authorization/src/Models/Role.php
  composer.lock
Labels: Change Type | Bug Fix, Change Type | Dependencies

#1015 [ADVAPP-870]: Fix performance issues with Roles - super admin checks
  app-modules/ai/src/Rules/RestrictSuperAdmin.php
  app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php
  app-modules/authorization/database/migrations/2024_08_14_174150_data_change_authorization.super_admin_to_sass_global_admin_in_roles_table.php
  app-modules/authorization/src/Console/Commands/SetupRoles.php
  app-modules/authorization/src/Enums/LicenseType.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ListRoles.php
  app-modules/authorization/src/Models/Role.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
  app-modules/authorization/tests/Unit/LicenceTypeTest.php
  app-modules/notification/src/Notifications/Channels/EmailChannel.php
  app-modules/notification/src/Notifications/Channels/SmsChannel.php
  app-modules/notification/tests/Features/NotificationSendingTest.php
  app-modules/team/src/Filament/Resources/TeamResource/RelationManagers/UsersRelationManager.php
  app-modules/team/tests/Team/EditTeamTest.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
  app/Jobs/CreateTenantUser.php
  app/Models/Authenticatable.php
  app/Models/Scopes/WithoutSuperAdmin.php
  app/Models/User.php
  app/Providers/AuthServiceProvider.php
  database/seeders/LocalDevelopmentSeeder.php
  database/seeders/SampleSuperAdminUserSeeder.php
  tests/Unit/LicenseSettingsEmailQuotaTracking.php
  tests/Unit/LicenseSettingsSmsQuotaTracking.php
Labels: Change Type | Bug Fix

#1012 [ADVAPP-600] & [ADVAPP-822]: Improve awaitThreadRunCompletion handling & Sometimes users experience a failure message from our Enterprise AI Assistant due to rate limiting
  app-modules/ai/resources/js/chat.js
  app-modules/ai/resources/views/components/assistant.blade.php
  app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
Labels: Change Type | Bug Fix, Change Type | New Feature

#1011 [ADVAPP-848]: Enhance the Thesis Elements integration by allowing an end user user to initiate an on demand sync, and by displaying the status of the last sync time
  app-modules/student-data-model/resources/views/filament/resources/student-resource/sis-sync.blade.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
  app/Multitenancy/Tasks/SwitchSessionDriver.php
  app/Overrides/Laravel/StartSession.php
  app/Providers/AppServiceProvider.php
  app/Services/Olympus.php
Labels: Change Type | New Feature

#1021 [ADVAPP-863] Enhance the AI Utilization report for institutions by tracking AI Assistant exchanges in the line chart
  app-modules/report/src/Filament/Pages/ArtificialIntelligence.php
  app-modules/report/src/Filament/Widgets/ExchangesByMonthLineChart.php
  composer.lock
Labels: Change Type | New Feature

#1020 [ADVAPP-847]: When viewing a list of articles within a category, paginate the results
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalCategoryController.php
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
Labels: Change Type | Content or Styling Update

#1023 [ADVAPP-864]: Enhance the display of Articles by including a count of articles in a given category
  portals/knowledge-management/src/Components/SearchResults.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
Labels: Change Type | Content or Styling Update

#1025 [ADVAPP-855]: Resolve the security issue tracked under CVE-2024-39338
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#1009 [ADVAPP-844]: Track portal views of articles and display them as article metadata
  app-modules/knowledge-base/database/migrations/2024_09_10_171824_add_portal_view_count_in_knowledge_base_articles_table.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalArticleController.php
  database/migrations/2024_09_12_142103_portal_view_count_feature_flag.php
  portals/knowledge-management/src/Pages/ViewArticle.vue
Labels: Change Type | New Feature, Feature Flag Added

#1027 [ADVAPP-872]: Fix the noWidgetData view which has broken height
  app-modules/report/src/Filament/Widgets/PromptsByCategoryDoughnutChart.php
  app-modules/report/src/Filament/Widgets/SpecialActionsDoughnutChart.php
  resources/views/livewire/no-widget-data.blade.php
Labels: Change Type | Content or Styling Update

#1030 [ADVAPP-881]: Enhance message center by indicating whether a person is a student or a prospect
  app-modules/engagement/resources/views/components/message-center-inbox.blade.php
Labels: Change Type | New Feature

#1028 [ADVAPP-888] Introduce the ability to filter prospects by subscriptions from the prospect list
  app-modules/notification/database/factories/SubscriptionFactory.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/prospect/tests/Prospect/ListProspectTest.php
Labels: Change Type | New Feature

#1032 [ADVAPP-882]: Enhance message center by improving the way a linked record works
  app-modules/engagement/resources/views/components/message-center-content.blade.php
Labels: Change Type | New Feature

#1033 [ADVAPP-835]: When attempting to login via SSO and the directory information case does not match the in product user email case, it generates a user not found error instead of logging the user in
  app-modules/authorization/src/Http/Controllers/SocialiteController.php
Labels: Change Type | Bug Fix

#1036 [ADVAPP-860]: Product Ping Health check is failing for all environments
  app/Providers/HealthServiceProvider.php
Labels: Change Type | Bug Fix

#1038 [ADVAPP-769]: Investigate why the rr file does not seem to be present when starting the application for the first time
  .gitignore
  Dockerfile
  docker/s6-overlay/s6-rc.d/symlink-roadrunner/dependencies
  docker/s6-overlay/s6-rc.d/symlink-roadrunner/type
  docker/s6-overlay/s6-rc.d/symlink-roadrunner/up
  docker/s6-overlay/scripts/symlink-roadrunner
  docker/s6-overlay/user/symlink-roadrunner
Labels: Change Type | DevOps

#1034 [ADVAPP-886]: Improve the notifications received when a user is added to a care team
  app-modules/care-team/src/Observers/CareTeamObserver.php
Labels: Change Type | New Feature

#1044 [ADVAPP-910] & [ADVAPP-891] & [ADVAPP-892]: Switch to class based feature flagging
  .github/pull_request_template.md
  app-modules/ai/database/migrations/2024_09_06_182440_data_convert_ai_settings_max_tokens.php
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalArticleController.php
  app/Enums/FeatureFlag.php
  app/Features/.gitkeep
  app/Features/EnableInteractionInitiativesFeature.php
  app/Providers/AppServiceProvider.php
  app/Support/AbstractFeatureFlag.php
  database/migrations/2024_09_12_142103_portal_view_count_feature_flag.php
  docs/data-migrations.md
  docs/feature-flagging.md
  portals/knowledge-management/src/Pages/ViewArticle.vue
  stubs/feature.stub
Labels: Change Type | Documentation, Change Type | New Feature, Change Type | Feature Cleanup

#1042 [ADVAPP-903]: Eliminate "performance" from the student data model.
  app-modules/report/src/Client/AiReportChatClient.php
  app-modules/student-data-model/config/roles/web/student_management.php
  app-modules/student-data-model/graphql/performance.graphql
  app-modules/student-data-model/graphql/student.graphql
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentInformation.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/PerformanceRelationManager.php
  app-modules/student-data-model/src/Filament/Tables/StudentsTable.php
  app-modules/student-data-model/src/Models/Performance.php
  app-modules/student-data-model/src/Models/Student.php
  app-modules/student-data-model/src/Providers/StudentDataModelServiceProvider.php
  database/migrations/2024_05_07_133937_seed_permissions.php
  database/migrations/2024_09_27_105155_drop_performance_table.php
  database/migrations/2024_09_27_110403_data_remove_performance_permission_from_permissions_table.php
  database/seeders/StudentSeeder.php
Labels: Change Type | Feature Cleanup

#1046 [ADVAPP-911]: When a user attempts to configure a custom assistant or institutional assistant with an assigned Canyon 4o mini model, the option fails to present
  app-modules/ai/src/Enums/AiApplication.php
Labels: Change Type | Bug Fix

#1041 [ADVAPP-871]: Prevent the deletion of a prompt-type that has an active relationship to a prompt.
  app-modules/ai/src/Filament/Resources/PromptTypeResource/Pages/ListPromptTypes.php
  app-modules/ai/src/Policies/PromptTypePolicy.php
Labels: Change Type | Bug Fix
