Repository canyongbs/advisingapp, pull requests merged in 2024-08, with the labels that each got.

#937 [ADVAPP-775]: Receiving false notifications that the scheduler in the application is not working when it is
  _ide_helper_models.php
  app/Console/Kernel.php
  app/Providers/HealthServiceProvider.php
  composer.json
  composer.lock
  resources/views/vendor/filament-spatie-health/pages/health-check-results.blade.php
Labels: Change Type | Bug Fix

#939 [ADVAPP-780]: Update instructions in message center to be more user friendly
  app-modules/engagement/resources/views/components/empty-state.blade.php
Labels: Change Type | Content or Styling Update

#942 [ADVAPP-779]: Sorting Tasks by Due Date on My Dashboard in the Recruitment CRM does not appropriately reorder the list
  app-modules/task/src/Filament/Widgets/TasksWidget.php
Labels: Change Type | Bug Fix

#944 [ADVAPP-791]: Fix issue causing Advising App tenant deployment from Olympus failure
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#941 [ADVAPP-746]: Add error handling to AI Chat Completions
  app-modules/campaign/src/Filament/Blocks/Actions/DraftCampaignEngagementBlockWithAi.php
  app-modules/engagement/src/Filament/Actions/DraftWithAiAction.php
  app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords/Actions/DraftWithAiAction.php
  app-modules/engagement/src/Filament/Resources/Actions/DraftTemplateWithAiAction.php
  app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
Labels: Change Type | New Feature

#940 [ADVAPP-781]: Enhance the Prospect and Student care team experience by allowing the ability to add more than one staff member at a time
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentCareTeam.php
Labels: Change Type | New Feature

#946 [Hotfix]: 1.21.1
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#950 [ADVAPP-803]: Old flowbite svg is still referenced in Landlord page
  resources/views/landlord.blade.php
Labels: Change Type | Content or Styling Update

#951 [ADVAPP-772]: Update the student and prospect data model to better handle an alternate email address
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
Labels: Change Type | Content or Styling Update

#955 [ADVAPP-804]: [Cleanup]: change-agent-name feature flag
  app-modules/audit/database/migrations/2024_08_12_155524_data_purge_change_agent_name_feature_flag.php
  app-modules/audit/src/Filament/Exports/AuditExporter.php
  app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php
  app-modules/audit/src/Filament/Resources/AuditResource/Pages/ViewAudit.php
Labels: Change Type | Feature Cleanup

#954 [ADVAPP-802] Update default logo images used for light and dark mode in the product
  resources/images/default-logo-dark.png
  resources/images/default-logo-dark.svg
  resources/images/default-logo-light.png
  resources/images/default-logo-light.svg
  resources/views/vendor/filament-panels/components/logo.blade.php
  resources/views/vendor/mail/html/header.blade.php
Labels: Change Type | Content or Styling Update

#949 [ADVAPP-786] Introduce Draft with AI for knowledge base articles
  app-modules/knowledge-base/resources/views/filament/actions/draft-with-ai-modal-content-knowledge-base.blade.php
  app-modules/knowledge-base/src/Filament/Actions/DraftKnowledgeBaseArticleWithAiAction.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/EditKnowledgeBaseArticle.php
Labels: Change Type | New Feature

#953 [ADVAPP-783]: Introduce Draft with AI for student and prospect interactions
  app-modules/interaction/resources/views/filament/actions/draft-with-ai-modal-content.blade.php
  app-modules/interaction/src/Filament/Actions/DraftInteractionWithAiAction.php
  app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/CreateInteraction.php
Labels: Change Type | New Feature

#959 [OLYMPUS-88]: Ensure Olympus connect to other products works locally
  app/Console/Commands/ConnectOlympus.php
Labels: Change Type | Bug Fix

#958 [ADVAPP-792]: Optimize tracked events database table(s) based on prior release
  app-modules/report/database/migrations/2024_08_06_192219_data_activate_tracked_events.php
  app-modules/report/database/migrations/2024_08_06_195151_data_backfill_ai_exchanges.php
  app-modules/report/database/migrations/2024_08_06_202738_data_backfill_ai_thread_saved.php
  app-modules/report/src/Filament/Widgets/AiStats.php
  app-modules/report/src/Jobs/RecordTrackedEvent.php
Labels: Change Type | Feature Cleanup

#961 [ADVAPP-805]: Restrict the ability to grant overly permissive rights to users
  app-modules/ai/src/Rules/RestrictSuperAdmin.php
  app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php
  app-modules/authorization/database/migrations/2024_08_14_174150_data_change_authorization.super_admin_to_sass_global_admin_in_roles_table.php
  app-modules/authorization/src/Console/Commands/SetupRoles.php
  app-modules/authorization/src/Enums/LicenseType.php
  app-modules/authorization/src/Models/Role.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
  app-modules/authorization/tests/Unit/LicenceTypeTest.php
  app-modules/notification/src/Notifications/Channels/EmailChannel.php
  app-modules/notification/src/Notifications/Channels/SmsChannel.php
  app-modules/notification/tests/Features/NotificationSendingTest.php
  app-modules/team/src/Filament/Resources/TeamResource/RelationManagers/UsersRelationManager.php
  app-modules/team/tests/Team/EditTeamTest.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
  app/Jobs/CreateTenantUser.php
  app/Models/Scopes/WithoutSuperAdmin.php
  app/Models/User.php
  app/Providers/AuthServiceProvider.php
  database/seeders/LocalDevelopmentSeeder.php
  database/seeders/SampleSuperAdminUserSeeder.php
  tests/Unit/LicenseSettingsEmailQuotaTracking.php
  tests/Unit/LicenseSettingsSmsQuotaTracking.php
Labels: Change Type | New Feature

#968 [ADVAPP-807]: [Cleanup]: ai-log-features
  app-modules/ai/database/migrations/2024_08_13_195739_data_activate_ai_log_features.php
  app-modules/ai/database/migrations/2024_08_13_210121_data_backfill_assistant_chat_message_logs_feature_column.php
  app-modules/ai/src/Actions/CompletePrompt.php
  app-modules/ai/src/Filament/Resources/LegacyAiMessageLogResource.php
  app-modules/ai/src/Listeners/CreateAiMessageLog.php
Labels: Change Type | Feature Cleanup

#969 [ADVAPP-809]: Draft with AI for student and prospect interactions generates an exception
  app-modules/interaction/src/Filament/Actions/DraftInteractionWithAiAction.php
Labels: Change Type | Bug Fix

#966 [ADVAPP-806]: CVE-2024-39338
  Dockerfile
  package-lock.json
Labels: Change Type | Dependencies

#962 [ADVAPP-778]: An exception is sometimes thrown during the thread pruning process
  app-modules/ai/src/Listeners/DeleteExternalAiMessageFile.php
  app-modules/ai/src/Listeners/DeleteExternalAiThread.php
Labels: Change Type | Bug Fix

#963 [ADVAPP-808]: Fix "fatal: No names found, cannot describe anything." during CI/CD
  .github/workflows/ci.yml
  app-modules/service-management/src/Models/ChangeRequest.php
  phpstan.neon.dist
  phpunit-ci.xml
Labels: Change Type | Bug Fix

#965 [ADVAPP-767]: Mimetype validation errors do not display for rounded upload inputs
  composer.lock
Labels: Change Type | Bug Fix

#972 [ADVAPP-798]: When draft with AI is used in campaigns, formatting is not preserved from the AI output
  resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php
Labels: Change Type | Bug Fix

#973 [ADVAPP-800]: Create new integration settings for Thesis Elements SIS integration
  _ide_helper_models.php
  app-modules/student-data-model/database/migrations/2024_08_19_202551_create_student_information_system_settings.php
  app-modules/student-data-model/database/migrations/2024_08_19_203311_data_activate__sis_integration_settings.php
  app-modules/student-data-model/database/migrations/2024_08_19_204749_seed_permissions_add_manage_sis_settings.php
  app-modules/student-data-model/resources/views/filament/resources/student-resource/sis-sync.blade.php
  app-modules/student-data-model/src/Enums/SisSystem.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentInformationSystemSettings.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
  app-modules/student-data-model/src/Models/Student.php
  app-modules/student-data-model/src/Settings/StudentInformationSystemSettings.php
  app/Enums/FeatureFlag.php
  docker-compose.dev.yml
Labels: Change Type | New Feature

#978 [Bugfix]: fix build task
  docker/s6-overlay/s6-rc.d/build-assets/dependencies
  docker/s6-overlay/s6-rc.d/build-assets/type
  docker/s6-overlay/s6-rc.d/build-assets/up
  docker/s6-overlay/s6-rc.d/laravel-octane/dependencies
  docker/s6-overlay/scripts/build-assets
  docker/s6-overlay/user/build-assets
  docs/local-setup.md
Labels: Change Type | Bug Fix

#984 [ADVAPP-797]: Introduce "demo mode" for email and text messaging
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
  app-modules/integration-twilio/src/Providers/IntegrationTwilioServiceProvider.php
  app-modules/integration-twilio/src/Settings/TwilioSettings.php
  app-modules/notification/src/Notifications/Channels/EmailChannel.php
  app-modules/notification/src/Notifications/Channels/SmsChannel.php
  app/Console/Commands/CreateTenant.php
  app/Http/Controllers/Tenants/CreateTenantController.php
  app/Multitenancy/DataTransferObjects/TenantMailConfig.php
  app/Multitenancy/Tasks/SwitchMailTask.php
  database/factories/TenantFactory.php
  tests/TestCase.php
Labels: Change Type | New Feature

#983 [ADVAPP-823]: When a conversation is cloned via the Enterprise AI Assistant, it generates an error.
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php
  app-modules/ai/src/Jobs/CloneAiThread.php
  app-modules/ai/src/Jobs/PrepareAiThreadCloning.php
  app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php
  app-modules/basic-needs/database/factories/BasicNeedsProgramFactory.php
Labels: Change Type | Bug Fix

#985 [ADVAPP-828]: Update GitHub Action step versions
  .github/workflows/ci.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  .github/workflows/update_yearly_copyright.yml
Labels: Change Type | Dependencies
