Repository canyongbs/advisingapp, pull requests merged in 2024-11, with the labels that each got.

#1097 [ADVAPP-962]: Update the language used when there are no interactions on a student or prospect record
  app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
Labels: Change Type | Content or Styling Update

#1098 [ADVAPP-896]: Improve processing speed for chat in the Enterprise AI Assistant
  app-modules/ai/resources/js/chat.js
  app-modules/ai/resources/js/chats.js
  app-modules/ai/resources/views/components/assistant.blade.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageFolders.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php
  app-modules/ai/src/Models/AiThread.php
  app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php
  composer.json
  composer.lock
  config/clockwork.php
  storage/clockwork/.gitignore
Labels: Change Type | New Feature

#1093 [ADVAPP-965] : Add filters for the campaign list view for my campaigns, enabled, and has been executed
  app-modules/campaign/database/factories/CampaignFactory.php
  app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/ListCampaigns.php
  app-modules/campaign/tests/Actions/ListCampaignsTest.php
Labels: Change Type | New Feature

#1103 [ADVAPP-969]: Add the ability to merge the value in for the preferred name of a student and prospect in engagement scenarios
  app-modules/campaign/src/Filament/Blocks/EngagementBatchEmailBlock.php
  app-modules/campaign/src/Filament/Blocks/EngagementBatchSmsBlock.php
  app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
  app-modules/engagement/src/Filament/Actions/SendEngagementAction.php
  app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Fields/EngagementSmsBodyField.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php
  app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/CreateSmsTemplate.php
  app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/EditSmsTemplate.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/form/src/Filament/Resources/FormResource/Pages/ManageFormEmailAutoReply.php
  app-modules/form/src/Models/FormEmailAutoReply.php
  app-modules/prospect/src/Models/Prospect.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentEngagementRelationManager.php
  app-modules/student-data-model/src/Models/Student.php
Labels: Change Type | New Feature

#1108 [ADVAPP-990]: Update rule title for Programs to Number of Programs
  app-modules/student-data-model/src/Filament/Tables/StudentsTable.php
Labels: Change Type | Content or Styling Update

#1105 [ADVAPP-987]: Feature Flag Cleanup: ProspectStatusSystemProtectionAndAutoAssignment
  app-modules/prospect/database/factories/ProspectStatusFactory.php
  app-modules/prospect/database/migrations/2024_10_08_174319_data_activate_feature_flag_prospect_status_system_protection_and_auto_assignment.php
  app-modules/prospect/database/seeders/ProspectStatusSeeder.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Actions/ConvertToStudent.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Actions/DisassociateStudent.php
  app-modules/prospect/src/Filament/Resources/ProspectStatusResource/Pages/ViewProspectStatus.php
  app-modules/prospect/src/Policies/ProspectStatusPolicy.php
  app/Features/ProspectStatusSystemProtectionAndAutoAssignment.php
Labels: Change Type | Feature Cleanup

#1106 [ADVAPP-988]: Indicate student or prospect's name when that task is related to a student or prospect in the resulting notification.
  app-modules/task/src/Notifications/TaskAssignedToUserNotification.php
Labels: Change Type | Content or Styling Update

#1112 [ADVAPP-854]: Prevent sending SMS messages to Prospects or Students with no Mobile number set
  app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
  app-modules/engagement/src/Filament/Actions/SendEngagementAction.php
  app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/EditEngagement.php
  app-modules/engagement/src/Models/EngagementBatch.php
  app-modules/prospect/src/Models/Prospect.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentEngagementRelationManager.php
  app-modules/student-data-model/src/Models/Student.php
Labels: Change Type | Bug Fix

#1114 [ADVAPP-991]: Text message body content does not appear when a text campaign action is opened using its associated edit link.
  app-modules/campaign/src/Filament/Blocks/EngagementBatchSmsBlock.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Fields/EngagementSmsBodyField.php
Labels: Change Type | Bug Fix

#1115 [ADVAPP-982]: When attempting to create a draft with the AI assistant on the student profile page to create a new email or text, an error is generated
  app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords/Actions/DraftWithAiAction.php
Labels: Change Type | Bug Fix

#1116 [ADVAPP-983]: When attempting to request a form in the student profile, an error is generated
  app-modules/form/src/Filament/Actions/RequestFormSubmission.php
Labels: Change Type | Bug Fix

#1118 [ADVAPP-899]: When attempting to set a hyperlink via the GDPR configuration, the path to the link is incorrectly constructed when attempting to follow it
  composer.lock
Labels: Change Type | Bug Fix

#1121 [ADVAPP-1006]: Disassociate results in a page not found error
  app-modules/prospect/src/Filament/Resources/ProspectResource/Actions/ConvertToStudent.php
Labels: Change Type | Bug Fix

#1124 [ADVAPP-996]: Update the Advising App logo used in the header
  resources/images/default-logo-dark-201124.svg
  resources/images/default-logo-light-201124.svg
  resources/views/vendor/filament-panels/components/logo.blade.php
  resources/views/vendor/mail/html/header.blade.php
Labels: Change Type | Documentation

#1125 [ADVAPP-1002]: After creating an interaction, I am unable to delete it, even with the appropriate permissions.
  app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
Labels: Change Type | Bug Fix

#1127 [ADVAPP-1001]: Modify the iconography to be more consistent in the collapsed view of the navigation
  app-modules/ai/src/Filament/Resources/PromptResource.php
  app-modules/application/src/Filament/Resources/ApplicationResource.php
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
  app-modules/campaign/src/Filament/Resources/CampaignResource.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/form/src/Filament/Resources/FormResource.php
  app-modules/in-app-communication/src/Filament/Pages/UserChat.php
  app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php
  app-modules/meeting-center/src/Filament/Resources/EventResource.php
  app-modules/prospect/src/Filament/Pages/RecruitmentCrmDashboard.php
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
  app-modules/report/src/Filament/Pages/ReportAssistant.php
  app-modules/report/src/Filament/Pages/TaskManagement.php
  app-modules/report/src/Filament/Resources/ReportResource.php
  app-modules/resource-hub/src/Filament/Resources/ResourceHubArticleResource.php
  app-modules/segment/src/Filament/Resources/SegmentResource.php
  app-modules/student-data-model/src/Filament/Pages/RetentionCrmDashboard.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource.php
  app-modules/survey/src/Filament/Resources/SurveyResource.php
  app-modules/task/src/Filament/Resources/TaskResource.php
  app/Filament/Clusters/ArtificialIntelligence.php
  app/Filament/Clusters/Communication.php
  app/Filament/Clusters/ConstituentManagement.php
  app/Filament/Clusters/GlobalSettings.php
  app/Filament/Clusters/InteractionManagement.php
  app/Filament/Clusters/OnlineAdmissions.php
  app/Filament/Clusters/ProfileManagement.php
  app/Filament/Clusters/ReportLibrary.php
  app/Filament/Clusters/ResourceHub.php
  app/Filament/Clusters/ServiceManagement.php
  app/Filament/Clusters/ServiceManagementAdministration.php
  app/Filament/Clusters/UsageAuditing.php
  app/Filament/Clusters/UserManagement.php
Labels: Change Type | Documentation

#1133 [ADVAPP-1010]: Update placeholder text for Message Center search box
  app-modules/engagement/resources/views/components/search.blade.php
  composer.lock
Labels: Change Type | Content or Styling Update

#1130 [ADVAPP-1021]: Update the naming of constituent management settings in Product Administration.
  app-modules/prospect/src/Filament/Pages/ManageProspectConversionSettings.php
  app-modules/prospect/src/Filament/Resources/ProspectSourceResource.php
  app-modules/prospect/src/Filament/Resources/ProspectStatusResource.php
Labels: Change Type | Documentation

#1137 [ADVAPP-1027]: Failure to retrieve Azure profile image causes issues with login
  app-modules/authorization/src/Http/Controllers/SocialiteController.php
Labels: Change Type | Bug Fix

#1136 [ADVAPP-1003]: Enhance the abilities of global search by including preferred name in search results.
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource.php
Labels: Change Type | Documentation

#1141 [AIDAPP-951]: Enhance the pipeline management experience to limit Kanban view when not practical
  app-modules/prospect/resources/views/filament/pages/manage-pipeline-educatables.blade.php
  app-modules/prospect/src/Filament/Resources/PipelineResource/Pages/ManageEductables.php
Labels: Change Type | New Feature

#1142 [ADVAPP-955]: Some campaign actions are generating an exception
  app-modules/engagement/src/Actions/EngagementSmsChannelDelivery.php
  app-modules/student-data-model/src/Models/Contracts/Educatable.php
Labels: Change Type | Bug Fix

#1144 [ADVAPP-941] & [ADVAPP-973]: Fix polymorphic relationship saved values
  app-modules/case-management/database/migrations/2024_11_26_223109_data_fix_audit_polymorphic_types_for_service_request_rename.php
  app-modules/resource-hub/database/migrations/2024_11_26_221634_data_fix_audit_polymorphic_types_for_knowledge_base_rename.php
  app-modules/resource-hub/database/migrations/2024_11_26_222012_data_fix_media_polymorphic_types_for_knowledge_base_rename.php
Labels: Change Type | Bug Fix

#1143 [ADVAPP-1004]: Enhance the user list experience by adding search
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: Change Type | New Feature

#1129 [ADVAPP-979]: Enhance the user list experience by introducing a filter for "no assigned team"
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: Change Type | New Feature

#1145 [OLYMPUS-196]: Ensure all requests between Olympus and the other application are done over HTTPS
  app/Console/Commands/ConnectOlympus.php
Labels: Change Type | Bug Fix

#1134 [ADVAPP-978]: Enhance the user list experience by introducing filters for users who have no assigned permissions
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: Change Type | New Feature

#1148 [ADVAPP-1028]: Feature Flag Cleanup: CaseManagement
  app-modules/campaign/src/Filament/Blocks/CaseBlock.php
  app-modules/case-management/src/Models/CaseAssignment.php
  app-modules/case-management/src/Models/CaseForm.php
  app-modules/case-management/src/Models/CaseFormAuthentication.php
  app-modules/case-management/src/Models/CaseFormField.php
  app-modules/case-management/src/Models/CaseFormStep.php
  app-modules/case-management/src/Models/CaseFormSubmission.php
  app-modules/case-management/src/Models/CaseHistory.php
  app-modules/case-management/src/Models/CaseModel.php
  app-modules/case-management/src/Models/CasePriority.php
  app-modules/case-management/src/Models/CaseStatus.php
  app-modules/case-management/src/Models/CaseType.php
  app-modules/case-management/src/Models/CaseUpdate.php
  app-modules/case-management/src/Policies/CaseAssignmentPolicy.php
  app-modules/case-management/src/Policies/CaseFormPolicy.php
  app-modules/case-management/src/Policies/CaseHistoryPolicy.php
  app-modules/case-management/src/Policies/CaseModelPolicy.php
  app-modules/case-management/src/Policies/CasePriorityPolicy.php
  app-modules/case-management/src/Policies/CaseStatusPolicy.php
  app-modules/case-management/src/Policies/CaseTypePolicy.php
  app-modules/case-management/src/Policies/CaseUpdatePolicy.php
  app/Features/CaseManagement.php
  database/migrations/2024_11_22_085206_data_activate_feature_flag_case_management.php
Labels: Change Type | Feature Cleanup

#1150 [ADVAPP-1024]: Feature Flag Cleanup: ResourceHub
  app-modules/resource-hub/src/Filament/Resources/ResourceHubArticleResource/Pages/ListResourceHubArticles.php
  app-modules/resource-hub/src/Models/ResourceHubArticle.php
  app-modules/resource-hub/src/Models/ResourceHubArticleUpvote.php
  app-modules/resource-hub/src/Models/ResourceHubArticleView.php
  app-modules/resource-hub/src/Models/ResourceHubCategory.php
  app-modules/resource-hub/src/Models/ResourceHubQuality.php
  app-modules/resource-hub/src/Models/ResourceHubStatus.php
  app-modules/resource-hub/src/Policies/ResourceHubArticlePolicy.php
  app-modules/resource-hub/src/Policies/ResourceHubCategoryPolicy.php
  app-modules/resource-hub/src/Policies/ResourceHubQualityPolicy.php
  app-modules/resource-hub/src/Policies/ResourceHubStatusPolicy.php
  app/Features/ResourceHub.php
  database/migrations/2024_11_20_054640_data_activate_feature_flag_resource_hub.php
Labels: Change Type | Feature Cleanup
