Repository canyongbs/advisingapp, pull requests merged in 2024-05, with the labels that each got.

#697 [ADVAPP-523]: Illuminate\View\ViewException
  app/Multitenancy/Http/Middleware/NeedsTenant.php
  app/Providers/Filament/AdminPanelProvider.php
  app/Providers/Filament/LandlordPanelProvider.php
  app/Providers/RouteServiceProvider.php
  docker/s6-overlay/s6-rc.d/nginx/data/check
  resources/views/errors/404.blade.php
  tests/Feature/Multitenancy/Http/Middleware/NeedsTenantTest.php
Labels: Change Type | Bug Fix, Change Type | DevOps

#693 [ADVAPP-516]: Red asterisk indicating a field is required does not display on form render
  widgets/application/src/App.vue
  widgets/event-registration/src/App.vue
  widgets/form/src/App.vue
  widgets/form/src/FormKit/asterisk.js
  widgets/form/src/FormKit/theme.js
  widgets/service-request-form/src/App.vue
  widgets/survey/src/App.vue
Labels: Change Type | New Feature

#698 [ADVAPP-530]: AI Assistant default Assistant is not created when Custom Assistant setting is turned off
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
Labels: Change Type | Bug Fix

#699 [Hotfix] Remove bucket details
  .env.example
Labels: Change Type | Content or Styling Update

#705 [ADVAPP-536]: Unable to insert email template.
  resources/views/vendor/filament-panels/resources/relation-manager.blade.php
Labels: Change Type | Bug Fix

#707 [ADVAPP-535]: Add user job title to care team presentation.
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentCareTeam.php
Labels: Change Type | New Feature

#706 [ADVAPP-551] Introduce inline "Download" action for uploaded files and documents
  app-modules/engagement/src/Filament/Resources/EngagementFileResource/RelationManagers/EngagementFilesRelationManager.php
Labels: Change Type | Content or Styling Update

#713 [ADVAPP-532] Add ability to hide source, status and created fields in the prospect list.
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
Labels: Change Type | Content or Styling Update

#719 [ADVAPP-420]: Ensure our custom @feature directive works along-side the Laravel Pennant @feature directive
  _ide_helper_models.php
  app-modules/form/src/Models/FormFieldSubmission.php
  app-modules/knowledge-base/graphql/knowledge-base-article.graphql
  app-modules/survey/src/Models/SurveyFieldSubmission.php
  app/GraphQL/Directives/AddonDirective.php
  config/app.php
Labels: Change Type | New Feature

#716 [ADVAPP-546] Rename article metadata
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/EditKnowledgeBaseArticle.php
Labels: Change Type | Content or Styling Update

#715 [AIDAPP-533] Update recruitment dashboard headings
  app-modules/prospect/src/Filament/Widgets/ProspectStats.php
Labels: Change Type | Content or Styling Update

#714 [ADVAPP-539]: Investigate pasting of certain content into email results in fatal errors
  app-modules/engagement/src/Actions/GenerateEmailMarkdownContent.php
Labels: Change Type | Bug Fix

#721 [ADVAPP-496]: Update docs and Docker Compose to remove Minio
  .env.example
  docker-compose.dev.yml
  docs/local-setup.md
Labels: Change Type | Content or Styling Update, Change Type | DevOps

#724 [ADVAPP-538] Add merge values for first name and last name
  app-modules/campaign/src/Filament/Blocks/EngagementBatchBlock.php
  app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Fields/EngagementSmsBodyField.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/CreateEngagement.php
  app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/CreateSmsTemplate.php
  app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/EditSmsTemplate.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/form/src/Filament/Resources/FormResource/Pages/ManageFormEmailAutoReply.php
  app-modules/form/src/Models/FormEmailAutoReply.php
  app-modules/prospect/src/Models/Prospect.php
  app-modules/student-data-model/src/Models/Student.php
Labels: Change Type | New Feature

#730 [ADVAPP-560] Enhance the icon display for mime types under files and documents
  app-modules/engagement/src/Filament/Resources/EngagementFileResource/RelationManagers/EngagementFilesRelationManager.php
  app-modules/student-data-model/src/Models/Student.php
Labels: Change Type | Content or Styling Update

#732 [ADVAPP-561] Enhance file uploads to work with specific types
  app-modules/engagement/src/Filament/Resources/EngagementFileResource.php
  app-modules/engagement/src/Models/EngagementFile.php
Labels: Change Type | Content or Styling Update

#735 [Hotfix] Remove unneeded permission seed
  database/migrations/2024_05_06_161618_seed_permission_add_manage_display_settings.php
Labels: Change Type | Bug Fix

#739 [Hotfix] Fix updating the AISettings on change
  app-modules/assistant/src/Jobs/UpdateAiAssistantJob.php
  app/Listeners/Contracts/HandleSettingsSaved.php
  app/Listeners/HandleSettingsSaved.php
  app/Multitenancy/Tasks/SwitchBindings.php
  app/Providers/AppServiceProvider.php
  app/Providers/EventServiceProvider.php
  config/multitenancy.php
Labels: Change Type | Bug Fix

#740 [Hotfix]: Adjust how users are searched and selected in Team User manager
  app-modules/team/src/Filament/Resources/TeamResource/RelationManagers/UsersRelationManager.php
Labels: Change Type | New Feature

#736 [ADVAPP-565]: Email templates content breaks when you save them on the edit page
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php
  app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/EditSmsTemplate.php
Labels: Change Type | Bug Fix

#737 [ADVAPP-562]: Regression - Embed issue with navigation bar
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/DesktopSidebar.vue
  portals/knowledge-management/src/Pages/Home.vue
Labels: Change Type | Bug Fix, Change Type | Content or Styling Update

#754 [Hotfix] Reduce default queue workers started
  Dockerfile
Labels: Change Type | Bug Fix, Change Type | DevOps

#751 ADVAPP-585-Enhance the default sort for users to be by name
  app/Filament/Resources/UserResource.php
Labels: Change Type | New Feature

#752 ADVAPP-583 - In the Product Users list, move Created At and Updated A…
  app/Filament/Resources/UserResource.php
Labels: Change Type | New Feature

#758 Hotfix/improved thread recreate
  app-modules/ai/src/Console/Commands/ReInitializeAiThreads.php
  app-modules/ai/src/Jobs/ReInitializeAiThread.php
  app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
Labels: Change Type | Bug Fix

#760 [Hotfix] 1.11.3
  app-modules/ai/src/Console/Commands/ReInitializeAiThreads.php
  app-modules/ai/src/Jobs/ReInitializeAiThread.php
  app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
Labels: Change Type | Bug Fix

#757 Make job title and email toggleable in product user table
  app/Filament/Resources/UserResource.php
Labels: Change Type | New Feature

#750 [ADVAPP-595] Restrict viewing of super admin users to other super admin users
  app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ViewUserTest.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
  app/Filament/Resources/UserResource/Pages/ViewUser.php
  app/Models/Scopes/WithoutSuperAdmin.php
  app/Models/User.php
Labels: Change Type | New Feature

#763 [ADVAPP-580]: Update label for Create User login via social provider
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Filament/Resources/UserResource/Pages/ViewUser.php
Labels: Change Type | Content or Styling Update

#761 [ADVAPP-570]: Correct the name of the SES settings
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app/Filament/Clusters/GlobalSettings/Pages/AmazonS3.php
  resources/views/filament/clusters/global-settings/pages/amazon-s3.blade.php
Labels: Change Type | New Feature, Change Type | Content or Styling Update

#765 [Bugfix] Reset the Storage Facade on change
  app/Multitenancy/Tasks/SwitchS3FilesystemTask.php
  app/Multitenancy/Tasks/SwitchS3PublicFilesystemTask.php
Labels: Change Type | Bug Fix

#764 [ADVAPP-377]: Scope the granted Knowledge Management API token appropriately to limit abuse
  app-modules/portal/routes/api.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalAuthenticateController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalLogoutController.php
  app-modules/portal/src/Http/Middleware/AuthenticateIfRequiredByPortalDefinition.php
  app/Filament/Resources/SystemUserResource/Pages/EditSystemUser.php
  app/Http/Kernel.php
  config/lighthouse.php
Labels: Change Type | New Feature

#762 [ADVAPP-584] In the Product Users list, display three new columns for license status
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: Change Type | New Feature

#767 Keep toggle on when SSO settings are on
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
Labels: Change Type | New Feature

#770 ADVAPP-612 Improve label for Custom AI Assistant usage
  app-modules/ai/resources/views/components/assistant.blade.php
Labels: Change Type | New Feature

#769 [ADVAPP-611] Regression: Mobile view fails to display correctly for AI Assistant
  app-modules/ai/resources/js/chat.js
  app-modules/ai/resources/views/components/assistant.blade.php
Labels: Change Type | Content or Styling Update

#766 [ADVAPP-592] Footer sticky issue fix in assistant page
  app-modules/ai/resources/js/chat.js
  app-modules/ai/resources/views/components/assistant.blade.php
Labels: Change Type | Content or Styling Update

#772 [Bugfix] Increase AI Max Length to 25000
  app-modules/ai/resources/views/components/assistant.blade.php
  app-modules/ai/src/Http/Requests/SendMessageRequest.php
Labels: Change Type | Bug Fix

#771 ADVAPP-615 Decrease prominence of AI Assistant badge
  app-modules/ai/resources/views/components/assistant.blade.php
  tailwind.config.js
Labels: Change Type | Content or Styling Update

#773 [Hotfix] 1.12.1 Hotfix
  app-modules/ai/resources/js/chat.js
  app-modules/ai/resources/views/components/assistant.blade.php
  app-modules/ai/src/Http/Requests/SendMessageRequest.php
Labels: Change Type | Bug Fix
