Repository canyongbs/advisingapp, pull requests merged in 2024-12, with the labels that each got.

#1152 [ADVAPP-1040]: Extend the capabilities of email editing with font color and clear formatting toolbar items
  bin/build.js
  composer.lock
  config/filament-tiptap-editor.php
Labels: Change Type | New Feature

#1151 [ADVAPP-1038]: Purge experimental reporting from the system
  app-modules/ai/src/Enums/AiApplication.php
  app-modules/ai/src/Enums/AiModel.php
  app-modules/ai/tests/Feature/Actions/CreateThreadTest.php
  app-modules/report/src/Client/AiReportChatClient.php
  app-modules/report/src/Filament/Pages/ManageReportAssistantSettings.php
  app-modules/report/src/Filament/Pages/ReportAssistant.php
  app-modules/report/src/Settings/ReportAssistantSettings.php
  app/Console/Commands/CreateTenant.php
  app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php
  app/Enums/Feature.php
  app/Filament/Pages/ManageLicenseSettings.php
  app/Http/Requests/Tenants/CreateTenantRequest.php
  app/Http/Requests/Tenants/SyncTenantRequest.php
  app/Providers/AppServiceProvider.php
  database/migrations/Legacy/2023_09_13_160013_report_assistant_settings.php
  database/migrations/Legacy/2024_11_29_133232_data_drop_report_assistant_settings.php
  tests/TestCase.php
Labels: Change Type | Feature Cleanup

#1154 [ADVAPP-1036]: Enhance timeline by switching from a modal to a page with a back button after clicking through the student detail page
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/view-educatable-activity-feed.blade.php
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-activity-feed-widget.blade.php
  app-modules/student-data-model/resources/views/filament/resources/student-resource/view-student.blade.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/HasEducatableActivityFeed.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableActivityFeedWidget.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudentActivityFeed.php
Labels: Change Type | New Feature

#1156 [ADVAPP-1047]: API documentation fails to generate after introducing flexible statuses on alerts
  app-modules/alert/graphql/alert-status.graphql
  app-modules/alert/graphql/alert.graphql
  app-modules/alert/src/Providers/AlertServiceProvider.php
Labels: Change Type | Bug Fix

#1158 [Bugfix]: Update canyongbs/filament-tiptap-editor
  composer.lock
Labels: Change Type | Bug Fix

#1159 [Hotfix]: 1.40.2
  composer.lock
Labels: Change Type | Bug Fix

#1162 [ADVAPP-1049]: When attempting to create a new alert status, it results in an error
  app-modules/alert/src/Filament/Resources/AlertStatusResource/Pages/ViewAlertStatus.php
Labels: Change Type | Bug Fix

#1160 [ADVAPP-977]: Enhance the user list experience by introducing filters for each license type
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: Change Type | New Feature

#1163 [ADVAPP-1011]: Add count to filter icon for message center
  app-modules/engagement/resources/views/components/message-center-inbox.blade.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
Labels: Change Type | New Feature

#1161 [ADVAPP-1030]: Database Migration Cleanup: polymorphic relationship saved values
  app-modules/case-management/database/migrations/2024_11_26_223109_data_fix_audit_polymorphic_types_for_service_request_rename.php
  app-modules/resource-hub/database/migrations/2024_11_26_221634_data_fix_audit_polymorphic_types_for_knowledge_base_rename.php
  app-modules/resource-hub/database/migrations/2024_11_26_222012_data_fix_media_polymorphic_types_for_knowledge_base_rename.php
Labels: Change Type | Feature Cleanup

#1167 [ADVAPP-1045]: Feature Flag Cleanup: AlertStatusId
  app-modules/alert/database/migrations/2024_11_17_062514_data_alert_statuses_table.php
  app-modules/alert/database/migrations/2024_11_17_093824_data_add_data_in_status_id_in_alerts_table.php
  app-modules/alert/database/migrations/2024_12_02_174519_data_activate_feature_flag_alert_status_id.php
  app-modules/alert/resources/views/components/created-history-timeline-item.blade.php
  app-modules/alert/src/Filament/Actions/AlertHistoryCreatedViewAction.php
  app-modules/alert/src/Filament/Resources/AlertResource/Pages/ListAlerts.php
  app-modules/alert/src/Filament/Resources/AlertStatusResource.php
  app-modules/alert/src/Models/Alert.php
  app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
  app-modules/prospect/src/Filament/Widgets/ProspectStats.php
  app-modules/report/src/Filament/Exports/StudentExporter.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableAlerts.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableAlertsWidget.php
  app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
  app/Features/AlertStatusId.php
  database/migrations/2024_11_19_112341_data_change_status_to_status_id_in_histories_table.php
Labels: Change Type | Feature Cleanup

#1170 [ADVAPP-1046]:Feature Flag Cleanup: TagFeatureFlag
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectTagResource.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/Concerns/HasStudentHeader.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
  app-modules/student-data-model/src/Filament/Resources/StudentTagResource.php
  app/Features/TagFeatureFlag.php
  database/migrations/2024_12_03_084103_data_tag_active_feature_flag.php
Labels: Change Type | Feature Cleanup

#1172 [ADVAPP-1031]: Modify the iconography to be more consistent in the collapsed view of the navigation
  app-modules/ai/src/Filament/Resources/AiAssistantResource.php
  app-modules/prospect/src/Filament/Resources/PipelineResource.php
  app/Filament/Pages/ProductHealth.php
Labels: Change Type | Bug Fix

#1166 [ADVAPP-1051]: Add event date to user auditing list view and detail view
  app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php
  app-modules/audit/src/Filament/Resources/AuditResource/Pages/ViewAudit.php
Labels: Change Type | Content or Styling Update

#1174 [ADVAPP-1050]: Enhance permissions with a matrix role editor
  app-modules/authorization/resources/views/filament/forms/components/permissions-matrix.blade.php
  app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php
  app-modules/authorization/src/Filament/Resources/RoleResource.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/CreateRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/EditRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ViewRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/RelationManagers/PermissionsRelationManager.php
Labels: Change Type | New Feature

#1178 [ADVAPP-1052]: Add start date and end date optional filters for the event date to the user auditing list view
  app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php
Labels: Change Type | New Feature

#1169 [ADVAPP-1055]: Adjust the scope of table pagination options for all table views
  app-modules/ai/tests/Feature/Filament/Resources/PromptResource/ListPromptsTest.php
  app-modules/ai/tests/Feature/Filament/Resources/PromptTypeResource/ListPromptTypesTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app-modules/basic-needs/tests/BasicNeedsCategory/BasicNeedsCategoryTest.php
  app-modules/basic-needs/tests/BasicNeedsProgram/BasicNeedsProgramTest.php
  app-modules/case-management/tests/Case/ListCasesTest.php
  app-modules/case-management/tests/CaseStatus/ListCaseStatusesTest.php
  app-modules/case-management/tests/CaseType/ListCaseTypeTest.php
  app-modules/case-management/tests/CaseUpdate/ListCaseUpdatesTest.php
  app-modules/prospect/tests/Prospect/ListProspectTest.php
  app-modules/prospect/tests/ProspectSource/ListProspectSourcesTest.php
  app-modules/prospect/tests/ProspectStatus/ListProspectStatusesTest.php
  app-modules/task/tests/ListTasksTest.php
  app/Providers/AppServiceProvider.php
Labels: Change Type | New Feature

#1157 [ADVAPP-1041]: Prevent the removal of a population segment that is associated with an active campaign
  app-modules/segment/src/Filament/Resources/SegmentResource/Pages/ListSegments.php
  app-modules/segment/src/Policies/SegmentPolicy.php
Labels: Change Type | New Feature

#1187 [ADVAPP-1071]: Some permissions are not available in the permissions matrix and syncing of permissions is not available upon change
  app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php
Labels: Change Type | Bug Fix

#1181 [ADVAPP-1056]: Move resource hub from Premium Features to Engagement Features
  app-modules/campaign/src/Filament/Resources/CampaignResource.php
  app-modules/resource-hub/src/Filament/Resources/ResourceHubArticleResource.php
  app-modules/segment/src/Filament/Resources/SegmentResource.php
  app-modules/task/src/Filament/Resources/TaskResource.php
Labels: Change Type | Content or Styling Update

#1184 [ADVAPP-1067]: Provide sample import files for the student model
  app-modules/student-data-model/src/Filament/Resources/ManageStudentResource/Pages/ListManageStudents.php
Labels: Change Type | Bug Fix

#1190 [ADVAPP-1059]: Custom range slider input not properly visible in dark mode
  resources/css/filament/admin/theme.css
  resources/views/filament/forms/components/slider.blade.php
Labels: Change Type | Content or Styling Update

#1182 [ADVAPP-1068]: Adjust the opacity of the checkboxes on the role view page when using light mode
  app-modules/authorization/composer.json
  composer.lock
Labels: Change Type | Content or Styling Update

#1189 [ADVAPP-1060]: Introduce a redesigned holistic view / profile page for the Recruitment CRM
  app-modules/interaction/resources/views/components/interaction-timeline-item.blade.php
  app-modules/prospect/resources/views/filament/resources/prospect-resource/view-prospect.blade.php
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/Concerns/HasProspectHeader.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectApplicationSubmissions.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectEngagement.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectEvents.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectFormSubmissions.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectInteractions.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ProspectCaseManagement.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ProspectEngagementTimeline.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspectActivityFeed.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Schemas/ProspectProfileInfolist.php
  app-modules/prospect/src/Models/Prospect.php
  app-modules/prospect/tests/Prospect/ViewProspectTest.php
Labels: Change Type | Content or Styling Update

#1195 [ADVAPP-1073]: Compile bugs thrown by out of date Node and NPM
  .nvmrc
  Dockerfile
Labels: Change Type | Bug Fix, Change Type | Dependencies

#1201 [ADVAPP-1063]: Refactor non-normalized permissions left in the system
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/CreatePrompt.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/EditPrompt.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/ListPrompts.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/ViewPrompt.php
  app-modules/ai/src/Policies/AiAssistantPolicy.php
  app-modules/ai/src/Policies/PromptPolicy.php
  app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php
  app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/CreateAiAssistantTest.php
  app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/EditAiAssistantTest.php
  app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/ListAiAssistantsTest.php
  app-modules/ai/tests/Feature/Policies/AiAssistantPolicyTest.php
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
  app-modules/audit/src/Filament/Pages/ManageAuditSettings.php
  app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php
  app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
  app-modules/authorization/src/Filament/Pages/ManageGoogleSsoSettings.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ViewUserTest.php
  app-modules/campaign/src/Filament/Pages/ManageCampaignSettings.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/in-app-communication/src/Filament/Pages/UserChat.php
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php
  app-modules/integration-google-recaptcha/src/Filament/Pages/ManageGoogleRecaptchaSettings.php
  app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php
  app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
  app-modules/meeting-center/src/Filament/Pages/ManageAzureCalendarSettings.php
  app-modules/meeting-center/src/Filament/Pages/ManageGoogleCalendarSettings.php
  app-modules/multifactor-authentication/src/Filament/Pages/ManageMultifactorSettings.php
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/prospect/resources/views/filament/resources/prospect-resource/view-prospect.blade.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/Concerns/HasProspectHeader.php
  app-modules/prospect/tests/Prospect/ViewProspectTest.php
  app-modules/student-data-model/resources/views/filament/resources/student-resource/view-student.blade.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentInformationSystemSettings.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableActivityFeedWidget.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/Concerns/HasStudentHeader.php
  app-modules/student-data-model/tests/Student/ViewStudentTest.php
  app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php
  app-modules/timeline/src/Filament/Pages/TimelinePage.php
  app-modules/webhook/src/Policies/InboundWebhookPolicy.php
  app/Filament/Pages/AmazonS3.php
  app/Filament/Pages/ManageLicenseSettings.php
  app/Filament/Pages/ProductHealth.php
  app/Models/User.php
  database/migrations/2024_12_19_174326_seed_refactor_non_normalized_permissions.php
  database/migrations/Concerns/CanModifyPermissions.php
  routes/web.php
Labels: Change Type | Bug Fix

#1202 [ADVAPP-1063]: Fix role access for permissions that split
  database/migrations/2024_12_19_201828_seed_permissions_give_proper_split_permissions_to_roles.php
Labels: Change Type | Bug Fix

#1203 [ADVAPP-1063]: Fix broken migration
  database/migrations/2024_12_19_201828_seed_permissions_give_proper_split_permissions_to_roles.php
Labels: Change Type | Bug Fix

#1204 [Hotfix]: 1.42.2
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/CreatePrompt.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/EditPrompt.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/ListPrompts.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/ViewPrompt.php
  app-modules/ai/src/Policies/AiAssistantPolicy.php
  app-modules/ai/src/Policies/PromptPolicy.php
  app-modules/ai/tests/Feature/Filament/Pages/AIAssistantPageTest.php
  app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/CreateAiAssistantTest.php
  app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/EditAiAssistantTest.php
  app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/ListAiAssistantsTest.php
  app-modules/ai/tests/Feature/Policies/AiAssistantPolicyTest.php
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
  app-modules/audit/src/Filament/Pages/ManageAuditSettings.php
  app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php
  app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
  app-modules/authorization/src/Filament/Pages/ManageGoogleSsoSettings.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ViewUserTest.php
  app-modules/campaign/src/Filament/Pages/ManageCampaignSettings.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/in-app-communication/src/Filament/Pages/UserChat.php
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php
  app-modules/integration-google-recaptcha/src/Filament/Pages/ManageGoogleRecaptchaSettings.php
  app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php
  app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
  app-modules/meeting-center/src/Filament/Pages/ManageAzureCalendarSettings.php
  app-modules/meeting-center/src/Filament/Pages/ManageGoogleCalendarSettings.php
  app-modules/multifactor-authentication/src/Filament/Pages/ManageMultifactorSettings.php
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/prospect/resources/views/filament/resources/prospect-resource/view-prospect.blade.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/Concerns/HasProspectHeader.php
  app-modules/prospect/tests/Prospect/ViewProspectTest.php
  app-modules/student-data-model/resources/views/filament/resources/student-resource/view-student.blade.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentInformationSystemSettings.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableActivityFeedWidget.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/Concerns/HasStudentHeader.php
  app-modules/student-data-model/tests/Student/ViewStudentTest.php
  app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php
  app-modules/timeline/src/Filament/Pages/TimelinePage.php
  app-modules/webhook/src/Policies/InboundWebhookPolicy.php
  app/Filament/Pages/AmazonS3.php
  app/Filament/Pages/ManageLicenseSettings.php
  app/Filament/Pages/ProductHealth.php
  app/Models/User.php
  database/migrations/2024_12_19_174326_seed_refactor_non_normalized_permissions.php
  database/migrations/2024_12_19_201828_seed_permissions_give_proper_split_permissions_to_roles.php
  database/migrations/Concerns/CanModifyPermissions.php
  routes/web.php
Labels: Change Type | Bug Fix

#1200 [ADVAPP-674]: Eliminate the legacy sessions management artifacts
  database/migrations/2024_12_19_165310_drop_sessions_table.php
Labels: Change Type | Feature Cleanup

#1199 [ADVAPP-1065]: Update RoadRunner Binary to v2024.3.0
  Dockerfile
Labels: Change Type | Dependencies

#1198 [ADVAPP-1072]: Feature Flag Cleanup: SmartPromptsFeature
  app-modules/ai/database/migrations/2024_12_18_135152_data_activate_smart_prompts_feature.php
  app-modules/ai/src/Actions/SendMessage.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManagePromptLibrary.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/CreatePrompt.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/EditPrompt.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/ListPrompts.php
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/ViewPrompt.php
  app-modules/ai/src/Http/Controllers/ShowThreadController.php
  app/Features/SmartPromptsFeature.php
Labels: Change Type | Feature Cleanup

#1205 [ADVAPP-1080]: Add filter in the student list for First Generation using a ternary filter
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
  app-modules/student-data-model/tests/Student/ListStudentsTest.php
Labels: Change Type | New Feature

#1211 [ADVAPP-1097]: Add migration to purge timeline items related to engagements
  app-modules/engagement/database/migrations/2024_12_27_002830_purge_timeline_items_related_to_enagements.php
Labels: Change Type | Bug Fix

#1212 [ADVAPP-1097]: Student and prospect activity logs are generating an error
  app-modules/engagement/database/migrations/2024_12_27_010201_purge_timeline_items_related_to_enagements_correctly.php
Labels: Change Type | Bug Fix

#1213 [ADVAPP-1092]: Data migration cleanup: app-modules/task/database/migrations/2024_12_18_104302_delete_task_individual_update_permissions.php
  app-modules/task/database/migrations/2024_12_18_104302_delete_task_individual_update_permissions.php
Labels: Change Type | Feature Cleanup

#1208 [ADVAPP-1078]: Introduce the ability to filter by Smart prompts in the Prompt Library
  app-modules/ai/src/Filament/Resources/PromptResource/Pages/ListPrompts.php
  app-modules/ai/tests/Feature/Filament/Resources/PromptResource/ListPromptsTest.php
Labels: Change Type | Content or Styling Update

#1214 [ADVAPP-1087]: Replace HS Grad Year in the header for a student with the Student ID
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/Concerns/HasStudentHeader.php
Labels: Change Type | Content or Styling Update

#1215 [ADVAPP-1090]: Users are unable to delete roles
  app-modules/authorization/database/migrations/2024_12_30_142107_data_seed_role_permissions.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/EditRole.php
  app-modules/authorization/src/Policies/RolePolicy.php
Labels: Change Type | Bug Fix
