Repository canyongbs/advisingapp, pull requests merged in 2024-10, with the labels that each got.

#1048 [ADVAPP-913]: When navigating to view a form, or a response for a form, an exception is generated.
  resources/views/vendor/cookie-consent/dialog.blade.php
Labels: Change Type | Bug Fix

#1049 [ADVAPP-915]: After uploading a file for the AI Assistants using Canyon's GPT 4o and GPT 4o Mini models, the AI assistants are unable to retrieve information.
  app-modules/integration-open-ai/src/Jobs/UploadFilesToAssistant.php
Labels: Change Type | Bug Fix

#1050 [ADVAPP-916]: Resolve issues in our Docker Compose setup from Docker Updates
  docker-compose.yml
Labels: Change Type | Bug Fix

#1052 [ADVAPP-910]: Fix path in FeatureFlag stub
  stubs/feature.stub
Labels: Change Type | Bug Fix

#1043 [ADVAPP-896]: Improve processing speed for chat in the Enterprise AI Assistant
  app-modules/ai/src/Models/AiThread.php
Labels: Change Type | Bug Fix

#1054 [ADVAPP-918]: Cleanup FeatureFlag: AddUrlToThemeSettingsFeature
  app-modules/authorization/src/Filament/Pages/Auth/Login.php
  app-modules/theme/database/migrations/2024_09_23_162352_add_feature_flag_for_changelog_url.php
  app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php
  app/Features/AddUrlToThemeSettingsFeature.php
Labels: Change Type | Feature Cleanup

#1056 [ADVAPP-859]: Trying to update the Portal copyright statement throws an error
  app-modules/portal/src/Settings/PortalSettings.php
Labels: Change Type | Bug Fix

#1058 [ADVAPP-925]: Update changelog path for login to point to the Advising App website changelog instead of GitHub
  app-modules/authorization/src/Filament/Pages/Auth/Login.php
Labels: Change Type | Content or Styling Update

#1059 [Bugfix]: Fix issue with prospect status default data migration
  app-modules/prospect/database/migrations/2024_10_08_161832_data_ensure_system_default_prospect_statuses_exist.php
Labels: Change Type | Bug Fix

#1062 [ADVAPP-933]: Improve the display of the login page with additional UI/UX enhancements
  resources/views/vendor/filament-panels/components/layout/login.blade.php
Labels: Change Type | Content or Styling Update

#1061 [ADVAPP-927]: Resolve the security issue tracked under CVE-2024-47823
  app-modules/multifactor-authentication/composer.lock
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#1067 [ADVAPP-936]: When accessing email or texts for a specific record in the demo environment, it generates an error.
  app-modules/campaign/src/Actions/ExecuteCampaignAction.php
Labels: Change Type | Bug Fix

#1069 [ADVAPP-935]: Add the ability to filter the list of Message Center engagement by constituents where you are a member of their care team
  app-modules/engagement/resources/views/components/filters.blade.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
Labels: Change Type | New Feature

#1071 [ADVAPP-929]: Adjust composer.json configuration and optimizations for performance benefits in Production and reduced complexity in development
  .github/actions/composer-dependency-setup/action.yml
  Dockerfile
  _ide_helper_models.php
  app-modules/ai/composer.json
  app-modules/ai/src/Rules/RestrictSuperAdmin.php
  app-modules/application/composer.json
  app-modules/assistant/composer.json
  app-modules/audit/config/audit.php
  app-modules/authorization/config/permission.php
  app-modules/basic-needs/composer.json
  app-modules/campaign/composer.json
  app-modules/care-team/composer.json
  app-modules/consent/composer.json
  app-modules/division/composer.json
  app-modules/engagement/tests/EngagementFile/EngagementFilePruningTest.php
  app-modules/form/composer.json
  app-modules/in-app-communication/composer.json
  app-modules/integration-aws-ses-event-handling/composer.json
  app-modules/integration-google-analytics/composer.json
  app-modules/integration-google-recaptcha/composer.json
  app-modules/integration-microsoft-clarity/composer.json
  app-modules/interaction/composer.json
  app-modules/inventory-management/composer.json
  app-modules/meeting-center/composer.json
  app-modules/multifactor-authentication/composer.json
  app-modules/notification/tests/Features/NotificationSendingTest.php
  app-modules/portal/composer.json
  app-modules/report/composer.json
  app-modules/segment/composer.json
  app-modules/survey/composer.json
  app-modules/team/composer.json
  app-modules/timeline/composer.json
  app/Rules/EmailNotInUseOrSoftDeleted.php
  app/View/Components/DatePicker.php
  app/View/Components/Dropzone.php
  app/View/Components/SelectList.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/app.php
  config/auth.php
  config/data.php
  config/filament-tiptap-editor.php
  config/lara-asp-graphql.php
  config/lighthouse.php
  config/media-library.php
  config/sanctum.php
  config/settings.php
  php-cs-fixer.php
  stubs/app-modules/composer-stub.json
  tests/Feature/Multitenancy/Http/Middleware/NeedsTenantTest.php
  tests/Pest.php
  tests/Unit/LicenseSettingsSmsQuotaTracking.php
Labels: Change Type | Dependencies, Change Type | Content or Styling Update, Change Type | DevOps

#1073 [ADVAPP-937]: Enhance the partner branding capabilities by introducing a new support menu item in the profile drop down menu
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | New Feature

#1081 [Bugfix] Interaction view fix
  app-modules/interaction/src/Models/Interaction.php
  app-modules/student-data-model/phpunit.xml
  app-modules/student-data-model/tests/Pest.php
Labels: Change Type | Bug Fix

#1082 [Hotfix] 1.32.1
  app-modules/interaction/src/Models/Interaction.php
  app-modules/student-data-model/phpunit.xml
  app-modules/student-data-model/tests/Pest.php
Labels: Change Type | Bug Fix

#1077 [ADVAPP-950]: Login page fails to preserve the padding in the top header when responding to screen size changes
  resources/views/vendor/filament-panels/components/layout/login.blade.php
Labels: Change Type | Bug Fix

#1078 [ADVAPP-942]: Update the Advising App favicon
  app/Providers/Filament/AdminPanelProvider.php
  public/images/default-favicon-211024.png
  public/images/default-favicon.png
Labels: Change Type | Content or Styling Update

#1079 [ADVAPP-947]: Update the copyright text for the footer in Advising App
  resources/views/components/footer.blade.php
Labels: Change Type | Content or Styling Update

#1080 [ADVAPP-943]: Update the Canyon GBS logo for Advising App
  resources/images/canyon-logo-dark.png
  resources/images/canyon-logo-dark.svg
  resources/images/canyon-logo-light.png
  resources/images/canyon-logo-light.svg
  resources/views/components/footer.blade.php
Labels: Change Type | Content or Styling Update

#1074 [ADVAPP-938]: When the Recent Updates link is activated for partner branding, introduce a new updates menu item in the avatar drop down
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | New Feature

#1072 [ADVAPP-934]: Introduce the ability to set a prospective student conversion value for ROI analysis
  app-modules/prospect/database/migrations/2024_10_08_174318_seed_permissions_for_prospect_conversion.php
  app-modules/prospect/database/migrations/2024_10_15_082847_prospect_conversion_settings.php
  app-modules/prospect/src/Filament/Pages/ManageProspectConversionSettings.php
  app-modules/prospect/tests/Unit/ProspectConversionTest.php
  app/DataTransferObjects/Casts/MoneySettingCast.php
  app/Features/ProspectConversion.php
  app/Filament/Forms/Components/Heading.php
  app/Filament/Forms/Components/Paragraph.php
  app/Settings/ProspectConversionSettings.php
  composer.json
  composer.lock
  config/money.php
  database/migrations/2024_10_16_082036_data_activate_feature_flag_prospect_conversion.php
  resources/views/filament/forms/components/heading-one.blade.php
  resources/views/filament/forms/components/heading-three.blade.php
  resources/views/filament/forms/components/heading-two.blade.php
  resources/views/filament/forms/components/paragraph.blade.php
Labels: Change Type | New Feature, Feature Flag Added

#1083 [ADVAPP-956]: Fix bug with dependency auto loading
  .github/actions/composer-dependency-setup/action.yml
  Dockerfile
Labels: Change Type | Bug Fix

#1085 [ADVAPP-953]: Feature Flag Cleanup: ManageStudentConfigurationFeature
  app-modules/student-data-model/src/Filament/Resources/ManageEnrollmentResource.php
  app-modules/student-data-model/src/Filament/Resources/ManageProgramResource.php
  app-modules/student-data-model/src/Filament/Resources/ManageStudentResource.php
  app/Features/ManageStudentConfigurationFeature.php
  database/migrations/2024_10_10_111459_add_feature_flag_for_manage_students_configuration.php
Labels: Change Type | Feature Cleanup

#1086 [ADVAPP-954]: Feature Flag Cleanup: ProspectConversion
  app-modules/prospect/src/Filament/Pages/ManageProspectConversionSettings.php
  app/Features/ProspectConversion.php
  database/migrations/2024_10_16_082036_data_activate_feature_flag_prospect_conversion.php
Labels: Change Type | Feature Cleanup

#1089 [ADVAPP-959]: Update the Advising App logo used in the header
  package-lock.json
  resources/images/default-logo-dark-251024.svg
  resources/images/default-logo-dark.svg
  resources/images/default-logo-light-251024.svg
  resources/images/default-logo-light.svg
  resources/views/vendor/filament-panels/components/logo.blade.php
  resources/views/vendor/mail/html/header.blade.php
Labels: Change Type | Content or Styling Update

#1088 [ADVAPP-952]: When the disable branding bar option is enabled in profile settings text appears next to the switch that should not be displayed
  app/Filament/Pages/EditProfile.php
Labels: Change Type | Bug Fix

#1087 [ADVAPP-958]: Update the favicon that is used throughout the application
  app/Providers/Filament/AdminPanelProvider.php
  public/images/default-favicon-211024.png
  public/images/default-favicon-251024.png
Labels: Change Type | Content or Styling Update

#1090 [ADVAPP-961]: Add draft with AI capabilities to message center email and text message scenarios
  app-modules/engagement/src/Filament/Actions/MessageCenterDraftWithAiAction.php
  app-modules/engagement/src/Filament/Actions/SendEngagementAction.php
Labels: Change Type | New Feature

#1084 [ADVAPP-963]: Introduce population segment rule for first generation status
  app-modules/student-data-model/src/Filament/Tables/StudentsTable.php
Labels: Change Type | New Feature

#1092 [ADVAPP-964]: Add enabled and complete as options to display in the list view of campaigns
  app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/ListCampaigns.php
Labels: Change Type | New Feature

#1095 [ADVAPP-971]: View Student page Files, Care Team, and Subscriptions manager issues
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentCareTeamRelationManager.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentFilesRelationManager.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/StudentSubscriptionsRelationManager.php
Labels: Change Type | Bug Fix, Change Type | Content or Styling Update
