Repository canyongbs/advisingapp, pull requests merged in 2024-06, with the labels that each got.

#768 Features/advapp 596 Restrict super admins from being placed in "Teams"
  app-modules/team/src/Filament/Resources/TeamResource/RelationManagers/UsersRelationManager.php
  app-modules/team/tests/Team/EditTeamTest.php
Labels: Change Type | New Feature

#778 [ADVAPP-614]:Enhance the description of artificial intelligence settings and configurability
  app-modules/ai/src/Filament/Pages/ManageAiSettings.php
Labels: Change Type | Content or Styling Update

#781 [ADVAPP-623]:Update Label for Product Administration > Prospect Management to Constituent Management
  app-modules/prospect/src/Filament/Resources/ProspectSourceResource.php
  app-modules/prospect/src/Filament/Resources/ProspectStatusResource.php
  app/Filament/Clusters/ConstituentManagement.php
Labels: Change Type | New Feature

#783 [ADVAPP-624]: Create an internal grouping for Prospect Management under Constituent Management
  app-modules/prospect/src/Filament/Resources/ProspectSourceResource.php
  app-modules/prospect/src/Filament/Resources/ProspectStatusResource.php
Labels: Change Type | Content or Styling Update

#788 [ADVAPP-636]: Clicking on a prospect from global search takes you to edit route
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
Labels: Change Type | Bug Fix

#782 [ADVAPP-622]: Update label for Report Center to Custom Reports
  app-modules/report/src/Filament/Resources/ReportResource.php
  app-modules/report/src/Filament/Resources/ReportResource/Pages/CreateReport.php
  app-modules/report/src/Filament/Resources/ReportResource/Pages/ListReports.php
Labels: Change Type | Content or Styling Update

#793 [ADVAPP-579]: Form validation issue for certain input types
  app-modules/form/src/Actions/GenerateSubmissibleValidator.php
  app-modules/form/src/Actions/ProcessSubmissionField.php
  app-modules/form/src/Http/Controllers/FormWidgetController.php
Labels: Change Type | Bug Fix

#784 [ADVAPP-621]: Introduce Report Library coming soon page under Reporting
  app-modules/report/database/migrations/2024_06_05_110340_seed_permissions_add_report_library.php
  app-modules/report/src/Filament/Pages/ReportLibrary.php
Labels: Change Type | New Feature

#795 [ADVAPP-645]: Change label for Edit Profile page to Profile Settings
  app/Filament/Pages/EditProfile.php
Labels: Change Type | New Feature

#799 [Bugfix]: Increase the timeout of the build command and display output
  app/Console/Commands/BuildAssets.php
Labels: Change Type | Bug Fix

#801 [ADVAPP-646]: Enhance the dropdown menu for profile information with an explicit Profile Settings link
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Content or Styling Update

#805 [ADVAPP-648]: Populate Tenant ID and User ID into Sentry reports
  app/Listeners/ClearSentryUser.php
  app/Listeners/SetSentryUser.php
  app/Multitenancy/Listeners/RemoveSentryTenantTag.php
  app/Multitenancy/Listeners/SetSentryTenantTag.php
  app/Providers/AppServiceProvider.php
  app/Providers/EventServiceProvider.php
  config/octane.php
Labels: Change Type | New Feature

#798 [ADVAPP-649]: Resolve message center/timeline issues, [ADVAPP-634]: Timeline Cannot access offset of type string on string error
  app-modules/engagement/database/migrations/2024_06_07_234752_data_fix_engagement_bodies.php
  app-modules/engagement/src/Actions/GenerateEmailMarkdownContent.php
  app-modules/engagement/src/Filament/Actions/CreateOnDemandEngagement.php
  app-modules/engagement/src/Filament/Actions/EngagementCreateAction.php
  app-modules/engagement/src/Filament/Actions/SendEngagementAction.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/form/src/Models/FormEmailAutoReply.php
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#809 [ADVAPP-640]: Update language used in Retention CRM dashboard cards to describe subscriptions, alerts, and caseloads
  app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
Labels: Change Type | Content or Styling Update

#808 [ADVAPP-617]: When using the AI Personal Assistant, the carriage return automatically sends message
  app-modules/ai/resources/views/components/assistant.blade.php
Labels: Change Type | Bug Fix

#794 [ADVAPP-307]: Restrict the display of available public profile features depending on whether the user has access to a CRM product
  app/Filament/Pages/EditProfile.php
Labels: Change Type | New Feature

#810 [ADVAPP - 637] - Message center not respecting user timezone
  app-modules/engagement/resources/views/components/message-center-inbox.blade.php
Labels: Change Type | New Feature

#792 [ADVAPP-651]: Investigate if updating to recent TipTap Editor package fixes Modal Depth issue
  composer.json
  composer.lock
  resources/views/vendor/filament-panels/resources/relation-manager.blade.php
Labels: Change Type | Bug Fix

#814 [BUGFIX]: Change the default amount of queue workers to 1 in local development
  docker-compose.dev.yml
Labels: Change Type | Bug Fix, Change Type | DevOps

#815 [ADVAPP-641]: Update state management to allow tasks to go from Cancelled back to In Progress
  app-modules/task/src/Enums/TaskStatus.php
  app-modules/task/tests/ListTasksTest.php
Labels: Change Type | New Feature

#791 [ADVAPP-590] Enhance the display of saved chats with last engaged hover details
  app-modules/ai/resources/js/chat.js
  app-modules/ai/resources/views/components/assistant.blade.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageFolders.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php
  app-modules/ai/src/Models/AiThread.php
Labels: Change Type | New Feature

#818 [ADVAPP-655]: Link Students and Prospects in Message Center to holistic record view
  app-modules/engagement/resources/views/components/message-center-content.blade.php
Labels: Change Type | New Feature

#820 [Hotfix]: filament builders
  composer.lock
Labels: Change Type | Bug Fix

#821 [Hotfix]: 1.14.1
  composer.lock
Labels: Change Type | Bug Fix

#823 [ADVAPP-654]: CLONE - Reintroduce streamed responses for AI Assistant
  app-modules/ai/resources/js/chat.js
  app-modules/ai/src/Actions/RetryMessage.php
  app-modules/ai/src/Actions/SendMessage.php
  app-modules/ai/src/Http/Controllers/RetryMessageController.php
  app-modules/ai/src/Http/Controllers/SendMessageController.php
  app-modules/ai/src/Services/Contracts/AiService.php
  app-modules/ai/src/Services/TestAiService.php
  app-modules/ai/tests/Feature/Actions/RetryMessageTest.php
  app-modules/ai/tests/Feature/Actions/SendMessageTest.php
  app-modules/ai/tests/Feature/Http/Controllers/RetryMessageControllerTest.php
  app-modules/ai/tests/Feature/Http/Controllers/SendMessageControllerTest.php
  app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
  app-modules/integration-open-ai/tests/Feature/Services/OpenAiGptTestServiceTest.php
  composer.json
  composer.lock
  overrides/Laravel/Octane/RoadRunner/RoadRunnerClient.php
  overrides/OpenAI/Responses/Threads/Runs/ThreadRunResponse.php
  package-lock.json
  package.json
Labels: Change Type | New Feature

#825 [Hotfix]: Version assistant assets
  app-modules/ai/resources/views/components/assistant.blade.php
  app/Providers/AppServiceProvider.php
Labels: Change Type | Bug Fix, Change Type | New Feature

#829 [ADVAPP-659]: Retention/Recruitment CRM emails fail to properly deliver embedded images
  app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
  app-modules/engagement/src/Actions/GenerateEngagementBodyContent.php
  app-modules/engagement/src/Filament/Concerns/EngagementInfolist.php
  app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/ViewEngagement.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/engagement/src/Notifications/EngagementEmailNotification.php
  app-modules/engagement/src/Notifications/EngagementSmsNotification.php
  app-modules/form/src/Models/FormEmailAutoReply.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementsRelationManager.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
Labels: Change Type | Bug Fix

#833 [ADVAPP-664]: Introduce the ability to receive the product health check data at the tenant level available via API call
  app/Http/Middleware/CheckOlympusKey.php
  routes/api.php
Labels: Change Type | New Feature

#835 [ADVAPP-663]: Enhance the order of Reporting navigation in the application
  app-modules/report/src/Filament/Pages/ReportAssistant.php
  app-modules/report/src/Filament/Pages/ReportLibrary.php
  app-modules/report/src/Filament/Resources/ReportResource.php
  app/Filament/Clusters/UsageAuditing.php
  app/Filament/Pages/ProductHealth.php
Labels: Change Type | Content or Styling Update

#832 [ADVAPP-661]: Update all email templates to address image ALT Tag issue and remove signature
  app-modules/engagement/src/Notifications/EngagementEmailNotification.php
  app-modules/form/src/Notifications/FormSubmissionRequestNotification.php
  app-modules/integration-aws-ses-event-handling/tests/Unit/SesConfigurationSetTest.php
  app-modules/notification/tests/Features/NotificationSendingTest.php
  app-modules/notification/tests/Features/TestEmailSettingFromNameNotification.php
  app-modules/service-management/src/Notifications/SendEducatableServiceRequestClosedNotification.php
  app/Multitenancy/Tasks/SwitchAppName.php
  config/multitenancy.php
  resources/views/vendor/notifications/email.blade.php
  tests/Feature/Multitenancy/Tasks/SwitchAppNameTest.php
  tests/Unit/TestEmailNotification.php
Labels: Change Type | Bug Fix

#836 [OLYMPUS-41]: Set the filesystem root configs during Tenant create
  app/Console/Commands/CreateTenant.php
  app/Http/Controllers/Tenants/CreateTenantController.php
  app/Http/Requests/Tenants/CreateTenantRequest.php
Labels: Change Type | New Feature

#839 [ADVAPP-665]: enhance failure engagements notifications
  app-modules/engagement/src/Notifications/EngagementFailedNotification.php
Labels: Change Type | Bug Fix

#843 [ADVAPP-676]: Prevent Engagements from putting jobs onto the email queue if it's on the queue but hasn't been processed
  app-modules/engagement/src/Actions/EngagementEmailChannelDelivery.php
  app-modules/engagement/src/Actions/EngagementSmsChannelDelivery.php
Labels: Change Type | Bug Fix

#841 [ADVAPP-629]: Global search produces different results based on capitalization
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource.php
  app/Filament/Resources/Concerns/HasGlobalSearchResultScoring.php
Labels: Change Type | New Feature

#844 [ADVAPP-588]: Introduce administrator recovery and support for MFA issues for local accounts
  app-modules/authorization/tests/Feature/Filament/Resources/User/ViewUserTest.php
  app-modules/multifactor-authentication/src/Traits/MultifactorAuthenticatable.php
  app/Filament/Resources/UserResource/Pages/ViewUser.php
  app/Policies/UserPolicy.php
  database/factories/UserFactory.php
Labels: Change Type | New Feature

#848 [ADVAPP-672]: Add local MFA recovery code usage
  app-modules/authorization/resources/views/login.blade.php
  app-modules/authorization/src/Filament/Pages/Auth/Login.php
Labels: Change Type | New Feature

#846 [ADVAPP-681]: Improve error message text for issues experienced by customers
  resources/svg/canyongbs-500.svg
  resources/svg/flowbite-500.svg
  resources/views/errors/500.blade.php
Labels: Change Type | Content or Styling Update

#851 [ADVAPP-685]: Improve language used to send an email or text from within the Message Center
  app-modules/engagement/resources/views/components/message-center-content.blade.php
Labels: Change Type | Content or Styling Update

#837 [ADVAPP-658]: Introduce ability to duplicate knowledge base articles
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseArticleResource/Pages/ListKnowledgeBaseArticles.php
  app/Support/MediaEncoding/TiptapMediaEncoder.php
Labels: Change Type | New Feature

#852 [ADVAPP-678]: Reduce local queues and workers to only run a single instance
  .env.example
  Dockerfile
  docker-compose.dev.yml
  docker/generate-queues.sh
Labels: Change Type | New Feature

#853 [ADVAPP-684]: Message center engagement fails to cancel properly
  app-modules/engagement/resources/views/components/message-center-content.blade.php
  app-modules/engagement/src/Filament/Actions/SendEngagementAction.php
Labels: Change Type | Bug Fix

#854 [ADVAPP-644]: Resolve SQS large payload errors
  composer.json
  composer.lock
  config/queue.php
Labels: Change Type | Bug Fix, Change Type | New Feature

#838 [ADVAPP-229]: Introduce Student Basic Needs Support program catalog
  app-modules/basic-needs/composer.json
  app-modules/basic-needs/config/roles/api/.gitkeep
  app-modules/basic-needs/config/roles/web/.gitkeep
  app-modules/basic-needs/database/factories/BasicNeedsCategoryFactory.php
  app-modules/basic-needs/database/factories/BasicNeedsProgramFactory.php
  app-modules/basic-needs/database/migrations/2024_06_18_120111_seed_permissions_for_basic_needs_category.php
  app-modules/basic-needs/database/migrations/2024_06_18_120143_seed_permissions_for_basic_needs_program.php
  app-modules/basic-needs/database/migrations/2024_06_19_121851_create_basic_needs_categories_table.php
  app-modules/basic-needs/database/migrations/2024_06_19_121853_create_basic_needs_programs_table.php
  app-modules/basic-needs/database/migrations/2024_06_20_172225_data_activate_basic_needs.php
  app-modules/basic-needs/database/seeders/BasicNeedsCategorySeeder.php
  app-modules/basic-needs/database/seeders/BasicNeedsProgramSeeder.php
  app-modules/basic-needs/src/BasicNeedsPlugin.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsCategoryResource.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsCategoryResource/Pages/CreateBasicNeedsCategory.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsCategoryResource/Pages/EditBasicNeedsCategory.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsCategoryResource/Pages/ListBasicNeedsCategories.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsCategoryResource/Pages/ViewBasicNeedsCategory.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource/Pages/CreateBasicNeedsProgram.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource/Pages/EditBasicNeedsProgram.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource/Pages/ListBasicNeedsPrograms.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource/Pages/ViewBasicNeedsProgram.php
  app-modules/basic-needs/src/Models/BasicNeedsCategory.php
  app-modules/basic-needs/src/Models/BasicNeedsProgram.php
  app-modules/basic-needs/src/Observers/BasicNeedsCategoryObserver.php
  app-modules/basic-needs/src/Policies/BasicNeedsCategoryPolicy.php
  app-modules/basic-needs/src/Policies/BasicNeedsProgramPolicy.php
  app-modules/basic-needs/src/Providers/BasicNeedsServiceProvider.php
  app-modules/basic-needs/src/Registries/BasicNeedsRbacRegistry.php
  app-modules/basic-needs/tests/BasicNeedsCategory/BasicNeedsCategoryTest.php
  app-modules/basic-needs/tests/BasicNeedsProgram/BasicNeedsProgramTest.php
  app/Exceptions/SoftDeleteContraintViolationException.php
  composer.json
  composer.lock
Labels: Change Type | New Feature

#855 [Bugfix]: Wrap adding file_upload in a try catch
  database/migrations/2024_06_10_164958_data_update_existing_assistants_to_use_file_search_tool.php
Labels: Change Type | Bug Fix

#856 [Bugfix] Force using file_search if files are attached to AI chat
  app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
Labels: Change Type | Bug Fix

#858 [ADVAPP-698]: Add a multitenancy task to clear out bindings
  app-modules/ai/src/Enums/AiModel.php
  app/Multitenancy/Tasks/ClearBindingsTask.php
  config/multitenancy.php
Labels: Change Type | Bug Fix

#861 [ADVAPP-698]: Apply the file_search tool if any message has files
  app-modules/integration-open-ai/src/Services/BaseOpenAiService.php
Labels: Change Type | Bug Fix

#862 [ADVAPP-572]: The health check page is throwing 500s randomly when viewed in Dev and Prod, [ADVAPP-631]: Clicking refresh generates an error from within product health
  resources/views/vendor/filament-spatie-health/pages/health-check-results.blade.php
Labels: Change Type | Bug Fix

#864 [ADVAPP-492]: Update all docs to instruct users to update to the most recent version of Docker
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.yml
  docs/local-setup.md
Labels: Change Type | Documentation, Change Type | DevOps

#866 [ADVAPP-693]: Delete ai_assistants default name data migration
  app-modules/ai/database/migrations/2024_06_24_211022_data_change_default_name_description_for_default_personal_assistant.php
Labels: Change Type | Content or Styling Update
