Repository canyongbs/advisingapp, pull requests merged in 2024-07, with the labels that each got.

#869 [ADVAPP-675]: Update PR template to ask whether or not a Feature Flag was added in the PR
  .github/pull_request_template.md
Labels: Change Type | Documentation

#868 [ADVAPP-573]: Fix unique constraint with deleted Users
  app-modules/authorization/tests/Feature/Filament/Resources/User/RestoreUserTest.php
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: Change Type | Bug Fix

#875 [ADVAPP-716]: Attempting to create a new AI Assistant results in an exception
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
  app-modules/ai/src/Models/AiAssistant.php
Labels: Change Type | Bug Fix

#876 Hotfix/1.17.1
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
  app-modules/ai/src/Models/AiAssistant.php
Labels: Change Type | Bug Fix

#872 [ADVAPP-690]: Restrict the ability to modify the settings for the Institutional Assistant to the appropriate administrative sections Advising App
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Pages/EditAiAssistant.php
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Pages/ListAiAssistants.php
  app-modules/ai/tests/Feature/Filament/Pages/ManageAiSettingsPageTest.php
Labels: Change Type | New Feature

#878 [ADVAPP-715]: The order of the primary navigation for the reporting group has regressed to a prior state
  app/Filament/Clusters/ReportLibrary.php
Labels: Change Type | Bug Fix

#877 [ADVAPP-687]: Expand the types of files that can be updated using the AI Personal Assistant.
  app-modules/ai/config/ai.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanUploadFiles.php
  config/livewire.php
Labels: Change Type | New Feature

#879 [ADVAPP-606]: Fix Coder file permission issues
  .gitignore
  Dockerfile
  bootstrap/cache/.gitignore
  composer.json
  copyright.rb
  docker-compose.dev.yml
  docker/s6-overlay/s6-rc.d/build-assets/dependencies
  docker/s6-overlay/s6-rc.d/fix-permissions/dependencies
  docker/s6-overlay/s6-rc.d/fix-permissions/type
  docker/s6-overlay/s6-rc.d/fix-permissions/up
  docker/s6-overlay/s6-rc.d/generate-api-docs/dependencies
  docker/s6-overlay/s6-rc.d/initial-migration/dependencies
  docker/s6-overlay/s6-rc.d/laravel-migrate/dependencies
  docker/s6-overlay/s6-rc.d/laravel-octane/dependencies
  docker/s6-overlay/s6-rc.d/laravel-scheduler/dependencies
  docker/s6-overlay/s6-rc.d/nginx/dependencies
  docker/s6-overlay/s6-rc.d/startup-caching/dependencies
  docker/s6-overlay/scripts/fix-permissions
  docker/s6-overlay/user/fix-permissions
  docker/set-id
  docs/local-setup.md
  php-cs-fixer.php
  storage/app/.gitignore
  storage/debugbar/.gitignore
  storage/framework/.gitignore
  storage/framework/cache/.gitignore
  storage/framework/cache/data/.gitignore
  storage/framework/sessions/.gitignore
  storage/framework/testing/.gitignore
  storage/framework/views/.gitignore
  storage/logs/.gitignore
  stubs/migration.create.stub
  stubs/migration.stub
  stubs/migration.update.stub
  stubs/permission-migration.stub
Labels: Change Type | DevOps

#881 [ADVAPP-733]: Engagement, Campaign, and CalendarSync jobs are not being dispatched by the scheduler
  app-modules/campaign/src/Actions/ExecuteCampaignAction.php
  app-modules/campaign/src/Actions/ExecuteCampaignActions.php
  app-modules/campaign/src/Providers/CampaignServiceProvider.php
  app-modules/engagement/src/Actions/QueuedEngagementDelivery.php
  app-modules/engagement/src/Providers/EngagementServiceProvider.php
  app-modules/meeting-center/src/Jobs/SyncCalendar.php
  app-modules/meeting-center/src/Jobs/SyncCalendars.php
  app-modules/meeting-center/src/Providers/MeetingCenterServiceProvider.php
  app/Settings/DisplaySettings.php
Labels: Change Type | Bug Fix

#887 [ADVAPP-711]: (Cleanup) ai_utilization Feature Flag
  app-modules/ai/database/migrations/2024_07_09_195234_data_purge_ai_utilization_feature_flage.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php
  app-modules/ai/src/Jobs/CloneAiThread.php
  app-modules/ai/src/Notifications/SendAssistantTranscriptNotification.php
  app-modules/report/src/Filament/Pages/ArtificialIntelligence.php
Labels: Change Type | Feature Cleanup

#885 [ADVAPP-730]: Modify the cacheTag property for reports to be locked
  app-modules/report/src/Filament/Widgets/ChartReportWidget.php
  app-modules/report/src/Filament/Widgets/StatsOverviewReportWidget.php
Labels: Change Type | New Feature

#890 [ADVAPP-719]: Third level navigation groups are not displaying appropriate arrow indicator when in an opened state
  composer.lock
Labels: Change Type | Bug Fix

#888 [ADVAPP-722]: Introduce a user list bulk action to assign roles to users
  app/Filament/Resources/UserResource/Actions/AssignRolesBulkAction.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: Change Type | New Feature

#886 [ADVAPP-726]: Enhance modal warning language when canceling bulk engagement for students or prospects
  app-modules/engagement/src/Filament/Actions/Concerns/ImplementsHasBulkEngagementAction.php
Labels: Change Type | Content or Styling Update

#891 [ADVAPP-707]: Create report for the report library Student Engagement
  app-modules/student-data-model/src/Filament/Pages/StudentEngagementReport.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource.php
  app-modules/student-data-model/src/Filament/Widgets/MostEngagedStudentsTable.php
  app-modules/student-data-model/src/Filament/Widgets/StudentEngagementLineChart.php
  app-modules/student-data-model/src/Filament/Widgets/StudentEngagementStats.php
Labels: Change Type | New Feature

#892 [ADVAPP-705]: Create report for the report library for Students
  app-modules/report/src/Filament/Pages/Students.php
  app-modules/report/src/Filament/Widgets/MostRecentStudentsTable.php
  app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php
  app-modules/report/src/Filament/Widgets/StudentsStats.php
  app-modules/student-data-model/database/factories/StudentFactory.php
  app-modules/student-data-model/database/migrations/2024_07_08_182424_add_new_timestamps_columns_in_students_table.php
  app-modules/student-data-model/database/migrations/2024_07_08_182958_data_update_timestamps_columns_data_in_student_table.php
  app-modules/student-data-model/database/migrations/2024_07_08_184533_data_activate_student_timestamp_fields.php
  app-modules/student-data-model/src/Models/Student.php
Labels: Change Type | New Feature, Feature Flag Added

#889 [ADVAPP-708] Create report for the report library for Prospect Engagement
  .gitignore
  app-modules/prospect/src/Filament/Pages/ProspectEnagagementReport.php
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
  app-modules/prospect/src/Filament/Widgets/MostEngagedProspectsTable.php
  app-modules/prospect/src/Filament/Widgets/ProspectEngagementLineChart.php
  app-modules/prospect/src/Filament/Widgets/ProspectEngagementState.php
Labels: Change Type | New Feature

#896 [ADVAPP-741]: Update the model names used throughout artificial intelligence features
  app-modules/ai/src/Enums/AiModel.php
Labels: Change Type | Content or Styling Update

#893 [ADVAPP-720]: Enhance the display of employee information for user administrators by displaying the team they are on.
  app/Filament/Resources/UserResource/Pages/ListUsers.php
  app/Models/User.php
Labels: Change Type | New Feature

#894 [ADVAPP-721]: Introduce the ability to filter the user list by team
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: Change Type | New Feature

#898 [ADVAPP-713]: Add a media conversion to AI Assistant avatar images
  app-modules/ai/resources/views/components/assistant.blade.php
  app-modules/ai/src/Models/AiAssistant.php
Labels: Change Type | Content or Styling Update

#900 [ADVAPP-724] Enhance the retention and recruitment dashboards by including related to fields for employee tasks
  app-modules/task/src/Filament/Widgets/TasksWidget.php
Labels: Change Type | Content or Styling Update

#902 [ADVAPP-732] Enhance API Docs to contain helpful support information
  spectaql.yml
Labels: Change Type | Content or Styling Update

#904 [ADVAPP-744]: (Cleanup) delete app-modules/student-data-model/database/migrations/2024_07_08_182958_data_update_timestamps_columns_data_in_student_table.php
  app-modules/student-data-model/database/migrations/2024_07_08_182958_data_update_timestamps_columns_data_in_student_table.php
Labels: Change Type | Feature Cleanup

#905 [ADVAPP-742]: Enhance the avatar display in the AI Assistant listing
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Pages/ListAiAssistants.php
Labels: Change Type | Content or Styling Update

#880 [ADVAPP-718]: Inaccurate validation error presents when creating a new user with existing email address
  app-modules/authorization/tests/Feature/Filament/Resources/User/RestoreUserTest.php
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Rules/EmailNotInUseOrSoftDeleted.php
Labels: Change Type | Bug Fix

#901 [ADVAPP-743] (Cleanup) student_timestamp_fields feature flag
  app-modules/report/src/Filament/Widgets/MostRecentStudentsTable.php
  app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php
  app-modules/student-data-model/database/factories/StudentFactory.php
  app-modules/student-data-model/database/migrations/2024_07_12_195608_data_clean_up_student_timestamp_fields.php
  app-modules/student-data-model/src/Models/Student.php
Labels: Change Type | Feature Cleanup

#908 [ADVAPP-717]: Fix GitHub Action issues found in ticket
  .github/actions/composer-dependency-setup/action.yml
  .github/workflows/ci.yml
  phpunit-ci.xml
Labels: Change Type | DevOps

#895 [ADVAPP-709]: Create report for the report library for Task Management
  app-modules/report/src/Filament/Pages/ProspectEnagagementReport.php
  app-modules/report/src/Filament/Pages/StudentEngagementReport.php
  app-modules/report/src/Filament/Pages/TaskManagement.php
  app-modules/report/src/Filament/Widgets/MostEngagedProspectsTable.php
  app-modules/report/src/Filament/Widgets/MostEngagedStudentsTable.php
  app-modules/report/src/Filament/Widgets/MostRecentTasksTable.php
  app-modules/report/src/Filament/Widgets/ProspectEngagementLineChart.php
  app-modules/report/src/Filament/Widgets/ProspectEngagementState.php
  app-modules/report/src/Filament/Widgets/StudentEngagementLineChart.php
  app-modules/report/src/Filament/Widgets/StudentEngagementStats.php
  app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php
  app-modules/report/src/Filament/Widgets/TaskStats.php
Labels: Change Type | New Feature

#910 [ADVAPP-725]: Enhance the placeholder text for global search
  resources/lang/vendor/filament-panels/en/global-search.php
Labels: Change Type | Content or Styling Update

#912 [ADVAPP-723]: Enable default sort of Permissions Group ascending
  app-modules/authorization/src/Filament/Resources/PermissionResource.php
Labels: Change Type | Bug Fix

#913 [ADVAPP-736], [ADVAPP-737] & [ADVAPP-739]: Introduce the ability to use AI to draft emails in more places
  app-modules/campaign/resources/views/filament/blocks/draft-campaign-engagement-block-with-ai-modal-content.blade.php
  app-modules/campaign/src/Filament/Blocks/Actions/DraftCampaignEngagementBlockWithAi.php
  app-modules/campaign/src/Filament/Blocks/EngagementBatchEmailBlock.php
  app-modules/campaign/src/Filament/Blocks/EngagementBatchSmsBlock.php
  app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php
  app-modules/engagement/resources/views/filament/actions/draft-with-ai-modal-content.blade.php
  app-modules/engagement/resources/views/filament/resources/draft-template-with-ai-modal-content.blade.php
  app-modules/engagement/src/Enums/EngagementDeliveryMethod.php
  app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
  app-modules/engagement/src/Filament/Actions/DraftWithAiAction.php
  app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords.php
  app-modules/engagement/src/Filament/ManageRelatedRecords/ManageRelatedEngagementRecords/Actions/DraftWithAiAction.php
  app-modules/engagement/src/Filament/Resources/Actions/DraftTemplateWithAiAction.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/CreateEmailTemplate.php
  app-modules/engagement/src/Filament/Resources/EmailTemplateResource/Pages/EditEmailTemplate.php
  app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/CreateSmsTemplate.php
  app-modules/engagement/src/Filament/Resources/SmsTemplateResource/Pages/EditSmsTemplate.php
Labels: Change Type | New Feature

#906 [ADVAPP-738]: Introduce the ability to assign teams to users in bulk
  app/Filament/Resources/UserResource/Actions/AssignTeamBulkAction.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
  app/Models/User.php
Labels: Change Type | New Feature

#918 [ADVAPP-757]: Fix bug caused by missing rr file
  docker/s6-overlay/scripts/fix-permissions
Labels: Change Type | Bug Fix, Change Type | DevOps

#914 [ADVAPP-727]: Enhance the contextual information provided in alerts by including who created the alert
  app-modules/alert/database/migrations/2024_07_17_101206_add_user_id_foreign_key_in_alerts_table.php
  app-modules/alert/database/migrations/2024_07_22_095019_created_by_feature_flag.php
  app-modules/alert/src/Models/Alert.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentAlerts.php
Labels: Change Type | New Feature

#919 [ADVAPP-755]: Enhance and standardize the maximum height display for line charts in dashboards
  app-modules/report/src/Filament/Widgets/LineChartReportWidget.php
  app-modules/report/src/Filament/Widgets/PromptsCreatedLineChart.php
  app-modules/report/src/Filament/Widgets/ProspectEngagementLineChart.php
  app-modules/report/src/Filament/Widgets/SavedConversationsLineChart.php
  app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php
  app-modules/report/src/Filament/Widgets/StudentEngagementLineChart.php
  app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php
Labels: Change Type | Content or Styling Update

#916 [ADVAPP-706]: Create report for the report library for Prospects
  app-modules/report/src/Filament/Pages/ProspectReport.php
  app-modules/report/src/Filament/Widgets/ProspectReportLineChart.php
  app-modules/report/src/Filament/Widgets/ProspectReportStats.php
  app-modules/report/src/Filament/Widgets/ProspectReportTableChart.php
Labels: Change Type | New Feature

#917 [ADVAPP-747] Enhance the prompt insertion experience for the Prompt Library feature so that users can filter prompts by their team.
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManagePromptLibrary.php
Labels: Change Type | New Feature

#920 [ADVAPP-756]: Enhance validation on the file type for Custom Assistant to svg, png, gif, jpg, for the avatar feature.
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
  app-modules/ai/src/Models/AiAssistant.php
Labels: Change Type | New Feature

#926 [ADVAPP-766]: Improve the third level navigation in the Report Library
  app-modules/report/src/Filament/Pages/ArtificialIntelligence.php
  app-modules/report/src/Filament/Pages/ProspectEnagagementReport.php
  app-modules/report/src/Filament/Pages/ProspectReport.php
  app-modules/report/src/Filament/Pages/StudentEngagementReport.php
  app-modules/report/src/Filament/Pages/Students.php
  app-modules/report/src/Filament/Pages/TaskManagement.php
  app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php
Labels: Change Type | Content or Styling Update

#928 [ADVAPP-762]: Improve the display of SIS and Other ID columns in the student list
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
Labels: Change Type | Content or Styling Update

#925 [ADVAPP-749]: Update delivery notifications when sending out bulk emails and texts to students and prospects to provide clear status updates
  app-modules/engagement/src/Actions/CreateEngagementBatch.php
  app-modules/engagement/src/Notifications/EngagementBatchFinishedNotification.php
  app-modules/engagement/src/Notifications/EngagementBatchStartedNotification.php
Labels: Change Type | Content or Styling Update

#927 [ADVAPP-759]: Fix Campaign Engagement images
  app-modules/campaign/src/Filament/Blocks/EngagementBatchEmailBlock.php
  app-modules/campaign/src/Filament/Blocks/EngagementBatchSmsBlock.php
  app-modules/campaign/src/Filament/Blocks/InteractionBlock.php
  app-modules/campaign/src/Filament/Blocks/ServiceRequestBlock.php
  app-modules/campaign/src/Filament/Blocks/TaskBlock.php
  app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php
  app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php
  app-modules/filament-tiptap-editor/resources/css/plugin.css
  app-modules/filament-tiptap-editor/resources/dist/filament-tiptap-editor.css
  app-modules/filament-tiptap-editor/resources/dist/filament-tiptap-editor.js
  app-modules/filament-tiptap-editor/resources/js/extensions/LocalFilesExtension.js
  app-modules/filament-tiptap-editor/resources/views/tiptap-editor.blade.php
  app-modules/filament-tiptap-editor/src/TiptapConverter.php
  app-modules/filament-tiptap-editor/src/TiptapEditor.php
  resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php
  resources/views/filament/forms/components/campaigns/step-summary.blade.php
Labels: Change Type | Bug Fix

#929 [Hotfix]: 1.20.1
  app-modules/campaign/src/Filament/Blocks/EngagementBatchEmailBlock.php
  app-modules/campaign/src/Filament/Blocks/EngagementBatchSmsBlock.php
  app-modules/campaign/src/Filament/Blocks/InteractionBlock.php
  app-modules/campaign/src/Filament/Blocks/ServiceRequestBlock.php
  app-modules/campaign/src/Filament/Blocks/TaskBlock.php
  app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php
  app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php
  app-modules/filament-tiptap-editor/resources/css/plugin.css
  app-modules/filament-tiptap-editor/resources/dist/filament-tiptap-editor.css
  app-modules/filament-tiptap-editor/resources/dist/filament-tiptap-editor.js
  app-modules/filament-tiptap-editor/resources/js/extensions/LocalFilesExtension.js
  app-modules/filament-tiptap-editor/resources/views/tiptap-editor.blade.php
  app-modules/filament-tiptap-editor/src/TiptapConverter.php
  app-modules/filament-tiptap-editor/src/TiptapEditor.php
  resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php
  resources/views/filament/forms/components/campaigns/step-summary.blade.php
Labels: Change Type | Bug Fix

#930 [ADVAPP-765]: Introduce the ability to duplicate admissions applications
  app-modules/application/src/Actions/DuplicateApplication.php
  app-modules/application/src/Filament/Resources/ApplicationResource/Pages/ListApplications.php
Labels: Change Type | New Feature

#934 [ADVAPP-774]: Fix class naming of EditAiAssistantRequestFactory file
  app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/EditAiAssistantTest.php
  app-modules/ai/tests/Feature/Filament/Resources/AiAssistantResource/RequestFactories/EditAiAssistantRequestFactory.php
  app-modules/application/src/Filament/Resources/ApplicationResource/Pages/ListApplications.php
Labels: Change Type | Bug Fix

#933 [ADVAPP-603]: Unable to receive engagement updates on delivered emails as expected
  app-modules/integration-aws-ses-event-handling/routes/landlord.php
  app-modules/integration-aws-ses-event-handling/src/Http/Controllers/AwsSesInboundWebhookController.php
  app-modules/integration-aws-ses-event-handling/tests/Feature/Http/AwsSesInboundWebhookControllerTest.php
  app-modules/integration-aws-ses-event-handling/tests/Feature/Listeners/HandleSesEventTest.php
  app-modules/integration-aws-ses-event-handling/tests/Fixtures/Bounce.json
  app-modules/integration-aws-ses-event-handling/tests/Fixtures/Click.json
  app-modules/integration-aws-ses-event-handling/tests/Fixtures/Complaint.json
  app-modules/integration-aws-ses-event-handling/tests/Fixtures/Delivery.json
  app-modules/integration-aws-ses-event-handling/tests/Fixtures/DeliveryDelay.json
  app-modules/integration-aws-ses-event-handling/tests/Fixtures/Open.json
  app-modules/integration-aws-ses-event-handling/tests/Fixtures/Reject.json
  app-modules/integration-aws-ses-event-handling/tests/Fixtures/RenderingFailure.json
  app-modules/integration-aws-ses-event-handling/tests/Fixtures/Send.json
  app-modules/integration-aws-ses-event-handling/tests/Unit/SesConfigurationSetTest.php
  app-modules/notification/src/Notifications/BaseNotification.php
  app-modules/notification/src/Notifications/Concerns/EmailChannelTrait.php
Labels: Change Type | Bug Fix

#935 [ADVAPP-763]: Some legacy online admission applications are generating an exception when attempting to open
  app-modules/form/database/migrations/2024_05_03_174656_data_rename_checkbox_form_field.php
  app-modules/form/database/migrations/2024_05_03_175328_data_activate_rename_checkbox_form_field_feature_flag.php
  app-modules/form/src/Filament/Blocks/AgreementFormFieldBlock.php
  app-modules/form/src/Filament/Blocks/CheckboxesFormFieldBlock.php
  app-modules/survey/database/migrations/2024_05_03_201353_data_rename_checkbox_survey_field.php
  database/migrations/2024_07_31_202513_purge_checkbox_form_field_feature_flags.php
  database/migrations/2024_07_31_202514_data_rename_checkbox_form_fields.php
Labels: Change Type | Bug Fix, Change Type | Feature Cleanup
