Repository canyongbs/advisingapp, pull requests merged in 2024-02, with the labels that each got.

#542 Modify the PR template and contribution guidelines
  .github/pull_request_template.md
  README.md
Labels: Change Type | New Feature

#544 Fix minor typo in PR template
  .github/pull_request_template.md
Labels: Change Type | Bug Fix, Change Type | Content or Styling Update

#546 [ADVAPP-355] & [ADVAPP-356]: Organize the Display of Information for the Student / Prospect Record
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ViewStudent.php
Labels: Change Type | Content or Styling Update

#548 [ADVAPP-334]: Embed issue with navigation bar
  portals/knowledge-management/src/Components/DesktopSidebar.vue
Labels: Change Type | Bug Fix, Change Type | Content or Styling Update

#547 [ADVAPP-332]: Presentation of knowledge portal embed link breaks container
  app-modules/application/src/Filament/Resources/ApplicationResource/Pages/EditApplication.php
  app-modules/form/src/Filament/Resources/FormResource/Pages/EditForm.php
  app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource/Pages/EditServiceRequestForm.php
  app-modules/survey/src/Filament/Resources/SurveyResource/Pages/EditSurvey.php
  resources/css/filament/admin/theme.css
Labels: Change Type | Bug Fix, Change Type | Content or Styling Update

#543 [ADVAPP-340]: Images uploaded into a KB article fail to present in the public KB articles.
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalArticleController.php
Labels: Change Type | Bug Fix

#549 [ADVAPP-324]: Display knowledge base category icon in knowledge portal.
  app-modules/portal/src/DataTransferObjects/KnowledgeBaseCategoryData.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalController.php
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/DesktopSidebar.vue
  portals/knowledge-management/src/Components/HelpCenter.vue
  portals/knowledge-management/src/Components/MobileSidebar.vue
  portals/knowledge-management/src/Components/SidebarContent.vue
Labels: Change Type | New Feature, Change Type | Content or Styling Update

#556 [ADVAPP-366]: Table name change for KnowledgeBaseItems to KnowledgeBaseArticles
  app-modules/knowledge-base/database/migrations/2023_03_06_000012_create_knowledge_base_articles_table.php
  app-modules/knowledge-base/database/migrations/2023_03_06_000039_create_division_knowledge_base_item_pivot_table.php
  app-modules/knowledge-base/database/migrations/2023_03_06_000041_add_relationship_fields_to_knowledge_base_items_table.php
  app-modules/knowledge-base/graphql/knowledge-base-item.graphql
  app-modules/knowledge-base/src/Models/KnowledgeBaseItem.php
Labels: Change Type | New Feature

#554 [ADVAPP-357]: Complete address model for prospects
  app-modules/prospect/database/factories/ProspectFactory.php
  app-modules/prospect/database/migrations/2023_07_26_000003_create_prospects_table.php
  app-modules/prospect/graphql/prospect.graphql
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php
  app-modules/prospect/src/Models/Prospect.php
Labels: Change Type | New Feature

#552 [ADVAPP-361]: Extend user model with job title, [ADVAPP-360]: Enhance AI to be dynamically aware of the user creating prompts
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
  app-modules/integration-ai/src/Client/BaseAIChatClient.php
  app-modules/integration-ai/src/DataTransferObjects/DynamicContext.php
  app-modules/integration-ai/src/Models/Concerns/ProvidesDynamicContext.php
  app/Filament/Resources/UserResource.php
  app/Models/User.php
  database/migrations/2023_03_06_000004_create_users_table.php
Labels: Change Type | New Feature

#557 [ADVAPP-241]: Replace "cancelled" references with "canceled"
  app-modules/alert/src/Enums/AlertStatus.php
  app-modules/assistant/src/Jobs/ShareAssistantChatJob.php
  app-modules/inventory-management/database/factories/MaintenanceActivityFactory.php
  app-modules/inventory-management/src/Enums/MaintenanceActivityStatus.php
  app-modules/meeting-center/src/Jobs/CreateEventAttendee.php
  app-modules/task/src/Enums/TaskStatus.php
  app-modules/task/src/Filament/Resources/TaskResource/Components/TaskViewAction.php
  app/Console/Commands/GenerateHelperFiles.php
Labels: Change Type | New Feature

#565 [ADVAPP-321]: Save and file in one step for AI Assistant, [ADVAPP-322]: Introduce drag-and-drop chat organization into folders for AI assistant
  app-modules/assistant/resources/js/chats.js
  app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
  app-modules/assistant/src/Providers/AssistantServiceProvider.php
  app-modules/consent/src/Models/ConsentAgreement.php
  app/Console/Commands/CreateTenantCommand.php
  app/Console/Commands/ValidateGraphQL.php
  bin/build.js
Labels: Change Type | New Feature

#570 [BUGFIX] rtrim the openai URL
  app-modules/integration-ai/src/Client/AzureOpenAI.php
Labels: Change Type | Bug Fix

#566 [ADVAPP-387]: AI name and job title context not working as expected.
  app-modules/integration-ai/database/migrations/2024_02_26_191606_fix_ai_prompt_system_context_setting.php
  app-modules/integration-ai/src/Client/BaseAIChatClient.php
  app/Models/User.php
Labels: Change Type | Bug Fix

#568 [ADVAPP-365]: Design process for data migration
  _ide_helper_models.php
  app-modules/data-migration/composer.json
  app-modules/data-migration/config/permissions/api/custom.php
  app-modules/data-migration/config/permissions/web/custom.php
  app-modules/data-migration/config/roles/api/data-migration_roles.php
  app-modules/data-migration/config/roles/web/data-migration_roles.php
  app-modules/data-migration/database/factories/OperationFactory.php
  app-modules/data-migration/database/migrations/2024_02_26_000000_create_one_time_operations_table.php
  app-modules/data-migration/database/seeders/.gitkeep
  app-modules/data-migration/src/Commands/OneTimeOperationShowCommand.php
  app-modules/data-migration/src/Commands/OneTimeOperationsCommand.php
  app-modules/data-migration/src/Commands/OneTimeOperationsMakeCommand.php
  app-modules/data-migration/src/Commands/OneTimeOperationsProcessCommand.php
  app-modules/data-migration/src/Commands/Utils/ColoredOutput.php
  app-modules/data-migration/src/Commands/Utils/OperationsLineElement.php
  app-modules/data-migration/src/DataMigrationPlugin.php
  app-modules/data-migration/src/Enums/OperationType.php
  app-modules/data-migration/src/Jobs/LandlordOneTimeOperationProcessJob.php
  app-modules/data-migration/src/Jobs/OneTimeOperationProcessJob.php
  app-modules/data-migration/src/Jobs/TenantOneTimeOperationProcessJob.php
  app-modules/data-migration/src/Models/Operation.php
  app-modules/data-migration/src/OneTimeOperation.php
  app-modules/data-migration/src/OneTimeOperationCreator.php
  app-modules/data-migration/src/OneTimeOperationFile.php
  app-modules/data-migration/src/OneTimeOperationManager.php
  app-modules/data-migration/src/Providers/DataMigrationServiceProvider.php
  app-modules/data-migration/src/Registries/DataMigrationRbacRegistry.php
  app-modules/data-migration/tests/.gitkeep
  composer.json
  composer.lock
  config/one-time-operations.php
  database/landlord/2024_02_26_000000_create_one_time_operations_landlord_table.php
  database/operations/.gitkeep
  docs/data-migrations.md
  stubs/one-time-operation-essential.stub
  stubs/one-time-operation.stub
Labels: Change Type | New Feature, Change Type | DevOps, Deployment Steps

#571 Update default FORWARD_DB_PORT
  .env.example
Labels: Change Type | Bug Fix
