Repository canyongbs/advisingapp, pull requests merged in 2024-04, with the labels that each got.

#632 [ADVAPP-462]: Resolve embed snippet for forms
  app-modules/application/src/Filament/Resources/ApplicationResource/Pages/EditApplication.php
  app-modules/form/src/Actions/GenerateSubmissibleEmbedCode.php
  app-modules/form/src/Filament/Resources/FormResource/Pages/EditForm.php
  app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource/Pages/EditServiceRequestForm.php
  app-modules/survey/src/Filament/Resources/SurveyResource/Pages/EditSurvey.php
Labels: Change Type | Bug Fix

#636 [ADVAPP-467], [ADVAPP-468], and [ADVAPP-469]
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectApplicationSubmissions.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectFormSubmissions.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ProspectServiceManagement.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentApplicationSubmissions.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ManageStudentFormSubmissions.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/StudentServiceManagement.php
Labels: Change Type | New Feature

#637 [ADVAPP-353]: Ensure all commands return static::SUCCESS or static::FAILURE
  app-modules/authorization/src/Console/Commands/SetupPermissions.php
  app-modules/authorization/src/Console/Commands/SetupRoles.php
  app-modules/authorization/src/Console/Commands/SyncRolesAndPermissions.php
  app-modules/campaign/src/Console/Commands/ExecuteCampaignActions.php
  app-modules/caseload-management/src/Console/Commands/TranslateCaseload.php
  app-modules/engagement/src/Console/Commands/DeliverEngagements.php
  app-modules/meeting-center/src/Console/Commands/CreateEvent.php
  app-modules/meeting-center/src/Console/Commands/DeleteEvent.php
  app-modules/meeting-center/src/Console/Commands/RefreshCalendarRefreshTokens.php
  app-modules/meeting-center/src/Console/Commands/SyncEvents.php
  app-modules/meeting-center/src/Console/Commands/UpdateEvent.php
  app-modules/notification/src/Console/Commands/SimulatedNotification.php
  app/Console/Commands/BuildAssets.php
  app/Console/Commands/ClearTestMigrationCache.php
  app/Console/Commands/ConnectOlympus.php
  app/Console/Commands/CreateSuperAdmin.php
  app/Console/Commands/CreateTenant.php
  app/Console/Commands/GenerateHelperFiles.php
  app/Console/Commands/InitialMigration.php
  app/Console/Commands/MigrateFreshLandlord.php
  app/Console/Commands/MigrateLandlord.php
  app/Console/Commands/OpenSearchDeleteAllIndices.php
  app/Console/Commands/OpenSearchList.php
  app/Console/Commands/PrintApiSchema.php
  app/Console/Commands/ValidateGraphQL.php
Labels: Change Type | Bug Fix

#638 [ADVAPP-466]: API docs link produces an error
  docker/s6-overlay/s6-rc.d/generate-api-docs/dependencies
  docker/s6-overlay/s6-rc.d/generate-api-docs/type
  docker/s6-overlay/s6-rc.d/generate-api-docs/up
  docker/s6-overlay/scripts/generate-api-docs
  docker/s6-overlay/user/generate-api-docs
  package-lock.json
  package.json
Labels: Change Type | Bug Fix, Change Type | New Feature

#634 [ADVAPP-383]: Delay loading of portal contents until after authentication
  app-modules/portal/routes/api.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalCategoryController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalController.php
  portals/knowledge-management/src/App.vue
Labels: Change Type | Bug Fix

#640 [ADVAPP-495]: Regression for inserting prompt from prompt library
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
Labels: Change Type | Bug Fix

#641 fix: Create tenant as super admin
  app/Jobs/CreateTenantUser.php
Labels: Change Type | Bug Fix

#642 [ADVAPP-466]: API docs link produces an error
  package.json
  spectaql.yml
Labels: Change Type | Bug Fix

#643 [ADVAPP-431]: Fix file permission issues in docker containers
  Dockerfile
  docker/s6-overlay/scripts/initial-migration
  docker/s6-overlay/scripts/laravel-migrate
  docker/s6-overlay/scripts/laravel-octane
Labels: Change Type | DevOps

#645 Remove changing the User
  Dockerfile
Labels: Change Type | DevOps

#647 [ADVAPP-483]: Introduce new users list view bulk license assign operation
  app-modules/authorization/tests/Feature/Filament/Resources/User/Actions/AssignLicensesBulkActionTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Actions/AssignLicensesBulkAction.php
  app/Models/User.php
Labels: Change Type | New Feature

#648 [ADVAPP-477]: Online Admissions settings should not present under Product Administration when feature is disabled, [ADVAPP-479]: Make Schedule & Appointments Feature Configurable Per Tenant
  app-modules/application/src/Policies/ApplicationSubmissionStatePolicy.php
  app-modules/meeting-center/src/Policies/CalendarEventPolicy.php
  app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php
  app/Enums/Feature.php
  app/Filament/Pages/ManageLicenseSettings.php
Labels: Change Type | New Feature

#649 Rename the add-ons to enabled features
  app/Filament/Pages/ManageLicenseSettings.php
Labels: Change Type | Content or Styling Update

#652 [ADVAPP-435]: Implement loader presentation when sending messages to the AI assistant.
  app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php
Labels: Change Type | New Feature, Change Type | Content or Styling Update

#654 [OLYMPUS-23]: Add API to Sync Application Plan Data
  app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/CreatePromptTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/EditPromptTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/ListPromptsTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptResource/ViewPromptTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptTypeResource/CreatePromptTypeTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptTypeResource/EditPromptTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptTypeResource/ListPromptTypesTest.php
  app-modules/assistant/tests/Feature/Filament/Resources/PromptTypeResource/ViewPromptTypeTest.php
  app-modules/authorization/src/Console/Commands/SyncRolesAndPermissions.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/Actions/AssignLicensesBulkActionTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Console/Commands/CreateTenant.php
  app/DataTransferObjects/LicenseManagement/LicenseLimitsData.php
  app/DataTransferObjects/LicenseManagement/LicenseSubscriptionData.php
  app/Filament/Pages/ManageLicenseSettings.php
  app/Http/Controllers/Tenants/CreateTenantController.php
  app/Http/Controllers/Tenants/SyncTenantController.php
  app/Http/Requests/Tenants/CreateTenantRequest.php
  app/Http/Requests/Tenants/SyncTenantRequest.php
  app/Jobs/CreateTenantUser.php
  app/Jobs/UpdateTenantLicenseData.php
  app/Multitenancy/Actions/CreateTenant.php
  composer.json
  composer.lock
  config/app.php
  database/seeders/SisDataSeeder.php
  database/settings/2023_11_29_192230_create_license_settings.php
  docker-compose.dev.yml
  routes/landlord_api.php
  tests/Pest.php
  tests/TestCase.php
Labels: Change Type | New Feature

#658 Role group cleanup
  app-modules/authorization/config/roles/web/role_group_manager.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/CreateRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/EditRole.php
  config/roles/web/role_management.php
  docs/roles-and-permissions.md
Labels: Change Type | Bug Fix, Change Type | Documentation

#653 [ADVAPP-482]: Introduce ability to import a list of users
  app/Filament/Imports/UserImporter.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
  app/Models/User.php
  app/Policies/UserPolicy.php
Labels: Change Type | New Feature

#669 [ADVAPP-497]: Introduce template acceptable use policy for colleges upon tenant creation
  app-modules/consent/database/seeders/ConsentAgreementSeeder.php
Labels: Change Type | Content or Styling Update

#665 [ADVAPP-474]: Ensure license settings are only configurable from Olympus
  app/Filament/Pages/ManageLicenseSettings.php
Labels: Change Type | Bug Fix

#671 [ADVAPP-506]: Enhance emailed chats by including formatting
  app-modules/assistant/src/Notifications/SendAssistantTranscriptNotification.php
Labels: Change Type | Bug Fix

#675 [ADVAPP-367]: AI chat history sometimes presents out of order
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
  app-modules/assistant/src/Services/AIInterface/DataTransferObjects/ChatMessage.php
  app-modules/assistant/tests/Feature/Filament/Pages/AIAssistantPageTest.php
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#668 [ADVAPP-500]: [Cleanup] ADVAPP-494 new-enrollments-columns
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EnrollmentsRelationManager.php
  database/migrations/2024_04_05_214333_data_clean_up_new_enrollments_columns_feature.php
Labels: Change Type | Feature Cleanup

#663 [ADVAPP-476] - Enhance presentation of Product Administration Section
  app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
  app-modules/authorization/src/Filament/Pages/ManageGoogleSsoSettings.php
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php
  app-modules/integration-google-recaptcha/src/Filament/Pages/ManageGoogleRecaptchaSettings.php
  app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php
  app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
  app-modules/meeting-center/src/Filament/Pages/ManageAzureCalendarSettings.php
  app-modules/meeting-center/src/Filament/Pages/ManageGoogleCalendarSettings.php
  app/Filament/Clusters/ArtificialIntelligence.php
  app/Filament/Clusters/AssetManagement.php
  app/Filament/Clusters/Communication.php
  app/Filament/Clusters/GlobalSettings.php
  app/Filament/Clusters/InteractionManagement.php
  app/Filament/Clusters/KnowledgeManagement.php
  app/Filament/Clusters/OnlineAdmissions.php
  app/Filament/Clusters/ProductIntegrations.php
  app/Filament/Clusters/ProfileManagement.php
  app/Filament/Clusters/ProspectManagement.php
  app/Filament/Clusters/ServiceManagementAdministration.php
  app/Filament/Clusters/UserManagement.php
Labels: Change Type | Content or Styling Update

#683 [ADVAPP-508]: Session Driver inconsistencies
  .env.example
  app/Multitenancy/Tasks/SwitchSessionDriver.php
  config/database.php
Labels: Change Type | Bug Fix, Change Type | DevOps, Deployment Steps

#689 [ADVAPP-262]: Write unit tests to Ensure all Tenancy switches happen as we would expect
  app/Console/Commands/CreateTenant.php
  config/app.php
  tests/Feature/Multitenancy/Actions/CreateTenantTest.php
  tests/Feature/Multitenancy/Http/Middleware/NeedsTenantTest.php
  tests/Feature/Multitenancy/LandlordTest.php
  tests/Feature/Multitenancy/Tasks/PrefixeCacheTaskTest.php
  tests/Feature/Multitenancy/Tasks/SwitchAppKeyTest.php
  tests/Feature/Multitenancy/Tasks/SwitchAppNameTest.php
  tests/Feature/Multitenancy/Tasks/SwitchAppUrlTest.php
  tests/Feature/Multitenancy/Tasks/SwitchMailTaskTest.php
  tests/Feature/Multitenancy/Tasks/SwitchS3FilesystemTaskTest.php
  tests/Feature/Multitenancy/Tasks/SwitchS3PublicFilesystemTaskTest.php
  tests/Feature/Multitenancy/Tasks/SwitchTenantDatabasesTaskTest.php
  tests/TestCase.php
Labels: Change Type | New Feature

#688 [ADVAPP-513]: Enhance look and feel of knowledge portal
  app-modules/portal/routes/api.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalLogoutController.php
  portals/knowledge-management/src/App.vue
  portals/knowledge-management/src/Components/AppLoading.vue
  portals/knowledge-management/src/Components/Breadcrumbs.vue
  portals/knowledge-management/src/Components/DesktopSidebar.vue
  portals/knowledge-management/src/Components/HelpCenter.vue
  portals/knowledge-management/src/Components/Loading.vue
  portals/knowledge-management/src/Components/MobileSidebar.vue
  portals/knowledge-management/src/Components/SearchLoading.vue
  portals/knowledge-management/src/Components/SearchResults.vue
  portals/knowledge-management/src/Components/SidebarContent.vue
  portals/knowledge-management/src/Pages/Home.vue
  portals/knowledge-management/src/Pages/ViewArticle.vue
  portals/knowledge-management/src/Pages/ViewCategory.vue
  resources/views/vendor/cookie-consent/dialog.blade.php
  widgets/form/src/FormKit/theme.js
Labels: Change Type | Content or Styling Update

#691 [ADVAPP-512]: Enhance audit capabilities by introducing export features
  app-modules/assistant/src/Filament/Exports/AssistantChatMessageLogExporter.php
  app-modules/assistant/src/Filament/Resources/AssistantChatMessageLogResource.php
  app-modules/assistant/src/Filament/Resources/AssistantChatMessageLogResource/Pages/ManageAssistantChatMessageLogs.php
  app-modules/audit/src/Filament/Exports/AuditExporter.php
  app-modules/audit/src/Filament/Resources/AuditResource/Pages/ListAudits.php
  tests/Feature/Multitenancy/LandlordTest.php
Labels: Change Type | New Feature

#692 [ADVAPP-509] Update Navigation Placement for Schedule & Appointment Features
  app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php
Labels: Change Type | Content or Styling Update

#695 [ADVAPP-507] Cannot detach a task from Student/Prospect
  app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php
Labels: Change Type | Bug Fix
