Repository canyongbs/advisingapp, pull requests merged in 2024-03, with the labels that each got.

#572 [ADVAPP-400]: Introduce ability to search prompt library and insert p…
  app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
Labels: Change Type | New Feature

#576 [ADVAPP-346]: Upvote knowledge base articles
  app-modules/knowledge-base/database/migrations/2024_03_04_154518_create_knowledge_base_item_upvotes_table.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php
  app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ViewKnowledgeBaseItem.php
  app-modules/knowledge-base/src/Models/KnowledgeBaseItem.php
  app-modules/knowledge-base/src/Models/KnowledgeBaseItemUpvote.php
Labels: Change Type | New Feature

#578 [ADVAPP-49]: Display whether or not a User is currently active in chat
  app-modules/in-app-communication/resources/js/userToUserChat.js
  app-modules/in-app-communication/resources/views/filament/pages/user-chat.blade.php
  app-modules/in-app-communication/src/Filament/Pages/UserChat.php
  app/Models/User.php
  database/migrations/2024_03_04_165304_add_last_chat_ping_at_column_to_users_table.php
Labels: Change Type | New Feature

#580 [ADVAPP-396]: Menu jump on navigate no longer works
  composer.lock
Labels: Change Type | Bug Fix

#581 [ADVAPP-277]: CI/CD to support production releases
  .dockerignore
  .env.example
  Dockerfile
  app-modules/data-migration/src/Jobs/TenantOneTimeOperationProcessJob.php
  app-modules/portal/routes/api.php
  app/Console/Commands/CreateTenantCommand.php
  app/Console/Commands/DispatchLandlordMigrations.php
  app/Console/Commands/DispatchMigrations.php
  app/Console/Commands/DispatchTenantMigrations.php
  app/Events/LandlordMigrationBatchFailure.php
  app/Events/LandlordMigrationBatchSuccessful.php
  app/Events/TenantMigrationBatchFailure.php
  app/Events/TenantMigrationBatchSuccessful.php
  app/Jobs/DispatchLandlordDataMigrations.php
  app/Jobs/DispatchTenantDataMigrations.php
  app/Jobs/LandlordSchemaMigration.php
  app/Jobs/TenantSchemaMigration.php
  app/Multitenancy/Tasks/SwitchTenantDatabasesTask.php
  database/operations/2024_03_01_173404_update_all_tenants_mail_from_address.php
  docker-compose.dev.yml
  docker/s6-overlay/s6-rc.d/cache-icons/up
  docker/s6-overlay/s6-rc.d/clear-cache/up
  docker/s6-overlay/s6-rc.d/landlord-migrate/dependencies
  docker/s6-overlay/s6-rc.d/landlord-migrate/type
  docker/s6-overlay/s6-rc.d/landlord-migrate/up
  docker/s6-overlay/s6-rc.d/laravel-migrate/dependencies
  docker/s6-overlay/s6-rc.d/laravel-migrate/type
  docker/s6-overlay/s6-rc.d/laravel-migrate/up
  docker/s6-overlay/s6-rc.d/laravel-octane/dependencies
  docker/s6-overlay/s6-rc.d/laravel-queue/dependencies
  docker/s6-overlay/s6-rc.d/laravel-scheduler/dependencies
  docker/s6-overlay/s6-rc.d/startup-caching/dependencies
  docker/s6-overlay/s6-rc.d/startup-caching/type
  docker/s6-overlay/s6-rc.d/startup-caching/up
  docker/s6-overlay/scripts/cache-icons
  docker/s6-overlay/scripts/clear-cache
  docker/s6-overlay/scripts/landlord-migrate
  docker/s6-overlay/scripts/laravel-migrate
  docker/s6-overlay/scripts/laravel-octane
  docker/s6-overlay/scripts/laravel-queue
  docker/s6-overlay/scripts/laravel-scheduler
  docker/s6-overlay/scripts/startup-caching
  docker/s6-overlay/user/cache-icons
  docker/s6-overlay/user/clear-cache
  docker/s6-overlay/user/landlord-migrate
  docker/s6-overlay/user/laravel-migrate
  docker/s6-overlay/user/startup-caching
  docs/local-setup.md
Labels: Change Type | New Feature, Change Type | DevOps, Deployment Steps

#588 Quick bugfixes
  app-modules/portal/src/Actions/GeneratePortalEmbedCode.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalController.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalLogoutController.php
  app-modules/prospect/src/Models/Prospect.php
  app/Notifications/SetPasswordNotification.php
Labels: Change Type | Bug Fix

#596 Change the api driver to session
  config/auth.php
Labels: Change Type | Bug Fix

#593 [ADVAPP-398]: Ensure that portal login only uses student and prospect guards
  app-modules/portal/routes/api.php
  app-modules/portal/src/Http/Controllers/KnowledgeManagement/KnowledgeManagementPortalLogoutController.php
Labels: Change Type | New Feature

#597 [ADVAPP-411]: Modify Button Label for Prompt Library
  app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
Labels: Change Type | Content or Styling Update

#598 [ADVAPP-407] && [ADVAPP-408] && [ADVAPP-423]: Implement Rich Text Editing and Templates in Campaign Journey Step
  app-modules/campaign/src/Filament/Blocks/EngagementBatchBlock.php
  app-modules/caseload-management/src/Filament/Resources/CaseloadResource/Pages/GetCaseloadQuery.php
  app-modules/caseload-management/src/Filament/Resources/CaseloadResourceForProcesses.php
  app-modules/engagement/src/Models/EngagementBatch.php
  database/seeders/NewTenantSeeder.php
  resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php
Labels: Change Type | Bug Fix, Change Type | Feature Cleanup

#592 [ADVAPP-391]: Enhance Create Prospect experience by auto generating full name.
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
Labels: Change Type | New Feature, Change Type | Content or Styling Update

#599 [ADVAPP-418]: Resolve Prototype Pollution XSS issue
  composer.lock
Labels: Change Type | Dependencies

#601 Fix one time operation
  database/operations/2024_03_12_135601_activate_interaction_defaults_feature_flag.php
Labels: Change Type | Bug Fix

#591 [ADVAPP-388] [Cleanup]: Introduce the ability to order prospect status, and default to the value in the create prospect experience to the highest ordered option
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/prospect/src/Filament/Resources/ProspectStatusResource/Pages/EditProspectStatus.php
  app-modules/prospect/src/Filament/Resources/ProspectStatusResource/Pages/ListProspectStatuses.php
  app-modules/prospect/src/Filament/Resources/ProspectStatusResource/Pages/ViewProspectStatus.php
  app-modules/prospect/src/Observers/ProspectStatusObserver.php
  database/operations/2024_02_11_132430_fill_prospect_status_sort_values.php
  database/operations/2024_02_11_132431_purge_prospect_status_sort_feature_flag.php
Labels: Change Type | New Feature, Change Type | Feature Cleanup

#606 [ADVAPP-434]: Currently some subdomains present a 401 error when accessing & [ADVAPP-373]: Tenant connections not using DB for sessions
  app/Multitenancy/Tasks/SwitchSessionDriver.php
Labels: Change Type | Bug Fix, Change Type | New Feature

#608 [ADVAPP-340]: Enhance AI by updating label for for button.
  app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php
  app-modules/report/resources/views/filament/pages/report-assistant.blade.php
Labels: Change Type | Content or Styling Update

#604 [ADVAPP-426]: Emailed chats include broken link to logo
  resources/views/vendor/mail/html/header.blade.php
Labels: Change Type | Bug Fix

#609 [ADVAPP-428]: Enhance AI by retaining customer supplied formatting in chats.
  app-modules/assistant/resources/views/filament/pages/personal-assistant.blade.php
  app-modules/report/resources/views/filament/pages/report-assistant.blade.php
Labels: Change Type | Bug Fix

#611 [ADVAPP-438]: Setup Advising App remote development environment
  .env.example
  docker-compose.dev.yml
  docker-compose.yml
Labels: Change Type | New Feature, Change Type | DevOps

#612 Fix build permissions
  Dockerfile
Labels: Change Type | Bug Fix

#615 [HOTFIX] Only run vite build in s6-overlay
  docker/s6-overlay/scripts/build-assets
Labels: Change Type | DevOps

#616 [Hotfix] Ensure we run filament:assets on startup
  docker/s6-overlay/scripts/build-assets
Labels: Change Type | DevOps

#622 [ADVAPP-410]: Invert heading colors presenting in main navigation
  resources/css/filament/admin/theme.css
Labels: Change Type | Content or Styling Update

#623 [ADVAPP-427]: Update email copyright template
  resources/views/vendor/mail/html/message.blade.php
Labels: Change Type | Content or Styling Update

#627 Updates the nginx check to grab the last status code
  docker/s6-overlay/s6-rc.d/nginx/data/check
Labels: Change Type | DevOps
