Repository canyongbs/advisingapp, pull requests merged in 2025-02, with the labels that each got.

#1281 [ADVAPP-1173]: Enhance the ability to distinguish the main navigation from the page itself
  resources/css/filament/admin/theme.css
Labels: Change Type | Content or Styling Update

#1280 [ADVAPP-1161]: Enhance the user importer experience for user administrators
  app/Filament/Imports/UserImporter.php
Labels: Change Type | New Feature

#1286 [ADVAPP-1165]: Update Roadrunner to 2024.3.2
  Dockerfile
Labels: Change Type | Documentation

#1292 [ADVAPP-1178]: Automatically update student and prospect messages on-screen to improve holistic management when they arrive -- without having to refresh the page
  app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/EngagementsRelationManager.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
Labels: Change Type | Documentation

#1293 [ADVAPP-1183]: Add a notification to the receiving user of a AI clone chat
  app-modules/ai/resources/js/chats.js
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php
  app-modules/ai/src/Jobs/CloneAiThread.php
Labels: Change Type | New Feature

#1297 [ADVAPP-1202]: Cleanup refactored code and jobs after engagement refactor release
  app-modules/engagement/database/migrations/2025_02_03_135729_data_fill_processing_timestamp_columns_in_engagements_table.php
  app-modules/engagement/database/migrations/2025_02_03_135948_activate_engagements_feature.php
  app-modules/engagement/database/migrations/2025_02_05_134045_drop_deliver_at_column_from_engagements_table.php
  app-modules/engagement/graphql/engagement.graphql
  app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
  app-modules/engagement/src/Actions/Contracts/EngagementChannel.php
  app-modules/engagement/src/Actions/CreateEngagementBatch.php
  app-modules/engagement/src/Actions/EngagementEmailChannelDelivery.php
  app-modules/engagement/src/Actions/EngagementSmsChannelDelivery.php
  app-modules/engagement/src/Actions/QueuedEngagementDelivery.php
  app-modules/engagement/src/Console/Commands/DeliverEngagements.php
  app-modules/engagement/src/DataTransferObjects/EngagementBatchCreationData.php
  app-modules/engagement/src/Drivers/Contracts/EngagementDeliverableDriver.php
  app-modules/engagement/src/Drivers/EngagementEmailDriver.php
  app-modules/engagement/src/Drivers/EngagementSmsDriver.php
  app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
  app-modules/engagement/src/Filament/Actions/MessageCenterSendEngagementAction.php
  app-modules/engagement/src/Filament/Actions/RelationManagerSendEngagementAction.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/engagement/src/Models/Concerns/HasManyMorphedEngagements.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/engagement/src/Models/EngagementBatch.php
  app-modules/engagement/src/Notifications/EngagementEmailNotification.php
  app-modules/engagement/src/Notifications/EngagementSmsNotification.php
  app-modules/engagement/src/Observers/EngagementObserver.php
  app-modules/engagement/tests/Feature/Actions/CreateEngagementBatchTest.php
  app-modules/timeline/src/Timelines/EngagementTimeline.php
  app/Console/Kernel.php
  app/Features/EngagementsFeature.php
Labels: Change Type | Feature Cleanup

#1299 [ADVAPP-1189]: Add .psysh_history to the .gitignore
  .gitignore
Labels: Change Type | Chore

#1306 [ADVAPP-1199] Feature Flag Cleanup: EngagementFilesCreatedByFeature
  app-modules/engagement/database/migrations/2025_02_07_052340_data_activate_engagement_files_created_by_feature.php
  app-modules/engagement/src/Filament/Resources/EngagementFileResource/RelationManagers/EngagementFilesRelationManager.php
  app-modules/engagement/src/Observers/EngagementFileObserver.php
  app/Features/EngagementFilesCreatedByFeature.php
Labels: Change Type | Feature Cleanup

#1303 [ADVAPP-1205]: Introduce a new alerts filter for students and prospects
  app-modules/alert/src/Enums/SystemAlertStatusClassification.php
  app-modules/alert/src/Filament/Resources/AlertResource/Pages/ListAlerts.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/prospect/tests/Tenant/Prospect/ListProspectTest.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
  app-modules/student-data-model/tests/Tenant/Student/ListStudentsTest.php
Labels: Change Type | New Feature

#1317 [ADVAPP-1209]: Feature Flag and Data Migration Cleanup: MessageEventsDisplay
  app-modules/notification/database/migrations/2025_02_10_224226_data_tmp_purge_all_outbound_deliverable_timeline_records.php
  app-modules/notification/database/migrations/2025_02_12_000642_data_tmp_activate_message_events_display_feature_flag.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
  app/Features/MessageEventsDisplay.php
Labels: Change Type | Feature Cleanup

#1311 [ADVAPP-1216]: Show the complete number of students in the student, prospect, and report
  app-modules/prospect/src/Filament/Widgets/ProspectStats.php
  app-modules/report/src/Filament/Widgets/ProspectReportStats.php
  app-modules/report/src/Filament/Widgets/StudentsStats.php
  app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
Labels: Change Type | Bug Fix

#1320 [ADVAPP-1206]: Remove the display of "Permissions" as a standalone model under user management
  app-modules/authorization/src/Filament/Resources/PermissionResource.php
  app-modules/authorization/src/Filament/Resources/PermissionResource/Pages/ListPermissions.php
  app-modules/authorization/src/Policies/PermissionPolicy.php
  app-modules/authorization/tests/Tenant/Feature/Filament/Resources/User/EditUserTest.php
  app-modules/division/src/Filament/Resources/DivisionResource.php
  app/Filament/Resources/SystemUserResource.php
  database/migrations/2025_02_26_095357_seed_permissions_remove_permission_from_permissions_table.php
Labels: Change Type | Chore

#1316 [ADVAPP-1197]: Convert dashboard card headings into hyperlinks for quick access to list views
  app-modules/prospect/src/Filament/Widgets/ProspectStats.php
  app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
Labels: Change Type | New Feature

#1323 [ADVAPP-1085]: Remove TrimStrings middleware from Twilio inbound webhook route
  app-modules/integration-twilio/routes/web.php
Labels: Change Type | Bug Fix

#1324 [ADVAPP-1085]: Update Twilio request validation to use HTTPS URL
  app-modules/integration-twilio/src/Http/Middleware/EnsureTwilioRequestIsValid.php
Labels: Change Type | Bug Fix

#1326 [ADVAPP-1243]: Resolve flaky test in SendMessageTest
  app-modules/ai/tests/Tenant/Feature/Actions/SendMessageTest.php
Labels: Change Type | Bug Fix

#1328 [ADVAPP-1204]: Resolve flaky test in OpenAiGptTestServiceTest
  app-modules/integration-open-ai/tests/Tenant/Feature/Services/OpenAiGptTestServiceTest.php
Labels: Change Type | Bug Fix

#1329 [ADVAPP-1013]: Form submission Prospect generation improvements
  app-modules/form/database/migrations/2024_11_06_145142_add_generate_prospects_to_forms_table.php
  app-modules/form/src/Filament/Resources/FormResource/Pages/Concerns/HasSharedFormConfiguration.php
Labels: Change Type | Chore

#1330 [ADVAPP-1228]: Feature Flag Cleanup: CaseFeedback
  app-modules/case-management/src/Http/Middleware/FeedbackManagementIsOn.php
  app-modules/case-management/src/Observers/CaseObserver.php
  app/Features/CaseFeedback.php
  database/migrations/2025_02_25_061839_data_activate_feature_flag_case_feedback.php
Labels: Change Type | Feature Cleanup

#1331 [ADVAPP-1230]: Update the license in the composer.json
  composer.json
Labels: Change Type | Content or Styling Update

#1333 [ADVAPP-1240]: Relocate Cognitive Services to Artificial Intelligence Navigation
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
Labels: Change Type | Documentation
