Repository canyongbs/advisingapp, pull requests merged in 2025-04, with the labels that each got.

#1412 [ADVAPP-1295]: Overwrite the migration stub to use the tpetry/laravel-postgresql-enhanced classes
  stubs/migration.create.stub
  stubs/migration.stub
  stubs/migration.update.stub
Labels: Change Type | New Feature

#1415 [ADVAPP-1325]: Update Laravel Octane to version 2.8.3
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#1416 [OLYMPUS-441]: Tiptap merge tags type ahead is currently limited to only 5 items and typeahead search does not seem to be working
  composer.lock
Labels: Change Type | Bug Fix

#1417 [ADVAPP-1331]: Change PHPStan to Level 6 and create a baseline
  app-modules/engagement/tests/Tenant/Feature/EngagementFile/EngagementFilePruningTest.php
  phpstan-baseline.php
  phpstan.neon.dist
Labels: Change Type | Chore

#1418 [ADVAPP-1322]: Demo mode for text messages fails to simulate a text message reply
  app-modules/engagement/src/Notifications/EngagementNotification.php
Labels: Change Type | Bug Fix

#1419 [ADVAPP-1328]: Apply Filament and Laravel auto discovery caching during CI linting and CI testing
  .github/workflows/ci.yml
  Dockerfile
  phpstan-ci.neon
  phpunit-ci.xml
  phpunit.xml
Labels: Change Type | Chore

#1428 [ADVAPP-1328]: Disable error report of unmatched ignored errors
  phpstan.neon.dist
Labels: Change Type | Bug Fix

#1420 [ADVAPP-1317]: Update the role search functionality to not be case-sensitive when typing to attach a role
  app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
Labels: Change Type | Documentation

#1434 Update common package version to ^1.1.1 in composer files
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#1435 [ADVAPP-1358]: Update RoadRunner binary
  Dockerfile
Labels: Change Type | Dependencies

#1432 [ADVAPP-1333]: The pie chart and tabular data in the deliverability report is not correctly identifying email and SMS eligibility
  app-modules/report/src/Filament/Widgets/StudentDeliverableTable.php
  app-modules/report/src/Filament/Widgets/StudentEmailOptInOptOutPieChart.php
  app-modules/report/src/Filament/Widgets/StudentSmsOptInOptOutPieChart.php
  app-modules/report/tests/Tenant/Unit/StudentDeliverabilityReport/StudentDeliverabilityReportTest.php
Labels: Change Type | Content or Styling Update

#1422 [ADVAPP-1223]: When a logged in user visits the login page, it does not automatically redirect them to the appropriate target
  app-modules/authorization/src/Filament/Pages/Auth/Login.php
Labels: Change Type | Bug Fix

#1426 [ADVAPP-1332]: Improve the holistic student and prospect page experience by linking directly to filtered alerts and tasks
  app-modules/alert/src/Notifications/AlertCreatedNotification.php
  app-modules/prospect/resources/views/filament/resources/prospect-resource/view-prospect.blade.php
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-alerts-widget.blade.php
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-tasks-widget.blade.php
  app-modules/student-data-model/resources/views/filament/resources/student-resource/view-student.blade.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableAlertsWidget.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableTasksWidget.php
Labels: Change Type | New Feature

#1437 [ADVAPP-1302]: Certain development environments are generating an exception when navigating to cases
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ListCases.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ViewCase.php
  app-modules/case-management/src/Policies/CaseModelPolicy.php
Labels: Change Type | Bug Fix

#1443 [ADVAPP-1382]: Sometimes the product admin does not have values available for Email or SMS Deliverability, Dual Enrollment, FERPA, SAP, or First Generation, and the record sync and importer tools generate an exception when students/prospects are missing this information
  app-modules/prospect/database/migrations/2025_04_11_165212_make_all_prospect_boolean_columns_nullable.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Schemas/ProspectProfileInfolist.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Tables/ProspectsTable.php
  app-modules/prospect/src/Imports/ProspectImporter.php
  app-modules/report/src/Filament/Widgets/StudentEmailOptInOptOutPieChart.php
  app-modules/report/src/Filament/Widgets/StudentSmsOptInOptOutPieChart.php
  app-modules/student-data-model/database/migrations/2025_04_11_164454_make_all_student_boolean_columns_nullable.php
  app-modules/student-data-model/src/Filament/Imports/StudentImporter.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
  app-modules/student-data-model/src/Models/Student.php
Labels: Change Type | Bug Fix

#1453 [ADVAPP-1386]: Improve the ease-of-use for record sync (students) or import (prospects) of phone numbers by handling more customer entered number formats in source files and transforming them automatically
  app-modules/prospect/src/Imports/ProspectImporter.php
  app-modules/student-data-model/src/Filament/Imports/StudentEmailAddressImporter.php
  app-modules/student-data-model/src/Filament/Imports/StudentPhoneNumberImporter.php
  app/Features/ImportSettingsFeature.php
  app/Filament/Pages/ManageImportSettings.php
  app/Settings/ImportSettings.php
  composer.json
  composer.lock
  database/migrations/2025_04_12_163924_create_import_settings_table.php
  database/migrations/2025_04_13_164704_data_activate_import_settings_feature.php
Labels: Change Type | New Feature, Feature Flag Added

#1448 [ADVAPP-1385]: Update the label used in the create and edit prospect forms to state High School Graduation Year
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
Labels: Change Type | Bug Fix

#1450 [ADVAPP-1375]: When clicking hyperlinked tasks or alerts boxes in prospect profile, the page layout differs from the student profile
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/Concerns/HasProspectHeader.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectTasks.php
Labels: Change Type | Bug Fix

#1451 [ADVAPP-1354]: Change default sort on interactions and tasks to be most recent first
  app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableTasks.php
  app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php
Labels: Change Type | Bug Fix

#1454 [ADVAPP-1384]: Update the label used in the create and edit student forms to state High School Graduation Year
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php
Labels: Change Type | Bug Fix

#1457 [ADVAPP-1383]: Resolve the security issue tracked under CVE-2025-32395
  package-lock.json
  package.json
Labels: Change Type | Dependencies

#1462 [ADVAPP-1388]: Remove CareTeamRoleFeature
  app-modules/campaign/src/Filament/Blocks/CareTeamBlock.php
  app-modules/care-team/database/migrations/2025_04_16_211240_data_activate_care_team_role_feature.php
  app-modules/care-team/src/Filament/Actions/AddCareTeamMemberAction.php
  app-modules/care-team/src/Filament/Resources/ProspectCareTeamRoleResource.php
  app-modules/care-team/src/Filament/Resources/StudentCareTeamRoleResource.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-care-team-widget.blade.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableCareTeam.php
  app/Features/CareTeamRoleFeature.php
  resources/views/filament/forms/components/campaigns/actions/care-team.blade.php
Labels: Change Type | Chore

#1466 [ADVAPP-1394]: Rename My Dashboard to Action Center in the Retention CRM and Recruitment CRM module navigation
  app-modules/prospect/src/Filament/Pages/RecruitmentCrmDashboard.php
  app-modules/student-data-model/src/Filament/Pages/RetentionCrmDashboard.php
Labels: Change Type | Content or Styling Update

#1471 [ADVAPP-1403]: When attempting to view a text message scheduled to Send Later, an error is thrown
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
Labels: Change Type | Bug Fix

#1464 [ADVAPP-1389]: When adding a new care team member, users already in the care team are still listed and selectable
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectCareTeam.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableCareTeam.php
Labels: Change Type | Bug Fix

#1475 [ADVAPP-1411]: Introduce the ability to synchronize smart prompts and prerequisite categories to all deployments with AI enabled
  app-modules/ai/src/Actions/SyncTenantSmartPrompts.php
  app/Http/Controllers/Tenants/SyncTenantController.php
  app/Http/Requests/Tenants/SyncTenantRequest.php
Labels: Change Type | New Feature

#1473 [ADVAPP-1398]: Expand the data model for students to include gender
  app-modules/student-data-model/database/migrations/2025_04_22_173836_add_gender_column_in_students_table.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
  app-modules/student-data-model/src/Models/Student.php
  app/Features/StudentGender.php
  database/migrations/2025_04_23_133144_data_activate_feature_flag_student_gender.php
Labels: Change Type | New Feature, Feature Flag Added

#1465 [ADVAPP-1395]: Add a filter for Message Center for inbound messages
  app-modules/engagement/database/seeders/EngagementResponseSeeder.php
  app-modules/engagement/resources/views/components/filters.blade.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
Labels: Change Type | New Feature

#1477 [ADVAPP-1419]: Scheduler throws a memory error due to ENV vars not properly being passed to cron
  docker/scheduler/s6-overlay/scripts/cron
Labels: Change Type | Bug Fix

#1489 [ADVAPP-1437]: Update action center with important actionable insight…
  app-modules/alert/src/Observers/AlertObserver.php
  app-modules/notification/src/Observers/SubscriptionObserver.php
  app-modules/prospect/src/Filament/Pages/RecruitmentCrmDashboard.php
  app-modules/prospect/src/Filament/Widgets/ProspectStats.php
  app-modules/prospect/src/Filament/Widgets/ProspectTasks.php
  app-modules/prospect/src/Filament/Widgets/ProspectsActionCenterWidget.php
  app-modules/segment/src/Observers/SegmentObserver.php
  app-modules/student-data-model/src/Filament/Pages/RetentionCrmDashboard.php
  app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
  app-modules/student-data-model/src/Filament/Widgets/StudentTasks.php
  app-modules/student-data-model/src/Filament/Widgets/StudentsActionCenterWidget.php
  app-modules/task/src/Filament/Widgets/TasksWidget.php
  resources/css/filament/admin/theme.css
Labels: Change Type | New Feature

#1485 [ADVAPP-1435]: Upgrade Eloquent Power Joins package to fix PHP warnings being reported in production
  app-modules/case-management/src/Models/CaseModel.php
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#1484 [ADVAPP-1423]: Optimize per page display options for list views
  app/Providers/AppServiceProvider.php
Labels: Change Type | Content or Styling Update

#1478 [ADVAPP-1399]: Add a segmentation rule to allow institutions to select students by gender
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
  app/Filament/Tables/Filters/QueryBuilder/Constraints/ExistingValuesSelectConstraint.php
Labels: Change Type | New Feature

#1482 [ADVAPP-1413]: Feature Flag Cleanup: EngagementResponseStatusFeature
  app-modules/engagement/database/migrations/2025_04_22_095041_data_activate_engagement_response_status_feature.php
  app-modules/engagement/src/Actions/CreateEngagementResponse.php
  app-modules/engagement/src/Jobs/ProcessSesS3InboundEmail.php
  app-modules/engagement/src/Notifications/EngagementNotification.php
  app-modules/student-data-model/resources/views/components/filament/resources/educatable-resource/view-educatable/engagement-modal-header.blade.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
  app/Features/EngagementResponseStatusFeature.php
Labels: Change Type | Feature Cleanup

#1467 [ADVAPP-1397]: Update the iconography in message center to use the standard icons for email or text messages regardless of direction
  app-modules/timeline/src/Timelines/EngagementResponseTimeline.php
  app-modules/timeline/src/Timelines/EngagementTimeline.php
Labels: Change Type | Documentation

#1483 [ADVAPP-1425]: Improve consistency in the display of the student hyperlink
  app-modules/engagement/resources/views/components/message-center-content.blade.php
Labels: Change Type | Content or Styling Update

#1496 [ADVAPP-1412]: Some jobs that fail to suceed are not being reported to centralized error reporting system
  app-modules/engagement/src/Jobs/ProcessSesS3InboundEmail.php
  app-modules/engagement/src/Notifications/EngagementNotification.php
Labels: Change Type | Bug Fix

#1497 [ADVAPP-1420]: Resolve the security issue tracked under CVE-2025-22871
  package-lock.json
Labels: Change Type | Dependencies

#1486 [ADVAPP-1352]: Update enrollment view in the holistic student profile to show the course name, course, section, grade, and semester name
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EnrollmentsRelationManager.php
Labels: Change Type | Documentation

#1491 [ADVAPP-1422]: Introduce the ability to duplicate roles
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ListRoles.php
Labels: Change Type | New Feature

#1493 [ADVAPP-1417]: Introduce an about link in the profile dropdown that displays the product's version information
  app/Providers/Filament/AdminPanelProvider.php
  resources/views/components/about-modal.blade.php
Labels: Change Type | New Feature
