Repository canyongbs/advisingapp, pull requests merged in 2025-05, with the labels that each got.

#1506 [ADVAPP-1467] & [ADVAPP-1468] & [ADVAPP-1469]
  app-modules/campaign/src/Filament/Blocks/TagsBlock.php
  app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
  app-modules/engagement/src/Models/Engagement.php
  app/Filament/Tables/Filters/QueryBuilder/Constraints/ExistingValuesSelectConstraint.php
Labels: Change Type | Bug Fix

#1500 [ADVAPP-1448]: Improve the experience when creating a new campaign by providing a confirmation modal
  app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php
Labels: Change Type | New Feature

#1507 [ADVAPP-1459]: Optimize implementation of new large language models based on prior release
  app-modules/ai/database/migrations/2025_04_24_064213_data_activate_gpt_41_mini_and_41_nano_feature.php
  app-modules/ai/src/Enums/AiApplication.php
  app-modules/ai/src/Enums/AiModel.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app/Features/GPT41MiniAnd41NanoFeature.php
Labels: Change Type | Feature Cleanup

#1513 [ADVAPP-1464]: Update the navigation menu in Global Administration to reflect the updated naming for AI features
  app-modules/ai/src/Filament/Pages/ManageAiIntegratedAssistantSettings.php
  app-modules/ai/src/Filament/Pages/ManageAiSettings.php
Labels: Change Type | Content or Styling Update

#1514 [ADVAPP-1432]: Align terminology by consistently using "Journey Steps" when managing Campaigns
  app-modules/campaign/src/Filament/Resources/CampaignResource/RelationManagers/CampaignActionsRelationManager.php
  app-modules/campaign/src/Policies/CampaignActionPolicy.php
Labels: Change Type | Bug Fix

#1511 [ADVAPP-1461]: Improve the language used on the duplicate role modal overlay
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ListRoles.php
Labels: Change Type | Content or Styling Update

#1509 [ADVAPP-1465]: Update the labeling of feature capabilities to be consistent for custom advisors
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
Labels: Change Type | Content or Styling Update

#1510 [ADVAPP-1463]: Introduce the ability to configure a large language model name throughout the application
  app-modules/ai/database/migrations/2025_05_02_162717_add_ai_integration_settings_model_name_settings.php
  app-modules/ai/src/Enums/AiModel.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app-modules/ai/src/Settings/AiIntegrationsSettings.php
Labels: Change Type | New Feature

#1518 [ADVAPP-1475]: Error thrown in campaigns caused by change of User / Team relationship
  app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/CreateCampaign.php
  app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/EditCampaign.php
Labels: Change Type | Bug Fix

#1517 [ADVAPP-1449]: Introduce support for the latest reasoning large language model to extend the capabilities of our artificial intelligence features
  .env.example
  app-modules/ai/database/migrations/2025_05_06_061948_add_open_ai_gpt_o4_mini_settings.php
  app-modules/ai/database/migrations/2025_05_06_105028_data_activate_gpt_o4_mini_feature.php
  app-modules/ai/src/Enums/AiModel.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Concerns/HandlesFileUploads.php
  app-modules/ai/src/Settings/AiIntegrationsSettings.php
  app-modules/integration-open-ai/config/integration-open-ai.php
  app-modules/integration-open-ai/src/Services/OpenAiGptO4MiniService.php
  app/Features/GPTO4MiniFeature.php
Labels: Change Type | New Feature, Feature Flag Added

#1519 [ADVAPP-1421]: Some users are reporting that campaigns involving care team journey steps are not always resulting in care team members being added to prospect and student records
  app-modules/campaign/src/Actions/ExecuteCampaignAction.php
Labels: Change Type | Bug Fix

#1523 [ADVAPP-1450] - Add Research Assistant to Filament Pages
  app-modules/ai/database/migrations/2025_05_07_051054_add_jina_deepsearch_ai_settings.php
  app-modules/ai/database/migrations/2025_05_07_164906_add_ai_research_assistant_settings.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app-modules/ai/src/Filament/Pages/ManageResearchAssistantSettings.php
  app-modules/ai/src/Settings/AiIntegrationsSettings.php
  app-modules/ai/src/Settings/AiResearchAssistantSettings.php
Labels: Change Type | New Feature

#1526 [Bugfix] Docker build fixes
  Dockerfile
Labels: Change Type | Bug Fix

#1532 [ADVAPP-1483]: Remove the PHP package spatie/laravel-ignition
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#1530 [ADVAPP-1479]: Feature Flag Cleanup: GPTO4MiniFeature
  app-modules/ai/database/migrations/2025_05_06_105028_data_activate_gpt_o4_mini_feature.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app/Features/GPTO4MiniFeature.php
Labels: Change Type | Feature Cleanup

#1529 [ADVAPP-1474]: Data Migration cleanup: 2025_04_30_201831_tmp_data_migrate_team_user_id_to_user_table
  database/migrations/2025_04_30_200449_tmp_data_migrate_team_user_id_to_user_table.php
Labels: Change Type | Feature Cleanup

#1528 [ADVAPP-1485]: Relocate gender after the separator and before ethnicity
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
Labels: Change Type | Content or Styling Update

#1476 [ADVAPP-1404]: Email formatting does not appear consistently across messages and email views
  app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/view-educatable-activity-feed.blade.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
  app-modules/timeline/resources/views/components/timeline.blade.php
  app-modules/timeline/src/Timelines/EngagementTimeline.php
  app/Infolists/Components/EngagementBody.php
  composer.json
  composer.lock
  resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php
  resources/views/infolists/components/engagement-body.blade.php
  resources/views/vendor/mail/html/themes/default.css
Labels: Change Type | Bug Fix, Change Type | Content or Styling Update

#1533 [ADVAPP-1409]: Display the Primary email and phone number on the student profile
  app-modules/student-data-model/resources/views/components/filament/resources/educatable-resource/view-educatable/email-address-detail.blade.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
Labels: Change Type | Content or Styling Update

#1537 [ADVAPP-1491]: Feature Flag Cleanup: EmailSignature
  app/Features/EmailSignature.php
  app/Filament/Pages/EditProfile.php
  database/migrations/2025_03_17_112122_data_activate_feature_flag_email_signature.php
Labels: Change Type | Feature Cleanup

#1539 [ADVAPP-1414]: Improve user experience by simplifying the process of setting up working hours in user profile by reducing repetitive typing and clicks
  app/Filament/Pages/EditProfile.php
  resources/css/filament/admin/theme.css
Labels: Change Type | New Feature

#1538 [ADVAPP-1490]: Feature Flag Cleanup: RefactorEngagementCampaignSubjectToJsonb
  _ide_helper_models.php
  app-modules/campaign/src/Filament/Blocks/EngagementBatchEmailBlock.php
  app-modules/engagement/database/migrations/2025_04_17_142824_data_migration_refactor_engagement_subject_to_jsonb.php
  app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
  app-modules/engagement/src/Actions/GenerateEngagementSubjectContent.php
  app-modules/engagement/src/DataTransferObjects/EngagementCreationData.php
  app-modules/engagement/src/Filament/Actions/BulkEngagementAction.php
  app-modules/engagement/src/Filament/Actions/RelationManagerSendEngagementAction.php
  app-modules/engagement/src/Filament/Actions/SendEngagementAction.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/engagement/src/Models/EngagementBatch.php
  app-modules/engagement/src/Notifications/EngagementFailedNotification.php
  app-modules/engagement/src/Notifications/EngagementNotification.php
  app-modules/form/src/Filament/Resources/FormResource/Pages/ManageFormEmailAutoReply.php
  app-modules/form/src/Models/FormEmailAutoReply.php
  app-modules/form/src/Notifications/FormSubmissionAutoReplyNotification.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Widgets/EducatableActivityFeedWidget.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
  app-modules/timeline/src/Timelines/EngagementTimeline.php
  app/Features/RefactorEngagementCampaignSubjectToJsonb.php
  resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php
Labels: Change Type | Feature Cleanup

#1547 [ADVAPP-1509]: Some users have reported that they are seeing unexpected cumulative visualizations in the student and prospect overview report
  app-modules/report/src/Filament/Widgets/ProspectReportLineChart.php
  app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php
Labels: Change Type | Content or Styling Update

#1545 [ADVAPP-1504]: Introduce the ability to create a segment based on the first enrolled semester for a student
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
  app/Filament/Tables/Filters/QueryBuilder/Constraints/ExistingValuesSelectConstraint.php
Labels: Change Type | New Feature

#1546 [ADVAPP-1505]: Introduce the ability to create a segment based on the most recent enrolled semester or a student
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
Labels: Change Type | New Feature

#1556 [ADVAPP-1445]: Some users are reporting that the "Related To" field is required to create a case, but it does not have a visual indicator to show that it is required
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#1557 [ADVAPP-1502]: Some users experience an issue when viewing some headings on an engagement (email) in-product when the dark theme is enabled
  app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
  resources/views/filament/forms/components/campaigns/actions/bulk-engagement.blade.php
  resources/views/infolists/components/engagement-body.blade.php
Labels: Change Type | Bug Fix

#1561 [ADVAPP-1537]: Not having a primary phone or email results in errors thrown on Student records
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
Labels: Change Type | Bug Fix

#1562 [Hotfix]: 1.68.1
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
Labels: Change Type | Bug Fix

#1553 [ADVAPP-1496]: Ensure all usage of Cache::tags apply Redis "hash tags" to the tag
  app-modules/alert/src/Observers/AlertObserver.php
  app-modules/application/src/Observers/ApplicationSubmissionObserver.php
  app-modules/form/src/Filament/Resources/FormResource/Pages/ManageFormSubmissions.php
  app-modules/form/src/Listeners/ClearAuthorFormSubmissionCountCache.php
  app-modules/form/src/Listeners/ClearFormFormSubmissionCountCache.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
  app-modules/prospect/src/Observers/ProspectObserver.php
  app-modules/report/src/Filament/Widgets/AiStats.php
  app-modules/report/src/Filament/Widgets/ExchangesByMonthLineChart.php
  app-modules/report/src/Filament/Widgets/PromptsByCategoryDoughnutChart.php
  app-modules/report/src/Filament/Widgets/PromptsCreatedLineChart.php
  app-modules/report/src/Filament/Widgets/ProspectEngagementLineChart.php
  app-modules/report/src/Filament/Widgets/ProspectEngagementState.php
  app-modules/report/src/Filament/Widgets/ProspectReportLineChart.php
  app-modules/report/src/Filament/Widgets/ProspectReportStats.php
  app-modules/report/src/Filament/Widgets/RefreshWidget.php
  app-modules/report/src/Filament/Widgets/SpecialActionsDoughnutChart.php
  app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php
  app-modules/report/src/Filament/Widgets/StudentEmailOptInOptOutPieChart.php
  app-modules/report/src/Filament/Widgets/StudentEngagementLineChart.php
  app-modules/report/src/Filament/Widgets/StudentEngagementStats.php
  app-modules/report/src/Filament/Widgets/StudentSmsOptInOptOutPieChart.php
  app-modules/report/src/Filament/Widgets/StudentsStats.php
  app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php
  app-modules/report/src/Filament/Widgets/TaskStats.php
  app-modules/report/src/Filament/Widgets/UserUniqueLoginCountLineChart.php
  app-modules/report/src/Filament/Widgets/UsersStats.php
  app/Filament/Widgets/ProspectGrowthChart.php
Labels: Change Type | Content or Styling Update

#1560 [ADVAPP-1487]: AAn error is thrown to Sentry if an Azure SSO login does not have a profile photo
  app-modules/authorization/src/Http/Controllers/SocialiteController.php
Labels: Change Type | Bug Fix

#1571 [ADVAPP-1541]: Single or bulk Engagement body saves as an empty array Tests
  app-modules/engagement/tests/Tenant/Filament/Actions/BulkEngagementActionTest.php
  app-modules/engagement/tests/Tenant/Filament/Actions/RelationManagerSendEngagementActionTest.php
  app-modules/engagement/tests/Tenant/Filament/Actions/SendEngagementActionTest.php
  database/factories/UserFactory.php
Labels: Change Type | Bug Fix

#1567 [ADVAPP-1531], [ADVAPP-1533] & [ADVAPP-1534]: Enhance the presentation of references in the Research Advisor, Enhance the approach the Research Advisor takes by increasing dependency on academically valid sources, and Enhance research advisor process for chain-of-thought prompt engineering
  app-modules/research/resources/views/results.blade.php
  app-modules/research/src/Actions/GenerateResearchQuestion.php
  app-modules/research/src/Jobs/Research.php
Labels: Change Type | Bug Fix

#1564 [ADVAPP-1407]: Sentry has detected an issue when attempting to send an engagement if the recipient is no longer available
  app-modules/engagement/src/Console/Commands/DeliverEngagements.php
  app-modules/engagement/src/Jobs/DeliverEngagements.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/notification/src/Notifications/Channels/MailChannel.php
  app-modules/notification/src/Notifications/Channels/SmsChannel.php
Labels: Change Type | Bug Fix

#1577 [ADVAPP-1561]: Recent changes to Engagement subject and body generation throw errors
  app-modules/engagement/src/Models/Engagement.php
Labels: Change Type | Bug Fix
