Repository canyongbs/advisingapp, pull requests merged in 2025-03, with the labels that each got.

#1338 [ADVAPP-1217]: Resolve the security issue tracked under CVE-2021-44906
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#1339 [Hotfix]: 1.55.1
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#1307 [ADVAPP-1190]: Presentation of birthdates after CSV upload for students presents as a day earlier than expected
  app/Providers/FilamentServiceProvider.php
Labels: Change Type | Content or Styling Update

#1341 [ADVAPP-1252]: Feature Flag Cleanup: PipelineFlag
  app-modules/prospect/database/migrations/2024_11_07_120145_data_activate_pipeline_feature_flag.php
  app-modules/prospect/src/Filament/Pages/ManageProspectPipelineSettings.php
  app-modules/prospect/src/Filament/Resources/PipelineResource.php
  app/Features/PipelineFlag.php
Labels: Change Type | Feature Cleanup

#1342 [ADVAPP-1245]: Feature Flag Cleanup: GenerateProspectFeature
  app-modules/form/database/migrations/2024_11_12_053304_data_activate_feature_flag_generate_prospect.php
  app-modules/form/src/Filament/Resources/FormResource/Pages/Concerns/HasSharedFormConfiguration.php
  app-modules/form/src/Http/Controllers/FormWidgetController.php
  app/Features/GenerateProspectFeature.php
Labels: Change Type | Feature Cleanup

#1335 [ADVAPP-1246]: Portal and widget stylesheets not generating properly
  portals/resource-hub/vite.config.js
  widgets/application/vite.config.js
  widgets/case-feedback-form/vite.config.js
  widgets/case-form/vite.config.js
  widgets/event-registration/vite.config.js
  widgets/form/vite.config.js
  widgets/survey/vite.config.js
Labels: Change Type | Bug Fix

#1337 [ADVAPP-1210]: Add validation to User Role attach Action to prevent a non-admin from attaching Super Admin as a Role
  app-modules/authorization/tests/Tenant/Feature/Filament/Resources/User/EditUserTest.php
  app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
  app/Rules/ExcludeSuperAdmin.php
  tests/Tenant/Feature/Filament/UserResource/RelationManagers/RolesRelationManagerTest.php
Labels: Change Type | New Feature

#1344 [ADVAPP-1253]: Feature Flag Cleanup: TwilioDemoAutoReplyModeFeature
  app-modules/integration-twilio/database/migrations/2024_11_28_151640_data_activate_twilio_demo_auto_reply_mode_feature.php
  app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
  app/Features/TwilioDemoAutoReplyModeFeature.php
Labels: Change Type | Feature Cleanup

#1345 [ADVAPP-1250]: Feature Flag Cleanup: AddCreatedByFeature
  app-modules/campaign/database/migrations/2024_11_20_092836_data_activate_feature_flag_created_by_campaign.php
  app-modules/campaign/src/Filament/Resources/CampaignResource/Pages/ViewCampaign.php
  app/Features/AddCreatedByFeature.php
Labels: Change Type | Feature Cleanup

#1346 [ADVAPP-1256]: Improve tracking of student and prospect import job batches
  app-modules/prospect/src/Imports/ProspectImporter.php
  app-modules/student-data-model/src/Filament/Imports/StudentImporter.php
Labels: Change Type | Chore

#1347 [ADVAPP-1226] Install canyongbs/common and use the PermissionsMatrix
  app-modules/authorization/src/Exceptions/NonUuidPermissionIdFound.php
  app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/CreateRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/EditRole.php
  app-modules/authorization/src/Filament/Resources/RoleResource/Pages/ViewRole.php
  composer.json
  composer.lock
  tailwind.config.js
Labels: Change Type | Dependencies

#1336 [ADVAPP-1247]: Update composer package for minor update
  composer.lock
Labels: Change Type | Dependencies

#1343 [ADVAPP-1215] When a user is deleted, automatically remove any licenses activated and detach any roles assigned to that user
  app/Models/User.php
  app/Observers/UserObserver.php
  database/migrations/2025_03_04_230535_data_remove_licenses_from_soft_deleted_users.php
Labels: Change Type | New Feature

#1350 [ADVAPP-1219]: Alert creation for students or prospects fails when status is not manually set
  app-modules/alert/src/Filament/Resources/AlertResource/Pages/ListAlerts.php
  app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ManageProspectAlerts.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableAlerts.php
Labels: Change Type | Bug Fix

#1349 [ADVAPP-1124]: Exceptions are thrown when login Azure profile image cannot be found
  app-modules/authorization/src/Http/Controllers/SocialiteController.php
Labels: Change Type | Bug Fix

#1352 [ADVAPP-1188]: Some tenants seem to be receiving unexpected notifications related to erroneous care team assignments
  app-modules/campaign/src/Actions/ExecuteCampaignActions.php
  app-modules/care-team/src/Observers/CareTeamObserver.php
Labels: Change Type | Bug Fix

#1355 [ADVAPP-1265]: Resolve the security issue tracked under CVE-2025-27517
  composer.json
  composer.lock
Labels: Change Type | Dependencies

#1353 [ADVAPP-1233]: Standardize import button labels across student profile, prospects, tasks, and users
  resources/lang/vendor/filament-actions/en/import.php
Labels: Change Type | Content or Styling Update

#1365 [ADVAPP-1268]: Fix issue with student and prospect edit button being displayed at the wrong time, which links to a forbidden page error
  app-modules/prospect/src/Filament/Resources/ProspectResource/Schemas/ProspectProfileInfolist.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#1356 [ADVAPP-1220]: When attempting to add a proactive alert campaign journey step, an error is generated
  app-modules/alert/src/Models/Alert.php
  app-modules/campaign/tests/Tenant/Actions/ProactiveAlertsCampaignTest.php
Labels: Change Type | Bug Fix

#1354 [ADVAPP-1259]: Remove unnecessary information about the delivery channel from the display of email messages sent to students or prospects
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
Labels: Change Type | Content or Styling Update

#1357 [ADVAPP-1234]: Improve the reset password styling to match the revised login screen design
  app-modules/authorization/resources/views/login.blade.php
  app-modules/authorization/src/Filament/Pages/Auth/Login.php
  resources/views/vendor/filament-panels/components/layout/simple.blade.php
  resources/views/vendor/filament-panels/components/page/simple.blade.php
Labels: Change Type | Content or Styling Update

#1359 [ADVAPP-1224]: In the "Students (Overview)" report, if the number of students exceeds 99 million a display issue presents to end users
  app-modules/prospect/src/Filament/Widgets/ProspectStats.php
  app-modules/report/src/Filament/Widgets/ProspectReportStats.php
  app-modules/report/src/Filament/Widgets/StudentsStats.php
  app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#1370 [ADVAPP-1149]: Refine legacy integration settings in the interface that are related to email
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-aws-ses-event-handling/tests/Tenant/Feature/Filament/Pages/ManageAmazonSesSettingsTest.php
  app/Console/Commands/CreateTenant.php
  app/Http/Controllers/Tenants/CreateTenantController.php
  app/Multitenancy/DataTransferObjects/TenantMailConfig.php
  app/Multitenancy/DataTransferObjects/TenantMailersConfig.php
  app/Multitenancy/Tasks/SwitchMailTask.php
  database/factories/TenantFactory.php
  database/migrations/2025_03_12_151307_tmp_data_remove_mailers_configuration_from_tenant_config.php
  tests/Tenant/Feature/Multitenancy/Tasks/SwitchMailTaskTest.php
  tests/TestCase.php
Labels: Change Type | New Feature

#1367 [ADVAPP-1220]: When attempting to add a proactive alert campaign journey step, an error is generated
  resources/views/filament/forms/components/campaigns/actions/proactive-alert.blade.php
Labels: Change Type | Bug Fix

#1369 [ADVAPP-1271]: Add support for email and sms usage to Advising App Olympus stats API endpoint
  app/Http/Controllers/UtilizationMetricsApiController.php
Labels: Change Type | Content or Styling Update

#1372 [ADVAPP-921] Enforce our styling consistently in the underlying codebase
  composer.json
Labels: Change Type | Content or Styling Update

#1375 [ADVAPP-1274]: Feature Flag Cleanup: O1MiniAndO3MiniFeature
  app-modules/ai/database/migrations/2025_03_12_183223_data_activate_o1_mini_and_o3_mini_feature.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app/Features/O1MiniAndO3MiniFeature.php
Labels: Change Type | Feature Cleanup

#1380 [ADVAPP-1272]: Feature Flag Cleanup: LocalPassword
  app-modules/authorization/src/Filament/Pages/ManageLocalPasswordSettings.php
  app/Features/LocalPassword.php
  app/Observers/UserObserver.php
  database/migrations/2025_03_11_142825_data_activate_feature_flag_local_password.php
Labels: Change Type | Feature Cleanup

#1378 [ADVAPP-1279]: Enhance the email system by adding merge values, allowing users to insert their personal information into outgoing messages
  app-modules/engagement/src/Filament/Actions/MessageCenterSendEngagementAction.php
  app-modules/engagement/src/Filament/Actions/RelationManagerSendEngagementAction.php
  app-modules/engagement/src/Models/Engagement.php
  composer.json
  composer.lock
Labels: Change Type | New Feature

#1382 [ADVAPP-1267]: Clean up prospect and students emails, phone numbers and addresses refactor
  _ide_helper_models.php
  app-modules/engagement/src/Actions/FindEngagementResponseSender.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/form/src/Actions/ResolveSubmissionAuthorFromEmail.php
  app-modules/form/src/Http/Controllers/FormWidgetController.php
  app-modules/form/src/Http/Requests/RegisterProspectRequest.php
  app-modules/form/src/Models/FormEmailAutoReply.php
  app-modules/integration-twilio/src/Actions/Playground/FindEngagementResponseSender.php
  app-modules/integration-twilio/tests/Tenant/Feature/Actions/MessageReceivedTest.php
  app-modules/interaction/src/Imports/InteractionsImporter.php
  app-modules/notification/src/Models/Concerns/NotifiableViaSms.php
  app-modules/prospect/database/migrations/2025_02_10_085601_data_migration_email_mobile_from_prospects_to_prospect_email_addresses_and_phone_table.php
  app-modules/prospect/database/migrations/2025_02_10_085601_remove_unused_email_phone_and_address_columns_from_prospects_table.php
  app-modules/prospect/database/migrations/2025_03_05_130336_data_cancel_prospect_imports.php
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/Concerns/HasProspectHeader.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Schemas/ProspectProfileInfolist.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Tables/ProspectsTable.php
  app-modules/prospect/src/Imports/ProspectImporter.php
  app-modules/prospect/src/Models/Prospect.php
  app-modules/report/src/Filament/Exports/ProspectExporter.php
  app-modules/report/src/Filament/Exports/StudentExporter.php
  app-modules/segment/src/Importers/ProspectSegmentSubjectImporter.php
  app-modules/student-data-model/database/migrations/2025_02_10_170154_data_migration_email_mobile_from_students_to_student_email_addresses_and_phone_table.php
  app-modules/student-data-model/database/migrations/2025_02_10_170154_remove_unused_email_phone_and_address_columns_from_students_table.php
  app-modules/student-data-model/database/migrations/2025_03_05_130255_data_cancel_student_imports.php
  app-modules/student-data-model/src/Actions/FinalizeStudentDataImport.php
  app-modules/student-data-model/src/Actions/ResolveEducatableFromEmail.php
  app-modules/student-data-model/src/Filament/Actions/ImportStudentDataAction.php
  app-modules/student-data-model/src/Filament/Imports/StudentImporter.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/Concerns/HasStudentHeader.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
  app-modules/student-data-model/src/Models/Student.php
  app-modules/task/src/Imports/TaskImporter.php
  app/Filament/Widgets/RecentProspectsList.php
Labels: Change Type | Feature Cleanup

#1383 [ADVAPP-1263]: When attempting to delete interaction in bulk, it generates an error
  app-modules/interaction/database/migrations/2025_03_17_170737_update_unique_key_in_interaction_outcomes_table.php
  app-modules/interaction/database/migrations/2025_03_18_181259_update_unique_key_in_interaction_relations_table.php
  app-modules/interaction/database/migrations/2025_03_18_181747_update_unique_key_in_interaction_statuses_table.php
Labels: Change Type | Bug Fix

#1381 [ADVAPP-1280]: Enable creation and storage of customizable email signatures with text and image support for messaging
  app/Features/EmailSignature.php
  app/Filament/Pages/EditProfile.php
  app/Models/User.php
  config/filament-tiptap-editor.php
  database/migrations/2025_03_17_072936_add_signature_columns_to_users_table.php
  database/migrations/2025_03_17_112122_data_activate_feature_flag_email_signature.php
Labels: Change Type | New Feature, Feature Flag Added

#1386 [ADVAPP-1015]: Upgrade to Larastan 3.0 and PHPStan 2.0
  composer.json
  composer.lock
  phpstan.neon.dist
Labels: Change Type | Chore

#1387 [ADVAPP-1284]: Enable the usage of stored customizable signatures in sending of Engagements
  app-modules/engagement/src/Filament/Actions/MessageCenterSendEngagementAction.php
  app-modules/engagement/src/Filament/Actions/RelationManagerSendEngagementAction.php
  app/Filament/Pages/EditProfile.php
  app/Models/User.php
  docker-compose.dev.yml
Labels: Change Type | New Feature

#1389 [ADVAPP-1281]: Azure profile image retrieval failures are generating exceptions
  app-modules/authorization/src/Http/Controllers/SocialiteController.php
Labels: Change Type | Bug Fix

#1390 [ADVAPP-1275]: Normalize permissions related to realtime chat for the role matrix
  app-modules/in-app-communication/database/migrations/2025_03_20_125908_data_remove_realtime_chat_api_permission.php
Labels: Change Type | Bug Fix

#1391 [ADVAPP-1293]: Feature Flag Cleanup: StudentDataImportTrackingFeature
  app-modules/student-data-model/database/migrations/2025_03_19_172122_data_activate_student_data_import_tracking_feature.php
  app-modules/student-data-model/src/Actions/FinalizeStudentDataImport.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentSyncs.php
  app-modules/student-data-model/src/Jobs/PrepareStudentDataCsvImport.php
  app/Features/StudentDataImportTrackingFeature.php
Labels: Change Type | Feature Cleanup

#1385 [ADVAPP-1249]: Ensure that the product is able to successfully route incoming SMS messages to the appropriate prospect or student by matching the numbers correctly regardless of their format
  app-modules/basic-needs/database/factories/BasicNeedsProgramFactory.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource/Pages/CreateBasicNeedsProgram.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource/Pages/EditBasicNeedsProgram.php
  app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php
  app-modules/prospect/database/factories/ProspectFactory.php
  app-modules/prospect/src/Imports/ProspectImporter.php
  app-modules/student-data-model/database/factories/StudentFactory.php
  app-modules/student-data-model/src/Filament/Imports/StudentPhoneNumberImporter.php
  app/Filament/Pages/EditProfile.php
Labels: Change Type | New Feature

#1399 [ADVAPP-1301]: Selecting a conversation within message center throws error.
  app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
Labels: Change Type | Bug Fix

#1401 [ADVAPP-1316]: Create schedule monitor tables on tenant
  app/Models/MonitoredScheduledTask.php
  app/Models/MonitoredScheduledTaskLogItem.php
Labels: Change Type | Bug Fix

#1404 [ADVAPP-1315]: CSV extract examples for record sync fail to download
  app-modules/student-data-model/src/Filament/Actions/ImportStudentDataAction.php
Labels: Change Type | Bug Fix

#1406 [ADVAPP-1306]: Enhance segmentation of prospects by targeting subscribed prospects
  app-modules/prospect/src/Filament/Resources/ProspectResource/Tables/ProspectsTable.php
Labels: Change Type | New Feature

#1409 [ADVAPP-1307]: Enhance segmentation options for buidling prospect segments to include support for targeting engagement deliverability
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
Labels: Change Type | New Feature

#1410 [ADVAPP-1308]: Add interactions added within a case to the case timeline in a similar fashion to how interactions outside of a case are added to a holistic profile timeline
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/CaseTimeline.php
Labels: Change Type | Bug Fix
