Repository canyongbs/advisingapp, pull requests merged in 2025-01, with the labels that each got.

#1217 [ADVAPP-1088]: Rename permission group in permissions for Resource Hub
  app-modules/resource-hub/database/migrations/2024_12_30_153854_data_rename_knowledge_base_article_permission_group_to_resource_hub_article.php
Labels: Change Type | Bug Fix

#1218 [ADVAPP-1095]: Engagement Refactor Cleanup
  app-modules/engagement/database/migrations/2024_12_16_201140_data_clear_out_outbound_deliverables_for_engagement_deliverables.php
  app-modules/engagement/database/migrations/2024_12_16_201142_data_truncate_engagements_table.php
  app-modules/engagement/database/migrations/2024_12_27_002830_purge_timeline_items_related_to_enagements.php
  app-modules/engagement/database/migrations/2024_12_27_010201_purge_timeline_items_related_to_enagements_correctly.php
Labels: Change Type | Feature Cleanup

#1207 [ADVAPP-1076] Include "Cases" in top menu bar after interactions for students and prospects
  app-modules/case-management/resources/views/filament/resources/case-resource/view-case/header.blade.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/Concerns/HasCaseHeader.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ViewCase.php
  app-modules/prospect/resources/views/filament/resources/prospect-resource/view-prospect.blade.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/CasesRelationManager.php
  app-modules/student-data-model/resources/views/filament/resources/student-resource/view-student.blade.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/CasesRelationManager.php
Labels: Change Type | Content or Styling Update

#1222 [ADVAPP-1091]: Legacy change management configuration options are showing up unexpectedly under service management
  _ide_helper_models.php
  app-modules/case-management/database/factories/ChangeRequestFactory.php
  app-modules/case-management/database/factories/ChangeRequestResponseFactory.php
  app-modules/case-management/database/factories/ChangeRequestStatusFactory.php
  app-modules/case-management/database/factories/ChangeRequestTypeFactory.php
  app-modules/case-management/database/seeders/ChangeRequestStatusSeeder.php
  app-modules/case-management/database/seeders/ChangeRequestTypeSeeder.php
  app-modules/case-management/src/Enums/SystemChangeRequestClassification.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestResource.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestResource/Pages/CreateChangeRequest.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestResource/Pages/EditChangeRequest.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestResource/Pages/ListChangeRequests.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestResource/Pages/ViewChangeRequest.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestStatusResource.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestStatusResource/Pages/CreateChangeRequestStatus.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestStatusResource/Pages/EditChangeRequestStatus.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestStatusResource/Pages/ListChangeRequestStatuses.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestStatusResource/Pages/ViewChangeRequestStatus.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestTypeResource.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestTypeResource/Pages/CreateChangeRequestType.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestTypeResource/Pages/EditChangeRequestType.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestTypeResource/Pages/ListChangeRequestTypes.php
  app-modules/case-management/src/Filament/Resources/ChangeRequestTypeResource/Pages/ViewChangeRequestType.php
  app-modules/case-management/src/Models/ChangeRequest.php
  app-modules/case-management/src/Models/ChangeRequestResponse.php
  app-modules/case-management/src/Models/ChangeRequestStatus.php
  app-modules/case-management/src/Models/Scopes/ClassifiedAs.php
  app-modules/case-management/src/Notifications/ChangeRequestAwaitingApprovalNotification.php
  app-modules/case-management/src/Policies/ChangeRequestPolicy.php
  app-modules/case-management/src/Policies/ChangeRequestStatusPolicy.php
  app-modules/case-management/src/Policies/ChangeRequestTypePolicy.php
  app-modules/case-management/src/Providers/CaseManagementServiceProvider.php
  app-modules/case-management/tests/ChangeRequest/ListChangeRequestTest.php
  app-modules/case-management/tests/ChangeRequestType/ListChangeRequestTypeTest.php
  app/Models/User.php
  database/migrations/2025_01_02_190909_drop_change_request_type_user_table.php
  database/migrations/2025_01_02_191034_drop_change_request_responses_table.php
  database/migrations/2025_01_02_192140_drop_change_requests_table.php
  database/migrations/2025_01_02_192420_drop_change_request_types_table.php
  database/migrations/2025_01_02_192519_drop_change_request_statuses_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/NewTenantSeeder.php
  resources/views/filament/forms/components/change-request/calculated-risk-score.blade.php
  resources/views/filament/infolists/components/change-request/risk-score.blade.php
  resources/views/filament/tables/columns/change-request/risk-score.blade.php
Labels: Change Type | Feature Cleanup

#1216 [ADVAPP-1075]: Relocate Case Management from Premium Features to Engagement Features
  app-modules/campaign/src/Filament/Resources/CampaignResource.php
  app-modules/segment/src/Filament/Resources/SegmentResource.php
  app-modules/task/src/Filament/Resources/TaskResource.php
  app/Filament/Clusters/CaseManagementAdministration.php
Labels: Change Type | Documentation

#1223 [ADVAPP-1098]: Feature Flag Cleanup: AzureMatchingPropertyFeature
  app-modules/authorization/database/migrations/2024_12_30_144224_data_activate_azure_matching_property_feature.php
  app-modules/authorization/src/Enums/SocialiteProvider.php
  app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
  app/Features/AzureMatchingPropertyFeature.php
Labels: Change Type | Feature Cleanup

#1224 [ADVAPP-1106]: Prevent an error from being thrown for a User if a non-UUID value is passed into the permission sync
  app-modules/authorization/src/Exceptions/NonUuidPermissionIdFound.php
  app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php
Labels: Change Type | Bug Fix

#1227 [ADVAPP-1103]: Users are unable to edit tags on student profiles
  app-modules/student-data-model/database/migrations/2025_01_03_155805_seed_permissions_add_remaining_student_permissions.php
Labels: Change Type | Chore

#1226 [ADVAPP-1109]: The Case Management feature is currently listed in two locations within the product
  app/Filament/Clusters/CaseManagement.php
  app/Filament/Clusters/CaseManagementAdministration.php
Labels: Change Type | Bug Fix

#1230 [ADVAPP-1107]: Update the label used for the navigation group People Management to User Management
  app-modules/authorization/src/Filament/Resources/PermissionResource.php
  app-modules/authorization/src/Filament/Resources/RoleResource.php
  app-modules/division/src/Filament/Resources/DivisionResource.php
  app-modules/team/src/Filament/Resources/TeamResource.php
  app/Filament/Resources/SystemUserResource.php
  app/Filament/Resources/UserResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Documentation

#1228 [ADVAPP-1082]: Per Tenant from email configuration and setup
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app-modules/integration-aws-ses-event-handling/tests/Feature/Filament/Pages/ManageAmazonSesSettingsTest.php
  app/Console/Commands/CreateTenant.php
  app/Http/Controllers/Tenants/CreateTenantController.php
  app/Multitenancy/DataTransferObjects/TenantMailConfig.php
  app/Multitenancy/Tasks/SwitchMailTask.php
  config/mail.php
  database/factories/TenantFactory.php
  database/migrations/2025_01_06_205759_data_remove_tenant_config_from_address.php
  tests/Feature/Multitenancy/Tasks/SwitchMailTaskTest.php
  tests/TestCase.php
  tests/Unit/LicenseSettingsEmailQuotaTrackingTest.php
  tests/Unit/LicenseSettingsSmsQuotaTrackingTest.php
Labels: Change Type | New Feature

#1232 [ADVAPP-1100]: Organize list of attached permissions groups presented in the role editor in descending alphabetical order for view and edit experiences on save
  app-modules/authorization/resources/views/filament/forms/components/permissions-matrix.blade.php
Labels: Change Type | Content or Styling Update

#1229 [ADVAPP-1105]: Refactor the edit experience for students when manual student management is enabled
  app-modules/student-data-model/database/migrations/2025_01_06_190706_seed_permissions_add_remaining_enrollment_permissions.php
  app-modules/student-data-model/database/migrations/2025_01_06_190750_seed_permissions_add_remaining_program_permissions.php
  app-modules/student-data-model/src/Filament/Imports/EnrollmentImporter.php
  app-modules/student-data-model/src/Filament/Imports/ProgramImporter.php
  app-modules/student-data-model/src/Filament/Resources/ManageEnrollmentResource.php
  app-modules/student-data-model/src/Filament/Resources/ManageEnrollmentResource/Pages/ListManageEnrollments.php
  app-modules/student-data-model/src/Filament/Resources/ManageProgramResource.php
  app-modules/student-data-model/src/Filament/Resources/ManageProgramResource/Pages/ListManagePrograms.php
  app-modules/student-data-model/src/Filament/Resources/ManageStudentResource/Pages/ListManageStudents.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Actions/EditStudentAction.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/Concerns/HasStudentHeader.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EnrollmentsRelationManager.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/ProgramsRelationManager.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
  app-modules/student-data-model/src/Policies/EnrollmentPolicy.php
  app-modules/student-data-model/src/Policies/ProgramPolicy.php
  app-modules/student-data-model/src/Policies/StudentPolicy.php
  app-modules/student-data-model/tests/Student/ListStudentsTest.php
  app-modules/student-data-model/tests/Student/ViewStudentTest.php
  app-modules/student-data-model/tests/Unit/EnrollmentsRelationManagerTest.php
  app-modules/student-data-model/tests/Unit/ProgramsRelationManagerTest.php
Labels: Change Type | New Feature

#1235 [ADVAPP-1127]: Resolve the security issue tracked under CVE-2025-22145
  composer.lock
Labels: Change Type | Chore

#1237 [ADVAPP-1119]: Cleanup Data Migration: database/migrations/2025_01_06_205759_data_remove_tenant_config_from_address.php
  database/migrations/2025_01_06_205759_data_remove_tenant_config_from_address.php
Labels: Change Type | Feature Cleanup

#1239 [ADVAPP-1135]: Add team assignment to the view and edit pages for managing users
  app-modules/report/tests/Unit/UniqueLogin/UserStatsTest.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Filament/Resources/UserResource/Pages/ViewUser.php
Labels: Change Type | New Feature

#1241 [ADVAPP-1129]: Merge values do not show up when sending a message from the holistic student profile
  app-modules/authorization/src/Filament/Forms/Components/PermissionsMatrix.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
Labels: Change Type | Bug Fix

#1240 [ADVAPP-1118]: Feature Flag Cleanup: UserTrackedEventsFeature
  app-modules/report/database/migrations/2024_12_27_074457_data_activate_user_tracked_events_feature_flag.php
  app-modules/report/src/Abstract/UserReport.php
  app-modules/report/src/Listeners/ProcessUserUniqueLoginTrackedEvent.php
  app/Features/UserTrackedEventsFeature.php
Labels: Change Type | Feature Cleanup

#1243 [ADVAPP-1123]: Permission normalization errors
  database/migrations/2025_01_14_165537_data_fix_not_normalized_permissions.php
Labels: Change Type | Bug Fix

#1242 [ADVAPP-1133]: Enhance the management of the user list by adding a filter for created after
  app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: Change Type | New Feature

#1244 [ADVAPP-1132]: When attempting to create a custom report for Users an exception is generated
  app-modules/report/src/Enums/ReportModel.php
  app/Filament/Tables/UsersTable.php
Labels: Change Type | Bug Fix

#1247 [ADVAPP-1128]: The filter for In Progress displays as a typo in Tasks
  app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php
Labels: Change Type | Bug Fix

#1238 [ADVAPP-1137]: Update navigation experience for product features
  app-modules/alert/src/Filament/Resources/AlertResource.php
  app-modules/campaign/src/Filament/Resources/CampaignResource.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ListCases.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/engagement/src/Filament/Resources/EngagementFileResource.php
  app-modules/interaction/src/Filament/Resources/InteractionResource.php
  app-modules/report/src/Filament/Pages/TaskManagement.php
  app-modules/resource-hub/src/Filament/Resources/ResourceHubArticleResource.php
  app-modules/segment/src/Filament/Resources/SegmentResource.php
  app-modules/segment/src/Filament/Resources/SegmentResource/Pages/ListSegments.php
  app-modules/task/src/Filament/Resources/TaskResource.php
  app/Filament/Clusters/CaseManagement.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Documentation

#1246 [ADVAPP-1108]: When selecting a student's case, the 'back to student' option is not consistently displayed across all case-related pages
  app-modules/case-management/resources/views/filament/resources/case-resource/pages/record-header.blade.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/CaseTimeline.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/Concerns/HasCaseRecordHeader.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/EditCase.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ManageCaseAssignment.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ManageCaseFormSubmission.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ManageCaseInteraction.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ManageCaseUpdate.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ViewCase.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/CasesRelationManager.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/CasesRelationManager.php
Labels: Change Type | Bug Fix

#1254 [ADVAPP-1141]: Remove data migration: database/migrations/2025_01_14_165537_data_fix_not_normalized_permissions.php
  database/migrations/2025_01_14_165537_data_fix_not_normalized_permissions.php
Labels: Change Type | Feature Cleanup

#1248 [ADVAPP-1131]: When creating a campaign task due dates are being automatically added even if not populated when configuring the journey step
  app-modules/campaign/src/Filament/Blocks/CareTeamBlock.php
  app-modules/campaign/src/Filament/Blocks/EventBlock.php
  app-modules/campaign/src/Filament/Blocks/InteractionBlock.php
  app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
  app-modules/campaign/src/Filament/Blocks/SubscriptionBlock.php
  app-modules/campaign/src/Filament/Blocks/TaskBlock.php
  composer.lock
  package-lock.json
  resources/views/filament/forms/components/campaigns/actions/task.blade.php
Labels: Change Type | Bug Fix

#1249 [ADVAPP-1145]: Correct typo in spelling for new and edit forms for manually created students
  app-modules/student-data-model/src/Filament/Imports/StudentImporter.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Actions/EditStudentAction.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
Labels: Change Type | Bug Fix

#1253 [ADVAPP-1147]: Adjust display of fields for the program model
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/ProgramsRelationManager.php
Labels: Change Type | Content or Styling Update

#1252 [ADVAPP-1142]: Improve Product Administration display settings based on licensing restrictions
  app-modules/alert/src/Filament/Resources/AlertStatusResource.php
  app-modules/alert/src/Policies/AlertStatusPolicy.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsCategoryResource.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource.php
  app-modules/basic-needs/src/Policies/BasicNeedsCategoryPolicy.php
  app-modules/basic-needs/src/Policies/BasicNeedsProgramPolicy.php
  app-modules/engagement/src/Policies/EmailTemplatePolicy.php
  app-modules/engagement/src/Policies/SmsTemplatePolicy.php
  app-modules/prospect/src/Filament/Pages/ManageProspectConversionSettings.php
  app-modules/prospect/src/Filament/Pages/ManageProspectPipelineSettings.php
  app-modules/prospect/src/Filament/Resources/ProspectSourceResource.php
  app-modules/prospect/src/Filament/Resources/ProspectStatusResource.php
  app-modules/prospect/src/Filament/Resources/ProspectTagResource.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentConfiguration.php
  app-modules/student-data-model/src/Filament/Resources/StudentTagResource.php
Labels: Change Type | New Feature

#1251 [ADVAPP-1150]: Attempting to create a campaign journey step for a proactive alert generates an exception
  app-modules/campaign/src/Filament/Blocks/ProactiveAlertBlock.php
  resources/views/filament/forms/components/campaigns/actions/proactive-alert.blade.php
Labels: Change Type | Bug Fix

#1264 [ADVAPP-1159]: Error thrown by interactions without an end date set
  app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
Labels: Change Type | Bug Fix

#1266 [ADVAPP-1160]: Sometimes emails fail to send and also sometimes send while demo mode is turned on
  app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php
  app/Models/Tenant.php
  app/Multitenancy/Tasks/SwitchMailTask.php
  tests/TestCase.php
Labels: Change Type | Bug Fix

#1265 [ADVAPP-1159]: Error thrown by interactions without an end date set
  app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
Labels: Change Type | Bug Fix

#1262 [ADVAPP-692]: Laravel 11 Upgrade
  app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
  app-modules/authorization/tests/Feature/Filament/Resources/User/ViewUserTest.php
  app-modules/prospect/graphql/prospect.graphql
  app-modules/student-data-model/graphql/student.graphql
  app/Exceptions/Handler.php
  app/GraphQL/Directives/MorphToRelationDirective.php
  app/GraphQL/Scalars/UUID.php
  app/Models/HealthCheckResultHistoryItem.php
  app/Overrides/LastDragon_ru/LaraASP/GraphQL/SearchBy/Definitions/SearchByDirective.php
  app/Overrides/LastDragon_ru/LaraASP/GraphQL/SearchBy/Types/Condition.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  tests/TestCase.php
Labels: Change Type | Dependencies

#1269 [ADVAPP-1102]: Add bulk select and deselect features to the permission when editing a role for each column
  app-modules/authorization/resources/views/filament/forms/components/permissions-matrix.blade.php
Labels: Change Type | New Feature

#1261 [ADVAPP-1154]: Introduce the ability to create confidential interactions and to share those with other users or teams of users
  app-modules/interaction/database/factories/InteractionConfidentialTeamFactory.php
  app-modules/interaction/database/factories/InteractionConfidentialUserFactory.php
  app-modules/interaction/database/migrations/2025_01_24_141857_add_is_confidential_to_interactions_table.php
  app-modules/interaction/database/migrations/2025_01_24_162843_create_interaction_confidential_users_table.php
  app-modules/interaction/database/migrations/2025_01_24_162901_create_interaction_confidential_teams_table.php
  app-modules/interaction/database/migrations/2025_01_29_043853_data_activate_confidential_interaction_feature.php
  app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
  app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/CreateInteraction.php
  app-modules/interaction/src/Models/Interaction.php
  app-modules/interaction/src/Models/InteractionConfidentialTeam.php
  app-modules/interaction/src/Models/InteractionConfidentialUser.php
  app-modules/interaction/src/Models/Scopes/InteractionConfidentialScope.php
  app-modules/interaction/tests/Filament/InterationRelationManager/ListIneractionManagerTest.php
  app/Features/ConfidentialInteractionFeatureFlag.php
Labels: Change Type | New Feature, Feature Flag Added

#1270 [ADVAPP-1169]: Interaction duration calculation throws errors
  app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/CreateInteraction.php
Labels: Change Type | Bug Fix

#1272 [ADVAPP-1170]: When viewing a record that has a confidential interaction that was not created by and is not authorized for me, an exception is generated
  app-modules/timeline/src/Livewire/Concerns/CanLoadTimelineRecords.php
Labels: Change Type | Bug Fix

#1271 [ADVAPP-1171]: Spatie Health package throws errors when trying to email about failures
  config/health.php
Labels: Change Type | Bug Fix

#1274 [ADVAPP-1176]: Setup pruning for HealthCheckResultHistoryItem
  app/Console/Kernel.php
Labels: Change Type | Chore

#1275 [ADVAPP-1164]: Feature Flag Cleanup: ConfidentialInteractionFeatureFlag
  app-modules/interaction/database/migrations/2025_01_29_043853_data_activate_confidential_interaction_feature.php
  app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
  app-modules/interaction/src/Filament/Resources/InteractionResource/Pages/CreateInteraction.php
  app-modules/interaction/src/Models/Scopes/InteractionConfidentialScope.php
  app/Features/ConfidentialInteractionFeatureFlag.php
Labels: Change Type | Feature Cleanup

#1277 [ADVAPP-1162]: Feature Flag Cleanup: ScheduleMonitor
  app/Features/ScheduleMonitor.php
  app/Health/Checks/ScheduleMonitorCheck.php
  app/Listeners/SyncScheduleMonitor.php
  database/landlord/2025_01_24_170657_data_activate_schedule_monitor_feature.php
Labels: Change Type | Feature Cleanup

#1278 [ADVAPP-1175]: Increase the files size for AI file upload limits per file for threads and custom assistants from 256kb to 20MB
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanUploadFiles.php
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
Labels: Change Type | New Feature

#1276 [ADVAPP-1083]: Allow per notification quota manipulation
  app-modules/integration-twilio/tests/Feature/Jobs/CheckSmsOutboundDeliverableStatusTest.php
  app-modules/integration-twilio/tests/Fixtures/ClientMock.php
  app-modules/notification/database/factories/OutboundDeliverableFactory.php
  app-modules/notification/src/Notifications/Channels/MailChannel.php
  app-modules/notification/src/Notifications/Channels/SmsChannel.php
  app-modules/notification/tests/Feature/LicenseSettingsEmailQuotaTrackingTest.php
  app-modules/notification/tests/Feature/LicenseSettingsSmsQuotaTrackingTest.php
  app-modules/notification/tests/Feature/NotificationFromNameTest.php
  app-modules/notification/tests/Feature/NotificationSendingTest.php
  app-modules/notification/tests/Fixtures/TestEmailNotification.php
  app-modules/notification/tests/Fixtures/TestEmailSettingFromNameNotification.php
  app-modules/notification/tests/Fixtures/TestSmsNotification.php
Labels: Change Type | New Feature
