Repository canyongbs/advisingapp, pull requests merged in 2025-09, with the labels that each got.

#1835 [Hotfix]: 1.85.1
  app-modules/notification/src/Notifications/Channels/SmsChannel.php
Labels: Change Type | Bug Fix

#1836 [Chore]: Replace PHPMD
  .github/workflows/ci.yml
  .gitignore
  app-modules/integration-twilio/src/DataTransferObjects/TwilioApiKey.php
  app/PhpMd/CamelCasePropertyNameWithoutSettings.php
  composer.json
  composer.lock
  phpmd.ruleset.xml
  phpstan-baseline.php
  phpstan.neon.dist
Labels: Change Type | Dependencies, Change Type | Content or Styling Update, Change Type | Chore

#1834 [ADVAPP-1870]: Update information architecture for primary navigation
  app-modules/campaign/src/Filament/Resources/CampaignResource.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php
  app-modules/report/src/Filament/Pages/TaskManagement.php
  app-modules/report/src/Filament/Resources/ReportResource.php
  app-modules/segment/src/Filament/Resources/SegmentResource.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentSyncs.php
  app/Filament/Clusters/ReportLibrary.php
  app/Filament/Clusters/UsageAuditing.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Content or Styling Update

#1854 [ADVAPP-1899]: Fix flaky test that is blocking CI from passing in > 80% of runs
  app-modules/ai/tests/Tenant/Feature/Filament/Pages/AIAssistantPageTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/ProspectReportStatsTest.php
Labels: Change Type | Bug Fix

#1853 [ADVAPP-1881]: Some users have reported that the merge value for contact name is missing in the case type templates
  app-modules/case-management/src/Filament/Resources/CaseTypeResource/Pages/ManageCaseTypeEmailTemplate.php
Labels: Change Type | Bug Fix

#1855 [ADVAPP-1878]: Feature Flag Cleanup: ConfidentialTaskFeature
  app-modules/campaign/src/Filament/Blocks/TaskBlock.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageTasks.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableTasks.php
  app-modules/task/database/migrations/2025_08_29_215640_data_activate_confidential_task_feature.php
  app-modules/task/src/Filament/Concerns/TaskViewActionInfoList.php
  app-modules/task/src/Filament/RelationManagers/BaseTaskRelationManager.php
  app-modules/task/src/Models/Scopes/ConfidentialTaskScope.php
  app/Features/ConfidentialTaskFeature.php
Labels: Change Type | Feature Cleanup

#1843 [ADVAPP-1760]: Some users are experiencing issues when configuring email templates for case types
  app-modules/case-management/src/Filament/Resources/CaseTypeResource/Pages/ManageCaseTypeEmailTemplate.php
Labels: Change Type | Bug Fix

#1867 [ADVAPP-1909]: Some users are reporting that cases fail to load in holistic student profile
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/ListCases.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/RelationManagers/CasesRelationManager.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/CasesRelationManager.php
  app/Filament/Widgets/MyCases.php
Labels: Change Type | Bug Fix

#1882 [ADVAPP-1924]: Feature flag cleanup: WorkflowSequentialExecutionFeature
  app-modules/application/src/Listeners/TriggerApplicationSubmissionWorkflows.php
  app-modules/form/src/Listeners/TriggerFormSubmissionWorkflows.php
  app-modules/workflow/src/Jobs/CareTeamWorkflowActionJob.php
  app-modules/workflow/src/Jobs/CaseWorkflowActionJob.php
  app-modules/workflow/src/Jobs/EngagementEmailWorkflowActionJob.php
  app-modules/workflow/src/Jobs/EngagementSmsWorkflowActionJob.php
  app-modules/workflow/src/Jobs/EventWorkflowActionJob.php
  app-modules/workflow/src/Jobs/ExecuteWorkflowActionJob.php
  app-modules/workflow/src/Jobs/ExecuteWorkflowActionStepsJob.php
  app-modules/workflow/src/Jobs/InteractionWorkflowActionJob.php
  app-modules/workflow/src/Jobs/ProactiveAlertWorkflowActionJob.php
  app-modules/workflow/src/Jobs/SubscriptionWorkflowActionJob.php
  app-modules/workflow/src/Jobs/TagsWorkflowActionJob.php
  app-modules/workflow/src/Jobs/TaskWorkflowActionJob.php
  app/Features/WorkflowSequentialExecutionFeature.php
  database/migrations/2025_09_05_163123_data_activate_workflow_sequential_execution_feature.php
Labels: Change Type | Feature Cleanup

#1859 [ADVAPP-1733]: Add the ability to insert images to the online admission application forms
  app-modules/application/src/Filament/Resources/ApplicationResource/Pages/Concerns/HasSharedFormConfiguration.php
  app-modules/application/src/Models/Application.php
  app-modules/application/src/Models/ApplicationStep.php
  app-modules/form/src/Actions/GenerateFormKitSchema.php
Labels: Change Type | New Feature

#1889 [ADVAPP-1922]: Populate the first term and most recent term values automatically as a derived value
  app-modules/report/src/Filament/Exports/StudentExporter.php
  app-modules/student-data-model/database/factories/StudentFactory.php
  app-modules/student-data-model/database/migrations/2025_09_15_154353_drop_f_e_term_and_mr_e_term_from_students_table.php
  app-modules/student-data-model/src/Filament/Imports/StudentImporter.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
  app-modules/student-data-model/src/Http/Controllers/Api/V1/Students/CreateStudentController.php
  app-modules/student-data-model/src/Http/Controllers/Api/V1/Students/ListStudentsController.php
  app-modules/student-data-model/src/Http/Controllers/Api/V1/Students/UpdateStudentController.php
  app-modules/student-data-model/src/Http/Resources/Api/V1/StudentResource.php
  app-modules/student-data-model/src/Models/Student.php
  app-modules/student-data-model/tests/Tenant/Http/Controllers/Api/V1/Students/CreateStudentControllerTest.php
  app-modules/student-data-model/tests/Tenant/Http/Controllers/Api/V1/Students/ListStudentsControllerTest.php
  app-modules/student-data-model/tests/Tenant/Http/Controllers/Api/V1/Students/RequestFactories/CreateStudentRequestFactory.php
  app-modules/student-data-model/tests/Tenant/Http/Controllers/Api/V1/Students/RequestFactories/UpdateStudentRequestFactory.php
  app-modules/student-data-model/tests/Tenant/Http/Controllers/Api/V1/Students/UpdateStudentControllerTest.php
Labels: Change Type | New Feature

#1893 [ADVAPP-1853]: Enhance enrollment display in the student holistic profile by improving sorting
  app-modules/student-data-model/database/factories/EnrollmentSemesterFactory.php
  app-modules/student-data-model/database/migrations/2025_09_17_120512_create_enrollment_semesters_table.php
  app-modules/student-data-model/src/Filament/Resources/AdvisingApp/StudentDataModel/Models/EnrollmentSemesterResource.php
  app-modules/student-data-model/src/Filament/Resources/AdvisingApp/StudentDataModel/Models/EnrollmentSemesterResource/Pages/ManageEnrollmentSemesters.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EnrollmentsRelationManager.php
  app-modules/student-data-model/src/Models/EnrollmentSemester.php
  app-modules/student-data-model/src/Observers/EnrollmentSemesterObserver.php
  app-modules/student-data-model/src/Policies/EnrollmentSemesterPolicy.php
  app-modules/student-data-model/tests/Tenant/Filament/Resources/EnrollmentSemesterResource/Pages/ManageEnrollmentSemestersTest.php
  app/Features/EnrollmentSemesterFeature.php
Labels: Change Type | New Feature, Feature Flag Added

#1890 [ADVAPP-1891]: Introduce the ability to configure confidential custom advisors
  app-modules/ai/database/factories/AiAssistantConfidentialTeamFactory.php
  app-modules/ai/database/factories/AiAssistantConfidentialUserFactory.php
  app-modules/ai/database/migrations/2025_09_16_125400_create_ai_assistant_confidential_users_table.php
  app-modules/ai/database/migrations/2025_09_16_125417_create_ai_assistant_confidential_teams_table.php
  app-modules/ai/database/migrations/2025_09_17_130929_add_is_confidential_to_ai_assistants_table.php
  app-modules/ai/database/migrations/2025_09_17_173300_data_activate_ai_assistant_confidential_feature.php
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
  app-modules/ai/src/Models/AiAssistant.php
  app-modules/ai/src/Models/AiAssistantConfidentialTeam.php
  app-modules/ai/src/Models/AiAssistantConfidentialUser.php
  app-modules/ai/src/Models/AiThread.php
  app-modules/ai/src/Models/Scopes/AiAssistantConfidentialScope.php
  app-modules/ai/src/Models/Scopes/AiThreadScope.php
  app-modules/ai/tests/Tenant/Models/Scopes/AiAssistantScopeTest.php
  app/Features/AiAssistantConfidentialFeature.php
Labels: Change Type | New Feature, Feature Flag Added

#1897 [ADVAPP-1934]: AiAssistantConfidentialFeature cleanup
  app-modules/ai/database/migrations/2025_09_17_173300_data_activate_ai_assistant_confidential_feature.php
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
  app/Features/AiAssistantConfidentialFeature.php
Labels: Change Type | Feature Cleanup

#1902 [ADVAPP-1931]: Feature Flag Cleanup: SmsOptOutFeature
  app-modules/engagement/src/Filament/Actions/RelationManagerSendEngagementAction.php
  app-modules/engagement/src/Filament/Actions/SendEngagementAction.php
  app-modules/notification/src/Notifications/Channels/SmsChannel.php
  app-modules/student-data-model/resources/views/components/filament/resources/educatable-resource/view-educatable/phone-number-detail.blade.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php
  app/Features/SmsOptOutFeature.php
  database/migrations/2025_09_10_071343_data_activate_sms_opt_out_feature.php
Labels: Change Type | Feature Cleanup

#1912 [ADVAPP-1941]: Introduce the ability to export data from student cases report table as a csv
  app-modules/report/src/Filament/Exports/StudentCaseExporter.php
  app-modules/report/src/Filament/Widgets/StudentCaseTable.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentCaseTableTest.php
Labels: Change Type | New Feature

#1922 [ADVAPP-1970]: Feature Flag Cleanup: AlertVisibleToStudentsFeature
  app-modules/student-data-model/database/migrations/2025_09_24_153231_add_is_visible_for_students_to_alerts_table.php
  app-modules/student-data-model/src/Filament/Resources/EducatableResource/Pages/Concerns/CanManageEducatableAlerts.php
  app/Features/AlertVisibleToStudentsFeature.php
Labels: Change Type | Feature Cleanup

#1919 [ADVAPP-1959]: Improve the unified inbox by adding an status as to whether the message is from a prospect or a student
  app-modules/engagement/src/Filament/Pages/Inbox.php
  app-modules/engagement/tests/Tenant/Filament/Pages/InboxTest.php
Labels: Change Type | Content or Styling Update

#1930 [ADVAPP-1983]: Feature Flag Cleanup: SettingsPermissions Feature
  app-modules/ai/src/Policies/PromptTypePolicy.php
  app-modules/alert/src/Policies/AlertStatusPolicy.php
  app-modules/application/src/Policies/ApplicationSubmissionStatePolicy.php
  app-modules/care-team/src/Filament/Resources/ProspectCareTeamRoleResource.php
  app-modules/care-team/src/Filament/Resources/StudentCareTeamRoleResource.php
  app-modules/care-team/src/Policies/CareTeamRolePolicy.php
  app-modules/case-management/src/Policies/CaseFormPolicy.php
  app-modules/case-management/src/Policies/CaseStatusPolicy.php
  app-modules/case-management/src/Policies/CaseTypePolicy.php
  app-modules/case-management/src/Policies/SlaPolicy.php
  app-modules/consent/src/Policies/ConsentAgreementPolicy.php
  app-modules/engagement/src/Policies/EmailTemplatePolicy.php
  app-modules/engagement/src/Policies/SmsTemplatePolicy.php
  app-modules/interaction/src/Policies/InteractionDriverPolicy.php
  app-modules/interaction/src/Policies/InteractionInitiativePolicy.php
  app-modules/interaction/src/Policies/InteractionOutcomePolicy.php
  app-modules/interaction/src/Policies/InteractionRelationPolicy.php
  app-modules/interaction/src/Policies/InteractionStatusPolicy.php
  app-modules/interaction/src/Policies/InteractionTypePolicy.php
  app-modules/pipeline/src/Filament/Pages/PipelineSettings.php
  app-modules/prospect/src/Filament/Pages/ManageProspectConversionSettings.php
  app-modules/prospect/src/Policies/ProspectSourcePolicy.php
  app-modules/prospect/src/Policies/ProspectStatusPolicy.php
  app-modules/resource-hub/src/Policies/ResourceHubCategoryPolicy.php
  app-modules/resource-hub/src/Policies/ResourceHubQualityPolicy.php
  app-modules/resource-hub/src/Policies/ResourceHubStatusPolicy.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentConfiguration.php
  app-modules/theme/src/Filament/Pages/ManageCollegeBrandingSettings.php
  app/Features/SettingsPermissions.php
  app/Filament/Pages/ManageDisplaySettings.php
  app/Policies/NotificationSettingPolicy.php
  app/Policies/PronounsPolicy.php
  app/Policies/TagPolicy.php
  database/migrations/2025_07_14_110004_data_activate_settings_permissions_feature_flag.php
Labels: Change Type | Feature Cleanup

#1933 [ADVAPP-1979]: Cleanup HolisticEngagementFeature
  app-modules/engagement/database/migrations/2025_09_15_201808_create_holistic_engagements_view.php
  app-modules/report/src/Filament/Pages/ProspectMessagesDetailReport.php
  app-modules/report/src/Filament/Pages/StudentMessagesDetailReport.php
  app/Features/HolisticEngagementFeature.php
Labels: Change Type | Feature Cleanup

#1936 [ADVAPP-1958]: Improve unified inbox by adding a message type column to distinguish between texts and emails
  app-modules/engagement/src/Filament/Pages/Inbox.php
  app-modules/engagement/tests/Tenant/Filament/Pages/InboxTest.php
Labels: Change Type | Content or Styling Update

#1916 [ADVAPP-1939]: Introduce the ability to export data from student messages overview report table as a csv
  app-modules/report/src/Filament/Exports/MostEngagedStudentTableExporter.php
  app-modules/report/src/Filament/Widgets/MostEngagedStudentsTable.php
  app-modules/report/tests/Tenant/Filament/Widgets/MostEngagedStudentsTableTest.php
  composer.json
  composer.lock
Labels: Change Type | New Feature
