Repository canyongbs/advisingapp, pull requests merged in 2025-07, with the labels that each got.

#1669 [ADVAPP-1633]: Deprecate and remove configuration support for gpt-3.5 and gpt-4
  .env.example
  app-modules/ai/database/migrations/2025_06_30_113742_data_remove_gpt_35_and_gpt_4_settings.php
  app-modules/ai/src/Enums/AiModel.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app-modules/ai/src/Settings/AiIntegrationsSettings.php
  app-modules/ai/tests/Tenant/Feature/Filament/Resources/AiAssistantResource/CreateAiAssistantTest.php
  app-modules/ai/tests/Tenant/Feature/Filament/Resources/AiAssistantResource/EditAiAssistantTest.php
  app-modules/ai/tests/Tenant/Feature/Filament/Resources/AiAssistantResource/RequestFactories/CreateAiAssistantRequestFactory.php
  app-modules/ai/tests/Tenant/Feature/Filament/Resources/AiAssistantResource/RequestFactories/EditAiAssistantRequestFactory.php
  app-modules/ai/tests/Tenant/Filament/Resources/QnaAdvisor/Pages/CreateQnaAdvisorTest.php
  app-modules/integration-open-ai/config/integration-open-ai.php
  app-modules/integration-open-ai/src/Services/OpenAiGpt35Service.php
Labels: Change Type | Chore

#1672 [ADVAPP-1643]: Feature Flag Cleanup: SubmitAiChatOnEnterFlag
  app-modules/ai/resources/views/components/assistant.blade.php
  app/Features/SubmitAiChatOnEnterFlag.php
  app/Filament/Pages/ArtificialIntelligence.php
  database/migrations/2025_05_07_192515_data_activate_is_submit_ai_chat_on_enter_feature_flag.php
Labels: Change Type | Feature Cleanup

#1673 [Bugfix]: Give all import and export jobs a 10 minute timeout
  app/Overrides/Filament/Actions/Exports/Jobs/CreateXlsxFileOverride.php
  app/Overrides/Filament/Actions/Exports/Jobs/ExportCompletionOverride.php
  app/Overrides/Filament/Actions/Exports/Jobs/ExportCsvOverride.php
  app/Overrides/Filament/Actions/Exports/Jobs/PrepareCsvExportOverride.php
  app/Overrides/Filament/Actions/Imports/Jobs/ImportCsvOverride.php
Labels: Change Type | Bug Fix

#1678 [ADVAPP-1649]: Services that have no credentials cause the assistant vector store check scheduled command to fail
  _ide_helper_models.php
  app-modules/integration-open-ai/src/Console/Commands/UploadAssistantFilesToVectorStores.php
Labels: Change Type | Bug Fix

#1681 [ADVAPP-1648]: Feature Flag Cleanup: OpenAiVectorStoresFeature
  app-modules/integration-open-ai/src/Console/Commands/UploadAssistantFilesToVectorStores.php
  app-modules/integration-open-ai/src/Services/BaseOpenAiResponsesService.php
  app/Features/OpenAiVectorStoresFeature.php
  database/migrations/2025_07_01_122617_data_activate_open_ai_vector_stores_feature.php
Labels: Change Type | Feature Cleanup

#1685 [ADVAPP-1645]: Clean up CaseTypeNotificationFeature
  app-modules/case-management/src/Filament/Resources/CaseTypeResource/Pages/EditCaseTypeNotifications.php
  app/Features/CaseTypeNotificationFeature.php
  database/migrations/2025_06_26_122617_data_activate_case_type_notification_feature_flag.php
Labels: Change Type | Feature Cleanup

#1634 [ADVAPP]: Resolved Lint errors.
  app-modules/webhook/src/DataTransferObjects/SnsMessage.php
  app/Actions/Finders/ApplicationModules.php
  app/Actions/GetRecordFromMorphAndKey.php
  app/Console/Commands/DispatchMigrations.php
  app/Filament/Pages/ManageDisplaySettings.php
  app/Filament/Resources/UserResource/Actions/AssignLicensesBulkAction.php
  app/Filament/Resources/UserResource/Actions/AssignRolesBulkAction.php
  app/Filament/Resources/UserResource/Actions/AssignTeamBulkAction.php
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Filament/Resources/UserResource/Pages/ViewUser.php
  app/Filament/Resources/UserResource/RelationManagers/RolesRelationManager.php
  app/Filament/Widgets/ProspectGrowthChart.php
  app/Filament/Widgets/RecentProspectsList.php
  app/Http/Middleware/AuthGates.php
  app/Http/Middleware/SetPreferredLocale.php
  app/Http/Requests/SetAzureSsoSettingRequest.php
  app/Http/Requests/Tenants/CreateTenantRequest.php
  app/Http/Requests/Tenants/SyncTenantRequest.php
  app/Jobs/CreateTenantUser.php
  app/Livewire/BrandingBar.php
  app/Livewire/TaskKanban.php
  app/Multitenancy/Http/Middleware/NeedsTenant.php
  app/Multitenancy/Tasks/PrefixCacheTask.php
  app/Multitenancy/Tasks/SwitchAppUrl.php
  app/Overrides/LaravelSqsExtended/SqsDiskConnector.php
  app/View/Components/DatePicker.php
  app/View/Components/Dropzone.php
  app/View/Components/SelectList.php
  database/factories/Concerns/RandomizeState.php
  database/migrations/2024_07_31_202514_data_rename_checkbox_form_fields.php
  phpstan-baseline.php
Labels: Change Type | Bug Fix

#1687 [ADVAPP-1595]: EngagementCampaignActionJob threw an Exception about the educatable not being the correct class
  app-modules/ai/src/Models/Concerns/CanAddAssistantLicenseGlobalScope.php
  app-modules/campaign/src/Jobs/EngagementCampaignActionJob.php
  app-modules/campaign/src/Jobs/ExecuteCampaignAction.php
  app-modules/campaign/src/Models/Campaign.php
  app-modules/prospect/src/Models/Prospect.php
  app-modules/segment/src/Models/Segment.php
  app-modules/student-data-model/src/Models/Student.php
Labels: Change Type | Bug Fix

#1691 [ADVAPP-1664]: Implement performance and infrastructure improvements for audit record consistency
  app/Overrides/LaravelSqsExtended/SqsDiskJob.php
  app/Overrides/LaravelSqsExtended/SqsDiskQueue.php
Labels: Change Type | Bug Fix

#1694 [Chore]: Fix issue with composer lock file and properties
  app-modules/form/src/Filament/Resources/FormResource/Pages/ManageFormSubmissions.php
  app-modules/portal/src/Http/Controllers/ResourceHub/ResourceHubPortalCategoryController.php
  composer.lock
  config/sentry.php
  phpstan-baseline.php
  tests/Expectations.php
  tests/Helpers/RollbackMigrations.php
Labels: Change Type | Bug Fix, Change Type | Dependencies

#1698 [ADVAPP-1679]: Add a Research Advisor report as coming soon under Artificial Intelligence following the Utilization report
  app-modules/report/src/Filament/Pages/ResearchAdvisorReport.php
Labels: Change Type | New Feature

#1697 [ADVAPP-1678]: Add a Custom Advisors report as coming soon under Artificial Intelligence following the Utilization report
  app-modules/report/src/Filament/Pages/CustomAdvisorReport.php
Labels: Change Type | New Feature

#1702 [ADVAPP-1674]: Improve the naming of the analytics in the main navigation
  app-modules/report/src/Filament/Resources/ReportResource.php
  app/Filament/Clusters/ReportLibrary.php
  app/Filament/Clusters/UsageAuditing.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Content or Styling Update

#1704 [ADVAPP-1672]: Simplify the CRM navigation in the application by combining the main navigation group for retention and recruitment
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentSyncs.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Documentation

#1710 [ADVAPP-1686]: Remove legacy purchase order fields in the data model and interface under subscription information for global administrators
  app/Console/Commands/CreateTenant.php
  app/DataTransferObjects/LicenseManagement/LicenseSubscriptionData.php
  app/Filament/Pages/ManageLicenseSettings.php
  app/Http/Requests/Tenants/CreateTenantRequest.php
  app/Http/Requests/Tenants/SyncTenantRequest.php
  tests/TestCase.php
Labels: Change Type | New Feature

#1707 [ADVAPP-1673]: Improve and streamline the product features navigation by relocating them to the CRM navigation.
  app-modules/alert/src/Filament/Resources/AlertResource.php
  app-modules/campaign/src/Filament/Resources/CampaignResource.php
  app-modules/engagement/src/Filament/Pages/MessageCenter.php
  app-modules/engagement/src/Filament/Resources/EngagementFileResource.php
  app-modules/interaction/src/Filament/Resources/InteractionResource.php
  app-modules/report/src/Filament/Pages/TaskManagement.php
  app-modules/resource-hub/src/Filament/Resources/ResourceHubArticleResource.php
  app-modules/segment/src/Filament/Resources/SegmentResource.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentSyncs.php
  app-modules/task/src/Filament/Resources/TaskResource.php
  app/Filament/Clusters/CaseManagement.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Documentation

#1719 [ADVAPP-1708]: Relocate Prospects in the list below Students for a more natural flow in the main navigation menu
  app-modules/prospect/src/Filament/Resources/ProspectResource.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource.php
Labels: Change Type | New Feature

#1721 [ADVAPP-1699][ADVAPP-1700][ADVAPP-1704][ADVAPP-1705][ADVAPP-1706][ADVAPP-1707]: Introduce new main navigations 'Project Management, Online Admissions, Digital Forms, Event Management, Automation Data'
  app-modules/application/src/Filament/Resources/ApplicationResource.php
  app-modules/campaign/src/Filament/Resources/CampaignResource.php
  app-modules/form/src/Filament/Resources/FormResource.php
  app-modules/meeting-center/src/Filament/Resources/EventResource.php
  app-modules/segment/src/Filament/Resources/SegmentResource.php
  app-modules/student-data-model/src/Filament/Pages/ManageStudentSyncs.php
  app-modules/task/src/Filament/Resources/TaskResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Content or Styling Update

#1716 [ADVAPP-1712]: Update Olympus API tenant creation to work without a name passed
  app/Http/Controllers/Tenants/CreateTenantController.php
  app/Http/Requests/Tenants/CreateTenantRequest.php
Labels: Change Type | New Feature

#1724 [ADVAPP-1671]: Improve the conversation quality of the prompt library by disabling the prompt library button after the initial prompt and add a tool tip to explain why it is not available
  app-modules/ai/resources/views/components/assistant.blade.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManagePromptLibrary.php
Labels: Change Type | Chore

#1725 [ADVAPP-1696]: Improve the user experience when loading the institutional advisor
  app-modules/ai/resources/views/components/assistant.blade.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManageThreads.php
  app-modules/ai/src/Services/Contracts/AiServiceLifecycleHooks.php
  app-modules/ai/tests/Tenant/Feature/Filament/Pages/AIAssistantPageTest.php
  app-modules/integration-open-ai/src/Services/Concerns/UploadsFiles.php
Labels: Change Type | Documentation

#1727 [ADVAPP-1684]: Some users are experiencing an issue when using the my teams tasks filter in the task list
  app-modules/task/src/Filament/Resources/TaskResource/Pages/ListTasks.php
Labels: Change Type | Bug Fix

#1728 [ADVAPP-1675][ADVAPP-1676]: Introduce case management reports for students and prospects
  app-modules/case-management/src/Filament/Resources/CaseResource.php
  app-modules/case-management/src/Filament/Resources/CaseResource/Pages/Concerns/HasCaseRecordHeader.php
  app-modules/report/src/Abstract/Concerns/HasFiltersForm.php
  app-modules/report/src/Filament/Pages/ProspectCaseReport.php
  app-modules/report/src/Filament/Pages/StudentCaseReport.php
  app-modules/report/src/Filament/Widgets/ProspectCaseStats.php
  app-modules/report/src/Filament/Widgets/ProspectCaseTable.php
  app-modules/report/src/Filament/Widgets/StudentCaseStats.php
  app-modules/report/src/Filament/Widgets/StudentCaseTable.php
  app-modules/report/tests/Tenant/Filament/Widgets/ProspectCaseStatsTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/ProspectCaseTableTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentCaseStatsTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentCaseTableTest.php
Labels: Change Type | New Feature

#1736 [ADVAPP-1675]: Hide cases resource from the main navigation
  app-modules/case-management/src/Filament/Resources/CaseResource.php
Labels: Change Type | Content or Styling Update

#1737 [ADVAPP-1721]: When models are previously selected and they have been removed from the Model Applicability list, select inputs that load them throw an error
  app-modules/ai/src/Filament/Pages/ManageAiICustomAdvisorSettings.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegratedAssistantSettings.php
  app-modules/ai/src/Filament/Pages/ManageAiQnaAdvisorSettings.php
  app-modules/ai/src/Filament/Pages/ManageAiResearchAssistantSettings.php
  app-modules/ai/src/Filament/Pages/ManageAiSettings.php
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/CreateQnaAdvisor.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/EditQnaAdvisor.php
Labels: Change Type | Bug Fix

#1738 [ADVAPP-1722]: New Smart Prompt tile interface usage does not record as a "use"
  app-modules/ai/src/Actions/SendMessage.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanManagePromptLibrary.php
  app-modules/ai/tests/Tenant/Feature/Filament/Pages/AIAssistantPageTest.php
  app-modules/research/src/Jobs/GenerateResearchRequestSection.php
Labels: Change Type | Bug Fix

#1740 [ADVAPP-1720]: Clean up QnaAdvisorEmbedFeature
  app-modules/ai/database/migrations/2025_07_23_185508_data_activate_qna_advisor_embed_feature_feature_flag.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/QnaAdvisorEmbed.php
  app/Features/QnaAdvisorEmbedFeature.php
Labels: Change Type | Feature Cleanup

#1739 [ADVAPP-1719]: Clean up OnlineAdmissionGenerateProspect feature
  app-modules/application/src/Http/Controllers/ApplicationWidgetController.php
  app/Features/OnlineAdmissionGenerateProspect.php
  database/migrations/2025_07_21_162118_data_activate_online_admission_generate_prospect_feature_flag.php
Labels: Change Type | Feature Cleanup

#1718 [ADVAPP-1630]: Introduce external REST API for enrollments
  app-modules/student-data-model/routes/api.php
  app-modules/student-data-model/src/Actions/PutStudentEnrollments.php
  app-modules/student-data-model/src/DataTransferObjects/StudentEnrollmentData.php
  app-modules/student-data-model/src/Http/Controllers/Api/V1/Students/StudentEnrollments/ListStudentEnrollmentsController.php
  app-modules/student-data-model/src/Http/Controllers/Api/V1/Students/StudentEnrollments/PutStudentEnrollmentsController.php
  app-modules/student-data-model/src/Http/Resources/Api/V1/StudentEnrollmentResource.php
  app-modules/student-data-model/tests/Tenant/Http/Controllers/Api/V1/Students/StudentEnrollments/ListStudentEnrollmentsControllerTest.php
  app-modules/student-data-model/tests/Tenant/Http/Controllers/Api/V1/Students/StudentEnrollments/PutStudentEnrollmentsControllerTest.php
  app-modules/student-data-model/tests/Tenant/Http/Controllers/Api/V1/Students/StudentEnrollments/RequestFactories/StudentEnrollmentRequestFactory.php
Labels: Change Type | New Feature

#1743 [ADVAPP-1724][ADVAPP-1725]: Restrict the view of models if it is not configurable to Global Administrators, Restrict the view of the application dropdown in the custom advisor screens to Global Administrators
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
Labels: Change Type | Content or Styling Update
