Repository canyongbs/advisingapp, pull requests merged in 2025-10, with the labels that each got.

#1940 [Bugfix]: Check requesting URL headers if origin is missing
  app-modules/ai/src/Http/Middleware/EnsureQnaAdvisorRequestComingFromAuthorizedDomain.php
  app-modules/form/src/Http/Middleware/EnsureSubmissibleIsEmbeddableAndAuthorized.php
  app-modules/meeting-center/src/Http/Middleware/EnsureEventRegistrationFormIsEmbeddableAndAuthorized.php
  app-modules/portal/src/Http/Middleware/EnsureResourceHubPortalIsEmbeddableAndAuthorized.php
Labels: Change Type | Bug Fix

#1937 [ADVAPP-1961]: Improve unified inbox by adding a status toggle to mark messages as Actioned or New
  app-modules/engagement/resources/views/filament/pages/view-engagement-response.blade.php
  app-modules/engagement/src/Filament/Pages/ViewEngagementResponse.php
Labels: Change Type | New Feature

#1945 V4 bugfixes
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-alerts-widget.blade.php
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-care-team-widget.blade.php
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-subscriptions-widget.blade.php
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/widgets/educatable-tasks-widget.blade.php
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#1946 [ADVAPP-2000]: Some users have reported that one of the summary cards in QnA Advisor report is incorrectly labeled
  app-modules/report/src/Filament/Widgets/QnaAdvisorReportStats.php
Labels: Change Type | Bug Fix

#1947 [ADVAPP-2040]: Missing sentBy relationship (most likely a deleted user) causes the Student Message Details report table to throw an error and now load rows after a certain point
  app-modules/report/src/Filament/Widgets/ProspectMessagesDetailTable.php
  app-modules/report/src/Filament/Widgets/StudentMessagesDetailTable.php
Labels: Change Type | Bug Fix

#1953 fix: Flaky QnaAdvisorCategory test
  app-modules/ai/database/factories/QnaAdvisorCategoryFactory.php
Labels: Change Type | Bug Fix

#1950 [Hotfix]: 1.90.2
  app-modules/ai/database/factories/QnaAdvisorCategoryFactory.php
  app-modules/case-management/src/Notifications/Concerns/HandlesCaseTemplateContent.php
  app-modules/case-management/src/Notifications/EducatableCaseAssignedNotification.php
  app-modules/case-management/src/Notifications/EducatableCaseStatusChangeNotification.php
  app-modules/case-management/src/Notifications/EducatableCaseUpdatedNotification.php
  app-modules/engagement/src/Models/Engagement.php
  app-modules/report/src/Filament/Widgets/ProspectMessagesDetailTable.php
  app-modules/report/src/Filament/Widgets/QnaAdvisorReportStats.php
  app-modules/report/src/Filament/Widgets/StudentMessagesDetailTable.php
Labels: Change Type | Bug Fix

#1968 [ADVAPP-1944]: Update the tasks report to be under Cases in the Prospects and Students heading in report library
  app-modules/report/src/Filament/Pages/ProspectTaskManagement.php
  app-modules/report/src/Filament/Pages/StudentTaskManagement.php
  app-modules/report/src/Filament/Widgets/MostRecentTasksTable.php
  app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php
  app-modules/report/src/Filament/Widgets/TaskStats.php
  app-modules/report/tests/Tenant/Filament/Widgets/MostRecentTasksTableTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/TaskStatsTest.php
Labels: Change Type | Content or Styling Update

#1963 [ADVAPP-2009]: Update Filament resource structure: audit module
  app-modules/audit/src/Filament/Resources/Audits/AuditResource.php
  app-modules/audit/src/Filament/Resources/Audits/Pages/ListAudits.php
  app-modules/audit/src/Filament/Resources/Audits/Pages/ViewAudit.php
  app-modules/audit/tests/Tenant/Audit/ListAuditsTest.php
  app-modules/audit/tests/Tenant/Audit/ViewAuditTest.php
Labels: Change Type | Chore

#1977 [ADVAPP-2012]: Update Filament resource structure: campaign module
  app-modules/campaign/src/Filament/Blocks/CareTeamBlock.php
  app-modules/campaign/src/Filament/Blocks/TagsBlock.php
  app-modules/campaign/src/Filament/Resources/Campaigns/CampaignResource.php
  app-modules/campaign/src/Filament/Resources/Campaigns/Pages/CreateCampaign.php
  app-modules/campaign/src/Filament/Resources/Campaigns/Pages/EditCampaign.php
  app-modules/campaign/src/Filament/Resources/Campaigns/Pages/ListCampaigns.php
  app-modules/campaign/src/Filament/Resources/Campaigns/Pages/ViewCampaign.php
  app-modules/campaign/src/Filament/Resources/Campaigns/RelationManagers/CampaignActionsRelationManager.php
  app-modules/campaign/src/Notifications/CampaignActionFinished.php
  app-modules/campaign/tests/Tenant/Actions/ListCampaignsTest.php
  app-modules/report/src/Filament/Widgets/ProspectMessagesDetailTable.php
  app-modules/report/src/Filament/Widgets/StudentMessagesDetailTable.php
  phpstan-baseline.php
Labels: Change Type | Chore
