Repository canyongbs/advisingapp, pull requests merged in 2025-06, with the labels that each got.

#1588 [ADVAPP-1553]: Introduce three tabs in the action center for all, subscribed, and care team
  _ide_helper_models.php
  app-modules/care-team/database/factories/CareTeamFactory.php
  app-modules/care-team/src/Models/CareTeam.php
  app-modules/prospect/src/Filament/Pages/RecruitmentCrmDashboard.php
  app-modules/prospect/src/Filament/Widgets/ProspectStats.php
  app-modules/prospect/src/Filament/Widgets/ProspectsActionCenterWidget.php
  app-modules/prospect/tests/Tenant/Unit/RecruitmentCrmDashboardTest.php
  app-modules/student-data-model/resources/views/filament/pages/dashboard.blade.php
  app-modules/student-data-model/src/Enums/ActionCenterTab.php
  app-modules/student-data-model/src/Filament/Pages/RetentionCrmDashboard.php
  app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
  app-modules/student-data-model/src/Filament/Widgets/StudentsActionCenterWidget.php
  app-modules/student-data-model/tests/Tenant/Unit/RetentionCrmDashboardTest.php
  app/Filament/Widgets/ProspectGrowthChart.php
  tests/.pest/snapshots/var/www/html/app-modules/prospect/tests/Tenant/Unit/RecruitmentCrmDashboardTest/it_renders_all_prospects_correctly_in_the_recruitment_dashboard_for_the_All_tab.snap
  tests/.pest/snapshots/var/www/html/app-modules/prospect/tests/Tenant/Unit/RecruitmentCrmDashboardTest/it_renders_care_team_prospects_correctly_in_the_recruitment_dashboard_for_the_Care_Team_tab.snap
  tests/.pest/snapshots/var/www/html/app-modules/prospect/tests/Tenant/Unit/RecruitmentCrmDashboardTest/it_renders_subscribed_prospects_correctly_in_the_recruitment_dashboard_for_the_Subscribed_tab.snap
Labels: Change Type | New Feature

#1597 [ADVAPP-1566]: Certain Engagement records are throwing errors for Product Student records
  app-modules/engagement/resources/views/components/engagement-timeline-item.blade.php
  app-modules/interaction/src/Filament/Concerns/HasManyMorphedInteractionsTrait.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
  app-modules/timeline/src/Timelines/EngagementTimeline.php
Labels: Change Type | Bug Fix

#1599 [ADVAPP-1532]: Update the core UI/UX experience for the Research Advisor
  app-modules/research/resources/js/results.js
  app-modules/research/resources/views/filament/pages/manage-research-requests.blade.php
  app-modules/research/resources/views/results.blade.php
  bin/build.js
  package-lock.json
  package.json
  resources/css/filament/admin/theme.css
Labels: Change Type | New Feature

#1585 [ADVAPP-1547]: Introduce the ability to Create Interaction from the student and prospect list view bulk actions
  app-modules/campaign/src/Filament/Blocks/InteractionBlock.php
  app-modules/interaction/src/Filament/Actions/BulkCreateInteractionAction.php
  app-modules/interaction/tests/Tenant/Filament/Actions/BulkCreateInteractionActionTest.php
  app-modules/interaction/tests/Tenant/Filament/Actions/RequestFactories/BulkCreateInteractionActionRequestFactory.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/prospect/tests/Tenant/Prospect/ListProspectTest.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
  app-modules/student-data-model/tests/Tenant/Filament/Resources/StudentResource/Pages/ListStudentsTest.php
Labels: Change Type | New Feature

#1590 [ADVAPP-1546]: Introduce the ability to Create Alert from the student and prospect list view bulk actions.
  app-modules/alert/src/Filament/Actions/BulkCreateAlertAction.php
  app-modules/alert/tests/Tenant/Filament/Actions/BulkCreateAlertActionTest.php
  app-modules/alert/tests/Tenant/Filament/Actions/RequestFactories/BulkCreateAlertActionRequestFactory.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/prospect/tests/Tenant/Prospect/ListProspectTest.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
  app-modules/student-data-model/tests/Tenant/Filament/Resources/StudentResource/Pages/ListStudentsTest.php
Labels: Change Type | New Feature

#1604 [ADVAPP-1554]: Display pagination information x of y on the bottom left of the Action Center table
  app-modules/prospect/src/Filament/Widgets/ProspectsActionCenterWidget.php
  app-modules/student-data-model/src/Filament/Widgets/StudentsActionCenterWidget.php
Labels: Change Type | New Feature, Change Type | Content or Styling Update

#1594 [ADVAPP-1550]: Introduce the ability to Create Case for the student and prospect list view bulk action
  app-modules/campaign/src/Filament/Blocks/CaseBlock.php
  app-modules/case-management/src/Filament/Actions/BulkCreateCaseAction.php
  app-modules/case-management/tests/Tenant/Filament/Actions/BulkCreateCaseActionTest.php
  app-modules/case-management/tests/Tenant/Filament/Actions/RequestFactories/BulkCreateCaseActionRequestFactory.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/prospect/tests/Tenant/Prospect/ListProspectTest.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
  app-modules/student-data-model/tests/Tenant/Filament/Resources/StudentResource/Pages/ListStudentsTest.php
Labels: Change Type | New Feature

#1605 [CHORE]: Upgrade stefanzweifel/git-auto-commit-action and fix checkout to not detach
  .github/workflows/ci.yml
Labels: Change Type | Bug Fix

#1609 [ADVAPP-1570]: Polling in EngagementsRelationManager causes any related action to refresh during the tables refresh
  app-modules/application/src/Http/Controllers/ApplicationWidgetController.php
  app-modules/case-management/src/Http/Controllers/CaseFormWidgetController.php
  app-modules/form/src/Http/Controllers/FormWidgetController.php
  app-modules/in-app-communication/src/Filament/Pages/UserChat.php
  app-modules/meeting-center/src/Http/Controllers/EventRegistrationWidgetController.php
  app-modules/student-data-model/src/Filament/Actions/ImportStudentDataAction.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/EngagementsRelationManager.php
  app-modules/survey/src/Http/Controllers/SurveyWidgetController.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
Labels: Change Type | Bug Fix

#1611 [ADVAPP-1582]: Improve the display of the prospect overview report in the report library
  app-modules/report/src/Filament/Widgets/ProspectReportLineChart.php
Labels: Change Type | Content or Styling Update

#1614 [ADVAPP-1580]: Improve the display of the cards on the interaction report
  app-modules/report/src/Filament/Widgets/ProspectInteractionStats.php
  app-modules/report/src/Filament/Widgets/StudentInteractionStats.php
Labels: Change Type | Content or Styling Update

#1618 [ADVAPP-1584]: Enhance the organization and naming of bulk actions in student and prospect list views.
  app-modules/alert/src/Filament/Actions/BulkCreateAlertAction.php
  app-modules/case-management/src/Filament/Actions/BulkCreateCaseAction.php
  app-modules/interaction/src/Filament/Actions/BulkCreateInteractionAction.php
  app-modules/notification/src/Filament/Actions/SubscribeBulkAction.php
  app-modules/prospect/src/Filament/Actions/ProspectTagsBulkAction.php
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ListProspects.php
  app-modules/segment/src/Actions/BulkSegmentAction.php
  app-modules/student-data-model/src/Filament/Actions/StudentTagsBulkAction.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/ListStudents.php
Labels: Change Type | Documentation

#1621 [ADVAPP-1586]: Resolve the security issue tracked under CVE-2025-5889
  package-lock.json
Labels: dependencies

#1622 [ADVAPP-1518]: Event Management was broken by the changing of Student and Prospect email storage
  app-modules/prospect/src/Models/Prospect.php
  app-modules/student-data-model/src/Models/Contracts/Educatable.php
  app-modules/student-data-model/src/Models/Student.php
Labels: Change Type | Bug Fix

#1610 [ADVAPP-1583]: Improve the organization and navigation of profile settings for product users & [ADVAPP-1573]: Update labeling for branding bar to match other sections in profile settings
  app/Filament/Clusters/ProfileSettings.php
  app/Filament/Pages/ArtificialIntelligence.php
  app/Filament/Pages/BrandingBar.php
  app/Filament/Pages/ConnectedAccounts.php
  app/Filament/Pages/EditProfile.php
  app/Filament/Pages/EmailSignature.php
  app/Filament/Pages/MultifactorAuthentication.php
  app/Filament/Pages/OfficeHours.php
  app/Filament/Pages/OutOfOffice.php
  app/Filament/Pages/ProfileInformation.php
  app/Filament/Pages/ProfilePage.php
  app/Filament/Pages/Timezone.php
  app/Filament/Pages/WorkingHours.php
  app/Providers/Filament/AdminPanelProvider.php
  composer.json
  resources/views/filament/pages/multifactor-authentication.blade.php
  resources/views/filament/pages/profile-save.blade.php
Labels: Change Type | Content or Styling Update

#1624 [ADVAPP-1572]: Display the primary email and phone number in a second location on the prospect profile
  app-modules/prospect/src/Filament/Resources/ProspectResource/Schemas/ProspectProfileInfolist.php
Labels: Change Type | New Feature

#1629 [ADVAPP-1591]: Users not having profile images causes Azure to throw error to Sentry unnecessarily
  app-modules/authorization/src/Http/Controllers/SocialiteController.php
Labels: Change Type | Bug Fix

#1633 [ADVAPP-1594]: Update Prism and remove our override of the Stream class
  app-modules/integration-open-ai/composer.json
  app-modules/integration-open-ai/src/Prism/AzureOpenAi.php
  app-modules/integration-open-ai/src/Prism/Handlers/Stream.php
  composer.lock
Labels: Change Type | Chore

#1632 [ADVAPP-1593]: When sending a message to the Response API ensure the Response object exists
  app-modules/integration-open-ai/src/Services/BaseOpenAiResponsesService.php
  app-modules/integration-open-ai/src/Services/OpenAiResponsesGptTestService.php
  app-modules/integration-open-ai/tests/Tenant/Feature/Services/OpenAiResponsesGptTestServiceTest.php
Labels: Change Type | New Feature

#1644 [ADVAPP-1604]: Improve messaging location for profile setting information related to Artificial Intelligence
  app/Filament/Pages/ArtificialIntelligence.php
Labels: Change Type | Content or Styling Update

#1640 [ADVAPP-1585]: Introduce a tool tip next to the subscription button on the holistic profile of students and prospects
  app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/Concerns/HasProspectHeader.php
  app-modules/student-data-model/resources/views/filament/resources/educatable-resource/subscribe-header-action.blade.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/Concerns/HasStudentHeader.php
Labels: Change Type | New Feature

#1643 [ADVAPP-1603]: Improve messaging around Multifactor Authentication when user account is configured to use SSO
  app-modules/multifactor-authentication/resources/views/livewire/multifactor-authentication-management.blade.php
  app-modules/multifactor-authentication/src/Livewire/MultifactorAuthenticationManagement.php
  resources/views/filament/pages/multifactor-authentication.blade.php
Labels: Change Type | New Feature

#1635 [ADVAPP-1605]: Provide a new setting for Action Center daily update for users by the institutional assistant
  _ide_helper_models.php
  app/Features/ActionCenterUpdateFeatureFlag.php
  app/Filament/Pages/ArtificialIntelligence.php
  app/Models/User.php
  database/migrations/2025_06_23_094150_add_is_action_center_update_enabled_column_in_users_table.php
  database/migrations/2025_06_23_095616_data_activate_action_center_update_feature_flag.php.php
Labels: Change Type | New Feature, Feature Flag Added

#1627 [ADVAPP-1440]: Implement the QnA advisor functionality
  _ide_helper_models.php
  app-modules/ai/database/factories/QnaAdvisorCategoryFactory.php
  app-modules/ai/database/factories/QnaAdvisorFactory.php
  app-modules/ai/database/factories/QnaAdvisorQuestionFactory.php
  app-modules/ai/database/migrations/2025_06_17_102215_create_ai_qna_advisor_settings.php
  app-modules/ai/database/migrations/2025_06_17_144755_create_qna_advisors_table.php
  app-modules/ai/database/migrations/2025_06_18_090829_create_qna_advisor_categories_table.php
  app-modules/ai/database/migrations/2025_06_18_103834_create_qna_advisor_questions_table.php
  app-modules/ai/database/migrations/2025_06_19_125848_seed_qna_advisor_permissions.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app-modules/ai/src/Filament/Pages/ManageAiQnaAdvisorSettings.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/CreateQnaAdvisor.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/EditQnaAdvisor.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/ListQnaAdvisors.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/ManageCategories.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/ManageQnaQuestions.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/QnaAdvisorEmbed.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/ViewQnaAdvisor.php
  app-modules/ai/src/Models/QnaAdvisor.php
  app-modules/ai/src/Models/QnaAdvisorCategory.php
  app-modules/ai/src/Models/QnaAdvisorQuestion.php
  app-modules/ai/src/Policies/QnaAdvisorCategoryPolicy.php
  app-modules/ai/src/Policies/QnaAdvisorPolicy.php
  app-modules/ai/src/Policies/QnaAdvisorQuestionPolicy.php
  app-modules/ai/src/Providers/AiServiceProvider.php
  app-modules/ai/src/Settings/AiQnaAdvisorSettings.php
  app-modules/ai/tests/RequestFactories/QnaAdvisorCategoryRequestFactory.php
  app-modules/ai/tests/RequestFactories/QnaAdvisorQuestionRequestFactory.php
  app-modules/ai/tests/RequestFactories/QnaAdvisorRequestFactory.php
  app-modules/ai/tests/Tenant/Filament/Resources/QnaAdvisor/Pages/CreateQnaAdvisorTest.php
  app-modules/ai/tests/Tenant/Filament/Resources/QnaAdvisor/Pages/EditQnaAdvisorTest.php
  app-modules/ai/tests/Tenant/Filament/Resources/QnaAdvisor/Pages/ListQnAAdvisorsTest.php
  app-modules/ai/tests/Tenant/Filament/Resources/QnaAdvisor/Pages/ManageCategoriesTest.php
  app-modules/ai/tests/Tenant/Filament/Resources/QnaAdvisor/Pages/ManageQuestionsTest.php
  app-modules/ai/tests/Tenant/Filament/Resources/QnaAdvisor/Pages/ViewQnaAdvisorTest.php
  app-modules/ai/tests/Tenant/Unit/QnaCategoryUniqueTest.php
  app/Features/QnaAdvisorFeature.php
  database/migrations/2025_06_19_142806_data_activate_qna_advisor_feature_flag.php
Labels: Change Type | New Feature, Feature Flag Added

#1648 Update roadrunner to 2025.1.2
  Dockerfile
Labels: Change Type | Dependencies, Change Type | DevOps

#1649 [Bugfix]: Ensure the UnmatchedInboundCommunicationsJob is dispatched as a Tenant
  app/Console/Kernel.php
Labels: Change Type | Bug Fix

#1665 [ADVAPP-1615]: Feature Flag Cleanup: LlamaParse
  app-modules/ai/database/factories/AiAssistantFactory.php
  app-modules/ai/database/migrations/2025_06_23_051054_add_llamaparse_ai_settings.php
  app-modules/ai/resources/views/components/assistant.blade.php
  app-modules/ai/src/Console/Commands/FetchAiAssistantFilesParsingResults.php
  app-modules/ai/src/Filament/Pages/Assistant/Concerns/CanUploadFiles.php
  app-modules/ai/src/Filament/Pages/ManageAiIntegrationsSettings.php
  app-modules/ai/src/Filament/Resources/AiAssistantResource/Forms/AiAssistantForm.php
  app-modules/ai/src/Http/Controllers/RetryMessageController.php
  app-modules/ai/src/Http/Controllers/SendMessageController.php
  app/Features/LlamaParse.php
Labels: Change Type | Feature Cleanup

#1662 [ADVAPP-1642]: Feature Flag Cleanup: JourneyStepPermissionRename
  app-modules/campaign/src/Policies/CampaignActionPolicy.php
  app/Features/JourneyStepPermissionRename.php
  database/migrations/2025_06_05_115710_data_rename_campaign_action_permissions_to_journey_step.php
Labels: Change Type | Feature Cleanup

#1663 [ADVAPP-1620]: Feature Flag Cleanup: QnAAdvisorFeature
  app-modules/ai/src/Filament/Pages/ManageAiQnaAdvisorSettings.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/ManageCategories.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/ManageQnaQuestions.php
  app-modules/ai/src/Filament/Resources/QnaAdvisorResource/Pages/QnaAdvisorEmbed.php
  app/Features/QnaAdvisorFeature.php
  database/migrations/2025_06_19_142806_data_activate_qna_advisor_feature_flag.php
Labels: Change Type | Feature Cleanup

#1664 [ADVAPP-1619]: Feature Flag Cleanup: CaseTypeManagerAuditor
  app-modules/case-management/src/Filament/Resources/CaseTypeResource/Pages/ManageCaseTypeAuditors.php
  app-modules/case-management/src/Filament/Resources/CaseTypeResource/Pages/ManageCaseTypeManagers.php
  app/Features/CaseTypeManagerAuditor.php
  database/migrations/2025_06_23_162445_data_activate_case_type_manager_auditor.php
Labels: Change Type | Feature Cleanup

#1666 [ADVAPP-1614]: Feature Flag Cleanup: UnMatchInboundCommunicationFeature
  app-modules/engagement/database/migrations/2025_06_16_093108_data_activate_unmatch_inbound_communication_feature.php
  app-modules/engagement/src/Actions/CreateEngagementResponse.php
  app-modules/engagement/src/Exceptions/UnableToDetectAnyMatchingEducatablesFromSesS3EmailPayload.php
  app-modules/engagement/src/Jobs/ProcessSesS3InboundEmail.php
  app-modules/engagement/src/Jobs/UnmatchedInboundCommunicationsJob.php
  app/Features/UnMatchInboundCommunicationFeature.php
Labels: Change Type | Feature Cleanup

#1671 [ADVAPP-1617]: Resolve the security issue tracked under CVE-2025-6545 & [ADVAPP-1618]: Resolve the security issue tracked under CVE-2025-6547
  composer.json
  composer.lock
Labels: Change Type | Dependencies
