Repository canyongbs/advisingapp, pull requests merged in 2025-08, with the labels that each got.

#1753 [ADVAPP-1753]: Introduce the navigation item for Projects under Project Mangement
  app-modules/project/composer.json
  app-modules/project/database/migrations/2025_08_01_095717_seed_permissions_for_projects.php
  app-modules/project/database/migrations/2025_08_01_100758_data_activate_project_coming_soon_feature.php
  app-modules/project/src/Filament/Pages/Projects.php
  app-modules/project/src/ProjectPlugin.php
  app-modules/project/src/Providers/ProjectServiceProvider.php
  app/Features/ProjectComingSoonFeature.php
  composer.json
  composer.lock
Labels: Change Type | New Feature

#1760 [ADVAPP-1726]: Issues with notifying Users of subscription created for them
  app-modules/notification/src/Listeners/NotifyUserOfSubscriptionCreated.php
Labels: Change Type | Bug Fix

#1769 [ADVAPP-1794]: Resolve the security issue tracked under CVE-2025-27210 & [ADVAPP-1793]: Resolve the security issue tracked under CVE-2025-27209
  .nvmrc
  Dockerfile
  package-lock.json
Labels: Change Type | Dependencies

#1765 [ADVAPP-1778]: Feature Flag Cleanup: WorkflowFeature
  app-modules/form/src/Filament/Resources/FormResource/Pages/ManageFormWorkflows.php
  app-modules/workflow/database/migrations/2025_07_24_181533_data_activate_workflow_feature_flag.php
  app/Features/WorkflowFeature.php
Labels: Change Type | Feature Cleanup

#1766 [ADVAPP-1798]: Enhance the data model for students by including a new field for athletics status and athletic details
  _ide_helper_models.php
  app-modules/student-data-model/database/factories/StudentFactory.php
  app-modules/student-data-model/database/migrations/2025_08_08_063630_add_athletics_fields_to_students_table.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
  app-modules/student-data-model/src/Models/Student.php
  app/Features/AthleticFieldsFeature.php
  database/migrations/2025_08_08_082729_data_activate_athletic_fields_feature.php
Labels: Change Type | New Feature, Feature Flag Added

#1773 [ADVAPP-1744]: Clean up ApplicationSubmissionChecklistFeature
  app-modules/application/database/migrations/2025_07_30_073021_data_activate_application_submission_checklist_feature_flag.php
  app-modules/application/src/Filament/Resources/ApplicationResource/Pages/ManageApplicationSubmissions.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/ApplicationSubmissionsRelationManager.php
  app/Features/ApplicationSubmissionChecklistFeature.php
Labels: Change Type | Feature Cleanup

#1768 [ADVAPP-1804]: Enhance the SIS sync records tool to allow care team assignments
  app-modules/student-data-model/src/Actions/CompleteStudentDataImport.php
  app-modules/student-data-model/src/Actions/CreateTemporaryStudentDataImportTables.php
  app-modules/student-data-model/src/Filament/Imports/StudentImporter.php
Labels: Change Type | New Feature

#1774 [ADVAPP-1799]: Enhance the student data model with a value for academic standing
  _ide_helper_models.php
  app-modules/student-data-model/database/factories/StudentFactory.php
  app-modules/student-data-model/database/migrations/2025_08_11_153704_add_academic_standing_to_students_table.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/CreateStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Pages/EditStudent.php
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Schemas/StudentProfileInfolist.php
  app-modules/student-data-model/src/Models/Student.php
  app/Features/AcademicStandingFeature.php
  database/migrations/2025_08_11_155208_data_activate_academic_standing_feature.php
Labels: Change Type | New Feature, Feature Flag Added

#1779 [ADVAPP-1801]: Enhance the holistic student interface by including cards on the student display for courses attempted, courses completed, credits attempted, and credits earned
  app-modules/student-data-model/resources/views/filament/resources/student-resource/view-student.blade.php
  app-modules/student-data-model/src/Filament/Widgets/StudentAcademicStats.php
Labels: Change Type | New Feature

#1780 [ADVAPP-1810]: Introduce a new navigation group called Knowledge Management and relocate Resource Hub underneath it
  app/Filament/Clusters/DisplaySettings.php
  app/Filament/Clusters/InteractionManagement.php
  app/Filament/Clusters/OnlineAdmissions.php
  app/Filament/Clusters/ResourceHub.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: Change Type | Content or Styling Update

#1782 [ADVAPP-1812]: Relocate Schedule & Appointments from Premium Features to CRM at the end of the list
  app-modules/meeting-center/src/Filament/Resources/CalendarEventResource.php
Labels: Change Type | Content or Styling Update

#1781 [ADVAPP-1811]: Relocate Programs in Settings > Constituent Management > Programs to Knowledge Management > Support Programs
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsCategoryResource.php
  app-modules/basic-needs/src/Filament/Resources/BasicNeedsProgramResource.php
Labels: Change Type | Content or Styling Update

#1785 [ADVAPP-1823]: Some users have reported that the Resource Hub is still located under the CRM navigation group and displays the wrong interface under Knowledge Management
  app-modules/resource-hub/src/Filament/Resources/ResourceHubArticleResource.php
  app/Filament/Clusters/DisplaySettings.php
  app/Filament/Clusters/InteractionManagement.php
  app/Filament/Clusters/OnlineAdmissions.php
  app/Filament/Clusters/ResourceHub.php
Labels: Change Type | Bug Fix

#1788 [ADVAPP-1751]: Introduce an auto generated table of contents that is hyperlinked to the various headings of the research report
  app-modules/research/resources/js/results.js
  app-modules/research/resources/views/filament/pages/manage-research-requests.blade.php
  package-lock.json
  package.json
Labels: Change Type | New Feature

#1794 [ADVAPP-1816]: Cleanup ProjectFileFeature
  app-modules/project/database/migrations/2025_08_06_163328_data_activate_project_file_feature_flag.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageFiles.php
  app/Features/ProjectFileFeature.php
Labels: Change Type | Feature Cleanup

#1792 [ADVAPP-1817]: Cleanup EngagementSettingsFeature
  app-modules/engagement/src/Notifications/EngagementNotification.php
  app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
  app/Features/EngagementSettingsFeature.php
  database/migrations/2025_08_08_110955_data_activate_engagement_settings_feature.php
Labels: Change Type | Feature Cleanup

#1796 [ADVAPP-1775]: Ensure that Subscriptions take into account soft deleted Users and/or the Educatables to prevent unnecessary exceptions
  app-modules/campaign/src/Jobs/SubscriptionCampaignActionJob.php
  app-modules/notification/src/Filament/Actions/SubscribeBulkAction.php
  app-modules/workflow/src/Jobs/SubscriptionWorkflowActionJob.php
Labels: Change Type | Chore

#1752 [ADVAPP-1701]: Enhance analytics and implement granular filtering in student reports
  app-modules/report/src/Abstract/Concerns/HasFiltersForm.php
  app-modules/report/src/Filament/Widgets/Concerns/InteractsWithPageFilters.php
  app-modules/report/src/Filament/Widgets/MostEngagedStudentsTable.php
  app-modules/report/src/Filament/Widgets/MostRecentStudentsTable.php
  app-modules/report/src/Filament/Widgets/StudentCaseStats.php
  app-modules/report/src/Filament/Widgets/StudentCaseTable.php
  app-modules/report/src/Filament/Widgets/StudentCumulativeCountLineChart.php
  app-modules/report/src/Filament/Widgets/StudentDeliverableTable.php
  app-modules/report/src/Filament/Widgets/StudentEmailOptInOptOutPieChart.php
  app-modules/report/src/Filament/Widgets/StudentEngagementLineChart.php
  app-modules/report/src/Filament/Widgets/StudentEngagementStats.php
  app-modules/report/src/Filament/Widgets/StudentInteractionLineChart.php
  app-modules/report/src/Filament/Widgets/StudentInteractionStats.php
  app-modules/report/src/Filament/Widgets/StudentInteractionStatusPolarAreaChart.php
  app-modules/report/src/Filament/Widgets/StudentInteractionTypeDoughnutChart.php
  app-modules/report/src/Filament/Widgets/StudentInteractionUsersTable.php
  app-modules/report/src/Filament/Widgets/StudentSmsOptInOptOutPieChart.php
  app-modules/report/src/Filament/Widgets/StudentsStats.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentCaseStatsTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentCaseTableTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentCumulativeCountLineChartTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentDeliverableTableTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentEmailOptInOptOutPieChartTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentEngagementLineChartTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentEngagementStatsTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentInteractionLineChartTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentInteractionStatsTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentInteractionStatusPolarAreaChartTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentInteractionTypeDoughnutChartTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentInteractionUsersTableTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentSmsOptInOptOutPieChartTest.php
  app-modules/report/tests/Tenant/Filament/Widgets/StudentsStatsTest.php
  app-modules/student-data-model/resources/views/filament/pages/dashboard.blade.php
  app-modules/student-data-model/src/Filament/Pages/RetentionCrmDashboard.php
  app-modules/student-data-model/src/Filament/Widgets/StudentStats.php
  app-modules/student-data-model/src/Filament/Widgets/StudentsActionCenterWidget.php
  app-modules/student-data-model/tests/Tenant/Unit/RetentionCrmDashboardTest.php
  tests/.pest/snapshots/var/www/html/app-modules/prospect/tests/Tenant/Unit/RecruitmentCrmDashboardTest/it_renders_all_prospects_correctly_in_the_recruitment_dashboard_for_the_All_tab.snap
  tests/.pest/snapshots/var/www/html/app-modules/prospect/tests/Tenant/Unit/RecruitmentCrmDashboardTest/it_renders_subscribed_prospects_correctly_in_the_recruitment_dashboard_for_the_Subscribed_tab.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/ProspectEngagementLineChartTest/it_returns_correct_monthly_email_and_sms_engagement_data_for_prospects_within_the_given_date_range.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/ProspectInteractionLineChartTest/it_checks_prospect_interactions_monthly_line_chart.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/ProspectInteractionLineChartTest/it_returns_correct_data_for_prospect_interactions_within_the_given_date_range.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/ProspectInteractionStatusPolarAreaChartTest/it_returns_correct_data_for_prospect_interactions_status_within_the_given_date_range.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/ProspectReportLineChartTest/it_returns_correct_cumulative_prospect_counts_grouped_by_month_within_the_given_date_range.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/StudentCumulativeCountLineChartTest/it_returns_correct_cumulative_student_counts_grouped_by_month_within_the_given_date_range.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/StudentEngagementLineChartTest/it_returns_correct_monthly_email_and_sms_engagement_data_for_students_within_the_given_date_range.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/StudentInteractionLineChartTest/it_checks_student_interactions_monthly_line_chart.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/StudentInteractionLineChartTest/it_returns_correct_data_for_student_interactions_based_on_segment_filter.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/StudentInteractionLineChartTest/it_returns_correct_data_for_student_interactions_within_the_given_date_range.snap
  tests/.pest/snapshots/var/www/html/app-modules/report/tests/Tenant/Filament/Widgets/TaskCumulativeCountLineChartTest/it_returns_correct_cumulative_task_counts_grouped_by_month_within_the_given_date_range.snap
Labels: Change Type | Documentation

#1807 [ADVAPP-1757]: Introduce the ability to associate tasks with a project
  app-modules/project/src/Filament/Resources/ProjectResource.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageTasks.php
  app-modules/project/src/Models/Project.php
  app-modules/project/tests/Tenant/Filament/Resources/ProjectResource/Pages/ManageTasksTest.php
  app-modules/task/database/migrations/2025_08_20_205946_add_project_id_to_tasks_table.php
  app-modules/task/database/migrations/2025_08_20_210328_data_activate_associate_tasks_with_projects_feature_feature_flag.php
  app-modules/task/src/Models/Task.php
  app/Features/AssociateTasksWithProjectsFeature.php
Labels: Change Type | New Feature, Feature Flag Added

#1818 [ADVAPP-1764]: Cleanup ProjectComingSoonFeature
  app-modules/project/database/migrations/2025_08_01_100758_data_activate_project_coming_soon_feature.php
  app/Features/ProjectComingSoonFeature.php
Labels: Change Type | Feature Cleanup

#1784 [ADVAPP-1806]: Refactor Enrollment filter for segments to be Enrollment Count
  app-modules/student-data-model/src/Filament/Resources/StudentResource/Tables/StudentsTable.php
  app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/Concerns/SemesterSelectForOperator.php
  app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/EqualsOperatorWithEnrollmentSemester.php
  app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/HasMaxOperatorWithEnrollmentSemester.php
  app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/HasMinOperatorWithEnrollmentSemester.php
  app/Filament/Tables/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/IsEmptyOperatorWithEnrollmentSemester.php
Labels: Change Type | New Feature

#1826 [ADVAPP-1858]: Feature Flag Cleanup: ProjectMilestoneTargetDateFeature
  app-modules/project/database/migrations/2025_08_22_195945_add_target_date_to_project_milestone_table.php
  app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageMilestones.php
  app/Features/ProjectMilestoneTargetDateFeature.php
Labels: Change Type | Feature Cleanup

#1829 [ADVAPP-1856]: Some users have reported that the student Program modal contains a labeling error where “Graduation Date” is incorrectly displayed as “Graduration Date"
  app-modules/student-data-model/src/Filament/Resources/StudentResource/RelationManagers/ProgramsRelationManager.php
Labels: Change Type | Bug Fix

#1833 [Bugfix]: Fix Telnyx webhook
  app-modules/notification/src/Notifications/Channels/SmsChannel.php
Labels: Change Type | Bug Fix
